// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/menu-item';

export interface MenuItemProps {
  shortcut?: string;
  disabled?: boolean;
  icon?: string;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const MenuItem: FunctionComponent<MenuItemProps> = ({ shortcut, disabled, icon, children, ...rest }) => (
  <arc-menu-item shortcut={shortcut} disabled={disabled} icon={icon} {...rest}>
    {children}
  </arc-menu-item>
);
