// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/option';

export interface OptionProps {
  value?: string;
  disabled?: boolean;
  selected?: boolean;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Option: FunctionComponent<OptionProps> = ({ value, disabled, selected, children, ...rest }) =>
  h('arc-option', { value, disabled, selected, ...rest }, children);
