/**
 * subscriptions.js — connection-scoped subscriptions to things outside the
 * component.
 *
 * The problem this solves (finding #55): a ResizeObserver or an event listener
 * belongs to the component for as long as it is *connected*, but the natural
 * place to create one is `firstUpdated`, because that is the first moment the
 * shadow-DOM target exists. `firstUpdated` runs **once per element for its
 * entire lifetime**; `disconnectedCallback` runs **once per disconnection**.
 * Pairing them is a leak in reverse — the teardown is correct and repeatable,
 * the setup is not — so the first time the element is reparented it
 * permanently unsubscribes. It keeps rendering and keeps answering every
 * property, so nothing looks wrong.
 *
 * Four components had exactly this, in three spellings, and one of them
 * (`arc-truncate`) re-created its observer in `connectedCallback` while leaving
 * the matching `.observe()` in `firstUpdated` — a live observer watching
 * nothing. Getting half of it right is the tell: the bug is generated by the
 * split between *creating* a subscription and *pointing it at a rendered
 * target*, which is precisely where the two lifecycles diverge.
 *
 * So the rule is stated once, here, rather than restated per component:
 *
 *   - attach on `hostConnected` **or** on the first `hostUpdated` after it,
 *     whichever is the first moment the target actually exists;
 *   - detach on `hostDisconnected`, and arm for re-attachment;
 *   - re-attach if the target element is replaced between renders.
 *
 * As in `props.js`, the work runs through a **reactive controller** rather than
 * lifecycle overrides. A controller's hooks fire regardless of what the host
 * overrides, so a component that forgets `super.connectedCallback()` cannot
 * silently lose its subscription — which is the same failure mode this file
 * exists to remove.
 */

/**
 * A subscription keyed to the host's connection rather than to its first render.
 *
 * `resolve` returns the current target or a falsy value if it is not rendered
 * yet; `attach`/`detach` do the actual subscribing. Kept private because the
 * two exported helpers below are the intended surface — a third kind of
 * subscription should be added here rather than by hand-rolling a controller.
 */
class ConnectedSubscription {
  constructor(host, resolve, attach, detach) {
    this.host = host;
    this._resolve = resolve;
    this._attach = attach;
    this._detach = detach;
    this._target = null;
    host.addController(this);
  }

  hostConnected() {
    this._sync();
  }

  /**
   * The first connection has no shadow DOM yet, so `hostConnected` cannot find
   * the target and this is where the initial attach actually lands. It also
   * covers a target the host re-renders into a different element.
   */
  hostUpdated() {
    this._sync();
  }

  hostDisconnected() {
    this._release();
  }

  _sync() {
    const next = this._resolve();
    if (next === this._target) return;
    this._release();
    if (!next) return;
    this._target = next;
    this._attach(next);
  }

  _release() {
    if (!this._target) return;
    this._detach(this._target);
    this._target = null;
  }
}

/** Resolve a target given as a selector into the host's shadow root, or as a getter. */
function targetResolver(host, target) {
  if (typeof target === 'function') return () => target(host);
  return () => host.shadowRoot?.querySelector(target) ?? null;
}

/**
 * Observe a rendered element's size for as long as the host is connected.
 *
 * `callback` receives the observed element, so a component does not have to
 * close over a target that may be replaced between renders — the stale-closure
 * variant of the same bug.
 *
 * One `ResizeObserver` per call site, created lazily and reused across
 * connection cycles; `unobserve` rather than `disconnect` on the way out, so the
 * instance stays valid for re-attachment.
 */
export function observeResize(host, target, callback) {
  if (typeof ResizeObserver === 'undefined') return null;
  const resolve = targetResolver(host, target);
  let observer = null;
  return new ConnectedSubscription(
    host,
    resolve,
    (el) => {
      observer ??= new ResizeObserver(() => callback(el));
      observer.observe(el);
    },
    (el) => observer?.unobserve(el),
  );
}

/**
 * Observe a rendered element's intersection with the viewport for as long as the
 * host is connected.
 *
 * Same contract as `observeResize`, with one addition worth knowing: a `target`
 * resolver that returns `null` releases the observation without tearing the
 * subscription down, and returning an element again re-attaches it. That is how
 * a component turns the observer off for a state rather than a lifecycle —
 * arc-infinite-scroll stops watching once `finished` or `disabled` — without
 * hand-rolling a second teardown path that then has to pair correctly.
 *
 * `options` are captured when the observer is first created, so a component
 * whose rootMargin depends on a reactive prop needs its own handling; none does
 * today, and the previous hand-rolled version did not either.
 */
export function observeIntersect(host, target, callback, options) {
  if (typeof IntersectionObserver === 'undefined') return null;
  const resolve = targetResolver(host, target);
  let observer = null;
  return new ConnectedSubscription(
    host,
    resolve,
    (el) => {
      observer ??= new IntersectionObserver((entries) => callback(entries, el), options);
      observer.observe(el);
    },
    (el) => observer?.unobserve(el),
  );
}

/**
 * Listen on a rendered element for as long as the host is connected.
 *
 * `handler` is subscribed and unsubscribed by identity, so pass a bound method
 * held on the instance — a fresh arrow per attach would still work here, since
 * this controller owns both halves, but it makes the component harder to reason
 * about from the outside.
 */
export function listen(host, target, type, handler, options) {
  const resolve = targetResolver(host, target);
  return new ConnectedSubscription(
    host,
    resolve,
    (el) => el.addEventListener(type, handler, options),
    (el) => el.removeEventListener(type, handler, options),
  );
}

/**
 * Observe attribute changes on an element for as long as the host is connected.
 *
 * The third kind, added here rather than hand-rolled per this file's own rule.
 * Its case is different from the other two in one way worth stating: the target
 * is usually **outside** the host — `document.documentElement` for
 * `arc-theme-toggle`, which has to follow the page theme rather than only write
 * it (finding #15). A subscription to shared global state is exactly the kind
 * that must not survive a disconnect, because every stale instance keeps
 * answering the callback.
 *
 * `names` is the attribute filter, passed straight to `MutationObserver`.
 * `callback` receives the observed element, matching the other two helpers, so
 * a component never closes over a target that may be replaced.
 *
 * One observer per call site, created lazily and reused across connection
 * cycles. `disconnect()` rather than an unobserve — MutationObserver has no
 * per-target release, and re-`observe()` on the next attach restores it.
 */
export function observeAttributes(host, target, names, callback) {
  if (typeof MutationObserver === 'undefined') return null;
  const resolve = targetResolver(host, target);
  let observer = null;
  return new ConnectedSubscription(
    host,
    resolve,
    (el) => {
      observer ??= new MutationObserver(() => callback(el));
      observer.observe(el, { attributes: true, attributeFilter: names });
    },
    () => observer?.disconnect(),
  );
}
