// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/color-picker';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-color-picker': Record<string, unknown>;
    }
  }
}

export interface ColorPickerProps {
  required?: boolean;
  readonly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  value?: string;
  name?: string;
  presets?: string[];
  disabled?: boolean;
  label?: string;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const ColorPicker: Component<ColorPickerProps> = (props) => {
  const [local, rest] = splitProps(props, ['required', 'readonly', 'size', 'value', 'name', 'presets', 'disabled', 'label', 'onArcInput', 'onArcChange']);
  return (
    <arc-color-picker required={local.required} readonly={local.readonly} size={local.size} value={local.value} name={local.name} presets={local.presets} disabled={local.disabled} label={local.label} on:arc-input={local.onArcInput} on:arc-change={local.onArcChange} {...rest}>
    </arc-color-picker>
  );
};
