// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/copy-button';

export interface CopyButtonProps {
  value?: string;
  disabled?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const CopyButton: Component<CopyButtonProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'disabled', 'children']);
  return (
    <arc-copy-button value={local.value} disabled={local.disabled} {...rest}>
      {local.children}
    </arc-copy-button>
  );
};
