// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/copy-button';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-copy-button': Record<string, unknown>;
    }
  }
}

export interface CopyButtonProps {
  value?: string;
  disabled?: boolean;
  onArcCopy?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const CopyButton: Component<CopyButtonProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'disabled', 'onArcCopy']);
  return (
    <arc-copy-button value={local.value} disabled={local.disabled} on:arc-copy={local.onArcCopy} {...rest}>
    </arc-copy-button>
  );
};
