// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component } from 'solid-js';
import '@arclux/arc-ui/date-picker';
import type { ArcDatePicker } from '@arclux/arc-ui/date-picker';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-date-picker': Record<string, unknown>;
    }
  }
}

export interface DatePickerProps {
  required?: boolean;
  readonly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  value?: string;
  name?: string;
  min?: string;
  max?: string;
  placeholder?: string;
  disabled?: boolean;
  label?: string;
  open?: boolean;
  locale?: string;
  firstDayOfWeek?: number;
  onArcChange?: (e: CustomEvent) => void;
  /** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
  ref?: ArcDatePicker | ((el: ArcDatePicker) => void);
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const DatePicker: Component<DatePickerProps> = (props) => {
  const [local, rest] = splitProps(props, ['required', 'readonly', 'size', 'value', 'name', 'min', 'max', 'placeholder', 'disabled', 'label', 'open', 'locale', 'firstDayOfWeek', 'onArcChange', 'ref']);
  return (
    <arc-date-picker required={local.required} readonly={local.readonly} size={local.size} value={local.value} name={local.name} min={local.min} max={local.max} placeholder={local.placeholder} disabled={local.disabled} label={local.label} open={local.open} locale={local.locale} prop:firstDayOfWeek={local.firstDayOfWeek} on:arc-change={local.onArcChange} ref={(el: ArcDatePicker) => { if (typeof local.ref === 'function') local.ref(el); }} {...rest}>
    </arc-date-picker>
  );
};
