// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/date-range-picker';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-date-range-picker': Record<string, unknown>;
    }
  }
}

export interface DateRangePickerProps {
  size?: 'sm' | 'md' | 'lg';
  locale?: string;
  firstDayOfWeek?: number;
  start?: string;
  end?: string;
  name?: string;
  min?: string;
  max?: string;
  months?: number;
  presets?: Array<{label:string,days:number}>;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  label?: string;
  open?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const DateRangePicker: Component<DateRangePickerProps> = (props) => {
  const [local, rest] = splitProps(props, ['size', 'locale', 'firstDayOfWeek', 'start', 'end', 'name', 'min', 'max', 'months', 'presets', 'placeholder', 'disabled', 'required', 'label', 'open', 'onArcChange']);
  return (
    <arc-date-range-picker size={local.size} locale={local.locale} prop:firstDayOfWeek={local.firstDayOfWeek} start={local.start} end={local.end} name={local.name} min={local.min} max={local.max} months={local.months} presets={local.presets} placeholder={local.placeholder} disabled={local.disabled} required={local.required} label={local.label} open={local.open} on:arc-change={local.onArcChange} {...rest}>
    </arc-date-range-picker>
  );
};
