// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/field-row';
import type { ArcFieldRow } from '@arclux/arc-ui/field-row';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-field-row': Record<string, unknown>;
    }
  }
}

export interface FieldRowProps {
  label?: string;
  children?: JSX.Element;
  /** The element, for the methods it is driven by: focusFirstField() and focusHandle(). */
  ref?: ArcFieldRow | ((el: ArcFieldRow) => void);
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const FieldRow: Component<FieldRowProps> = (props) => {
  const [local, rest] = splitProps(props, ['label', 'children', 'ref']);
  return (
    <arc-field-row label={local.label} ref={(el: ArcFieldRow) => { if (typeof local.ref === 'function') local.ref(el); }} {...rest}>
      {local.children}
    </arc-field-row>
  );
};
