// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/file-upload';

export interface FileUploadProps {
  accept?: string;
  multiple?: boolean;
  maxSize?: number;
  disabled?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const FileUpload: Component<FileUploadProps> = (props) => {
  const [local, rest] = splitProps(props, ['accept', 'multiple', 'maxSize', 'disabled', 'children']);
  return (
    <arc-file-upload accept={local.accept} multiple={local.multiple} maxSize={local.maxSize} disabled={local.disabled} {...rest}>
      {local.children}
    </arc-file-upload>
  );
};
