// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/inline-edit';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-inline-edit': Record<string, unknown>;
    }
  }
}

export interface InlineEditProps {
  required?: boolean;
  readonly?: boolean;
  value?: string;
  label?: string;
  name?: string;
  placeholder?: string;
  multiline?: boolean;
  disabled?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  onArcCancel?: (e: CustomEvent) => void;
  onArcInput?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const InlineEdit: Component<InlineEditProps> = (props) => {
  const [local, rest] = splitProps(props, ['required', 'readonly', 'value', 'label', 'name', 'placeholder', 'multiline', 'disabled', 'onArcChange', 'onArcCancel', 'onArcInput', 'children']);
  return (
    <arc-inline-edit required={local.required} readonly={local.readonly} value={local.value} label={local.label} name={local.name} placeholder={local.placeholder} multiline={local.multiline} disabled={local.disabled} on:arc-change={local.onArcChange} on:arc-cancel={local.onArcCancel} on:arc-input={local.onArcInput} {...rest}>
      {local.children}
    </arc-inline-edit>
  );
};
