// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface InputProps {
  type?: string;
  name?: string;
  label?: string;
  placeholder?: string;
  value?: string;
  disabled?: boolean;
  required?: boolean;
  error?: string;
  size?: 'sm' | 'lg';
  multiline?: boolean;
  rows?: number;
  _hasPrefix?: string;
  _hasSuffix?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Input: Component<InputProps> = (props) => {
  const [local, rest] = splitProps(props, ['type', 'name', 'label', 'placeholder', 'value', 'disabled', 'required', 'error', 'size', 'multiline', 'rows', '_hasPrefix', '_hasSuffix', 'children']);
  return (
    <arc-input type={local.type} name={local.name} label={local.label} placeholder={local.placeholder} value={local.value} disabled={local.disabled} required={local.required} error={local.error} size={local.size} multiline={local.multiline} rows={local.rows} _hasPrefix={local._hasPrefix} _hasSuffix={local._hasSuffix} {...rest}>
      {local.children}
    </arc-input>
  );
};
