// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/label';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-label': Record<string, unknown>;
    }
  }
}

export interface LabelProps {
  for?: string;
  required?: boolean;
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Label: Component<LabelProps> = (props) => {
  const [local, rest] = splitProps(props, ['for', 'required', 'size', 'disabled', 'children']);
  return (
    <arc-label for={local.for} required={local.required} size={local.size} disabled={local.disabled} {...rest}>
      {local.children}
    </arc-label>
  );
};
