// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/masked-input';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-masked-input': Record<string, unknown>;
    }
  }
}

export interface MaskedInputProps {
  mask?: string;
  value?: string;
  placeholderChar?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  required?: boolean;
  autocomplete?: string;
  error?: string;
  size?: 'sm' | 'md' | 'lg';
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const MaskedInput: Component<MaskedInputProps> = (props) => {
  const [local, rest] = splitProps(props, ['mask', 'value', 'placeholderChar', 'label', 'name', 'disabled', 'required', 'autocomplete', 'error', 'size', 'onArcInput', 'onArcChange', 'children']);
  return (
    <arc-masked-input mask={local.mask} value={local.value} prop:placeholderChar={local.placeholderChar} label={local.label} name={local.name} disabled={local.disabled} required={local.required} autocomplete={local.autocomplete} error={local.error} size={local.size} on:arc-input={local.onArcInput} on:arc-change={local.onArcChange} {...rest}>
      {local.children}
    </arc-masked-input>
  );
};
