// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/radio-group';

export interface RadioGroupProps {
  value?: string;
  name?: string;
  disabled?: boolean;
  size?: 'sm' | 'lg';
  orientation?: 'horizontal';
  onArcChange?: (e: CustomEvent) => void;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const RadioGroup: Component<RadioGroupProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'name', 'disabled', 'size', 'orientation', 'onArcChange', 'children']);
  return (
    <arc-radio-group value={local.value} name={local.name} disabled={local.disabled} size={local.size} orientation={local.orientation} on:arc-change={local.onArcChange} {...rest}>
      {local.children}
    </arc-radio-group>
  );
};
