// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/search';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-search': Record<string, unknown>;
    }
  }
}

export interface SearchProps {
  value?: string;
  placeholder?: string;
  label?: string;
  disabled?: boolean;
  loading?: boolean;
  open?: boolean;
  onArcInput?: (e: CustomEvent) => void;
  onArcClear?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  onArcSelect?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Search: Component<SearchProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'placeholder', 'label', 'disabled', 'loading', 'open', 'onArcInput', 'onArcClear', 'onArcChange', 'onArcSelect', 'children']);
  return (
    <arc-search value={local.value} placeholder={local.placeholder} label={local.label} disabled={local.disabled} loading={local.loading} open={local.open} on:arc-input={local.onArcInput} on:arc-clear={local.onArcClear} on:arc-change={local.onArcChange} on:arc-select={local.onArcSelect} {...rest}>
      {local.children}
    </arc-search>
  );
};
