// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/switch-group';

export interface SwitchGroupProps {
  label?: string;
  orientation?: 'horizontal';
  size?: string;
  disabled?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const SwitchGroup: Component<SwitchGroupProps> = (props) => {
  const [local, rest] = splitProps(props, ['label', 'orientation', 'size', 'disabled', 'children']);
  return (
    <arc-switch-group label={local.label} orientation={local.orientation} size={local.size} disabled={local.disabled} {...rest}>
      {local.children}
    </arc-switch-group>
  );
};
