// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/textarea';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-textarea': Record<string, unknown>;
    }
  }
}

export interface TextareaProps {
  value?: string;
  placeholder?: string;
  label?: string;
  rows?: number;
  maxlength?: number;
  disabled?: boolean;
  readonly?: boolean;
  resize?: 'none' | 'vertical' | 'horizontal' | 'both';
  size?: 'sm' | 'md' | 'lg';
  autoResize?: boolean;
  error?: string;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Textarea: Component<TextareaProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'placeholder', 'label', 'rows', 'maxlength', 'disabled', 'readonly', 'resize', 'size', 'autoResize', 'error', 'onArcInput', 'onArcChange', 'children']);
  return (
    <arc-textarea value={local.value} placeholder={local.placeholder} label={local.label} rows={local.rows} maxlength={local.maxlength} disabled={local.disabled} readonly={local.readonly} resize={local.resize} size={local.size} prop:autoResize={local.autoResize} error={local.error} on:arc-input={local.onArcInput} on:arc-change={local.onArcChange} {...rest}>
      {local.children}
    </arc-textarea>
  );
};
