// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component } from 'solid-js';
import '@arclux/arc-ui/tree-select';
import type { ArcTreeSelect } from '@arclux/arc-ui/tree-select';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-tree-select': Record<string, unknown>;
    }
  }
}

export interface TreeSelectProps {
  required?: boolean;
  readonly?: boolean;
  items?: Array<{value: string, label: string, children?: Array<object>, disabled?: boolean}>;
  value?: string;
  expandedValues?: string[];
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  error?: string;
  open?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  /** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
  ref?: ArcTreeSelect | ((el: ArcTreeSelect) => void);
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const TreeSelect: Component<TreeSelectProps> = (props) => {
  const [local, rest] = splitProps(props, ['required', 'readonly', 'items', 'value', 'expandedValues', 'placeholder', 'label', 'name', 'disabled', 'size', 'error', 'open', 'onArcChange', 'ref']);
  return (
    <arc-tree-select required={local.required} readonly={local.readonly} items={local.items} value={local.value} prop:expandedValues={local.expandedValues} placeholder={local.placeholder} label={local.label} name={local.name} disabled={local.disabled} size={local.size} error={local.error} open={local.open} on:arc-change={local.onArcChange} ref={(el: ArcTreeSelect) => { if (typeof local.ref === 'function') local.ref(el); }} {...rest}>
    </arc-tree-select>
  );
};
