#!/usr/bin/env node
/**
 * generate/group-barrels.js
 *
 * Writes one barrel per domain group — `src/marketing/index.js`,
 * `src/media/index.js` — from the `@arc-group` annotations in component source.
 *
 * A domain group is the second catalog axis V4-SCOPE §1 added: tier says what
 * *kind* of component this is, group says what kind of *product* it is for.
 * The marketing cluster and the DAW primitives are not bad components, they are
 * badly grouped ones, and a flat catalog of 200 tags had no way to say so — the
 * only tools it offered were deletion and exile, which is why the v4 cut list
 * started at ~25 tags and ended at 5.
 *
 * Mechanically the group is a published subpath and nothing more:
 *
 *   import { ArcCarousel } from '@arclux/arc-ui/marketing';
 *
 * The components stay in this package, this repo, this test suite and the same
 * derived conformance run; they keep their tier, so their wrappers still
 * generate into `content/`, `data/`, `typography/`, `input/`. What changes is
 * that prism's `barrelExclude` keeps them out of the default barrel, so a bare
 * `@arclux/arc-ui` import no longer pulls a landing-page carousel into an admin
 * dashboard's bundle. That exclusion is derived from the same annotations this
 * file reads (see prism.config.js), and `scripts/checks/group-gating.js` fails
 * the build if the two ever disagree.
 *
 * Barrels re-export from each component's `.register.js`, not from its class
 * module or its tier barrel:
 *
 *   - `.register.js` rather than the class module, because that is what the
 *     tier barrels do and what consumers expect from an ARC barrel — importing
 *     the name defines the element. A barrel that handed back an unregistered
 *     class would be a different contract from every other entry point.
 *   - the register file rather than `../content/index.js`, because the tier
 *     barrel is exactly where `barrelExclude` has just removed these names
 *     from. Re-exporting through it would resolve to nothing.
 *
 * Run via: pnpm generate (Components phase, after registrations and before the
 * prism step whose exclusions it complements)
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { findGroups, SRC_DIR } from '../lib/component-tags.js';

/**
 * Extra non-element modules a group publishes, as `[group, specifier]`.
 *
 * `shared/time-scale.js` is the only entry: it is a published subpath today
 * (`@arclux/arc-ui/shared/time-scale`) and belongs to the DAW consumer that
 * `arc-waveform` and `arc-level-meter` serve, so V4-SCOPE §2.1 moves it under
 * `/media` with them. The file stays in `shared/` — it is a plain coordinate
 * utility with no DOM and no group of its own, and the subpath is the contract
 * that moved, not the source layout.
 *
 * Re-exported with `export *` rather than a name list: this is a move, so the
 * group barrel's surface should be exactly the module's, including whatever it
 * gains later. A hand-written name list here would be a second declaration of
 * the same API, and the twelve functions it currently has make it a list that
 * would be wrong within one commit of anybody touching the module.
 */
const EXTRA_MODULES = [['media', '../shared/time-scale.js']];

const HEADER = '// Generated by scripts/generate/group-barrels.js — do not edit';

const groups = findGroups();
let written = 0;

for (const [group, components] of groups) {
  const lines = [
    HEADER,
    `//`,
    `// The \`${group}\` domain group — reachable as \`@arclux/arc-ui/${group}\`,`,
    `// deliberately absent from the default \`@arclux/arc-ui\` barrel.`,
    ``,
  ];

  for (const comp of components) {
    const stem = comp.file.replace(/\.js$/, '');
    lines.push(`export { ${comp.className} } from '../${comp.tier}/${stem}.register.js';`);
  }

  for (const [g, specifier] of EXTRA_MODULES) {
    if (g !== group) continue;
    // Asserted rather than assumed: a rename or a move would otherwise produce
    // a barrel that only fails at a consumer's bundler, long after this ran
    // green. `export *` from a missing module is not an error at parse time.
    const modPath = resolve(SRC_DIR, group, specifier);
    if (!existsSync(modPath)) {
      console.error(`generate-group-barrels: ${group} → ${specifier} does not exist`);
      process.exit(1);
    }
    const source = readFileSync(modPath, 'utf-8');
    if (!/^export\s/m.test(source)) {
      console.error(`generate-group-barrels: ${specifier} exports nothing`);
      process.exit(1);
    }
    lines.push('', `export * from '${specifier}';`);
  }

  const dir = resolve(SRC_DIR, group);
  mkdirSync(dir, { recursive: true });
  writeFileSync(resolve(dir, 'index.js'), lines.join('\n') + '\n');
  written++;
  console.log(`generate-group-barrels: ${group} — ${components.length} component(s)`);
}

if (written === 0) {
  console.error('generate-group-barrels: no groups defined — GROUPS is empty, which is not a state this repo has.');
  process.exit(1);
}
