// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface AnchorNavProps {
  orientation?: 'vertical';
  value?: string;
  items?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const AnchorNav: FunctionComponent<AnchorNavProps> = ({ orientation, value, items, children, ...rest }) => (
  <arc-anchor-nav orientation={orientation} value={value} items={items} {...rest}>
    {children}
  </arc-anchor-nav>
);
