// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/breadcrumb-menu';

export interface BreadcrumbMenuProps {
  items?: string;
  label?: string;
  onArcNavigate?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const BreadcrumbMenu: FunctionComponent<BreadcrumbMenuProps> = ({ items, label, onArcNavigate, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcNavigate) {
      const fn: EventListener = (e) => onArcNavigate(e as CustomEvent);
      el.addEventListener('arc-navigate', fn);
      listeners.push(['arc-navigate', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcNavigate]);
  return (
    <arc-breadcrumb-menu ref={ref} items={items} label={label} {...rest}>
      {children}
    </arc-breadcrumb-menu>
  );
};
