// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface CommandBarProps {
  placeholder?: string;
  value?: string;
  icon?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const CommandBar: FunctionComponent<CommandBarProps> = ({ placeholder, value, icon, children, ...rest }) => (
  <arc-command-bar placeholder={placeholder} value={value} icon={icon} {...rest}>
    {children}
  </arc-command-bar>
);
