// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface DrawerProps {
  open?: boolean;
  position?: 'left' | 'right';
  heading?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Drawer: FunctionComponent<DrawerProps> = ({ open, position, heading, children, ...rest }) => (
  <arc-drawer open={open} position={position} heading={heading} {...rest}>
    {children}
  </arc-drawer>
);
