// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/drawer';

export interface DrawerProps {
  open?: boolean;
  position?: 'left' | 'right';
  heading?: string;
  onArcClose?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Drawer: FunctionComponent<DrawerProps> = ({ open, position, heading, onArcClose, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcClose) {
      const fn: EventListener = (e) => onArcClose(e as CustomEvent);
      el.addEventListener('arc-close', fn);
      listeners.push(['arc-close', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcClose]);
  return (
    <arc-drawer ref={ref} open={open} position={position} heading={heading} {...rest}>
      {children}
    </arc-drawer>
  );
};
