// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/link';

export interface LinkProps {
  href?: string;
  variant?: 'default' | 'muted' | 'nav';
  underline?: 'hover' | 'always' | 'never';
  active?: boolean;
  external?: boolean;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Link: FunctionComponent<LinkProps> = ({ href, variant, underline, active, external, children, ...rest }) =>
  h('arc-link', { href, variant, underline, active, external, ...rest }, children);
