// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/navigation-menu';

export interface NavigationMenuProps {
  label?: string;
  onArcMobileMenuToggle?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const NavigationMenu: FunctionComponent<NavigationMenuProps> = ({ label, onArcMobileMenuToggle, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcMobileMenuToggle) {
      const fn: EventListener = (e) => onArcMobileMenuToggle(e as CustomEvent);
      el.addEventListener('arc-mobile-menu-toggle', fn);
      listeners.push(['arc-mobile-menu-toggle', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcMobileMenuToggle]);
  return h('arc-navigation-menu', { ref, label, ...rest }, children);
};
