// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/page-indicator';

export interface PageIndicatorProps {
  count?: number;
  value?: number;
  clickable?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const PageIndicator: FunctionComponent<PageIndicatorProps> = ({ count, value, clickable, onArcChange, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return (
    <arc-page-indicator ref={ref} count={count} value={value} clickable={clickable} {...rest}>
      {children}
    </arc-page-indicator>
  );
};
