// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/sidebar';

export interface SidebarProps {
  active?: string;
  collapsed?: boolean;
  position?: 'right';
  width?: string;
  glow?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Sidebar: FunctionComponent<SidebarProps> = ({ active, collapsed, position, width, glow, children, ...rest }) => (
  <arc-sidebar active={active} collapsed={collapsed} position={position} width={width} glow={glow} {...rest}>
    {children}
  </arc-sidebar>
);
