// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/sidebar-section';

export interface SidebarSectionProps {
  heading?: string;
  collapsible?: boolean;
  open?: boolean;
  onArcToggle?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const SidebarSection: FunctionComponent<SidebarSectionProps> = ({ heading, collapsible, open, onArcToggle, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcToggle) {
      const fn: EventListener = (e) => onArcToggle(e as CustomEvent);
      el.addEventListener('arc-toggle', fn);
      listeners.push(['arc-toggle', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcToggle]);
  return (
    <arc-sidebar-section ref={ref} heading={heading} collapsible={collapsible} open={open} {...rest}>
      {children}
    </arc-sidebar-section>
  );
};
