// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/sidebar-link';

export interface SidebarLinkProps {
  href?: string;
  active?: boolean;
  level?: number;
  icon?: string;
  external?: boolean;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const SidebarLink: FunctionComponent<SidebarLinkProps> = ({ href, active, level, icon, external, children, ...rest }) =>
  h('arc-sidebar-link', { href, active, level, icon, external, ...rest }, children);
