// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/skip-link';

export interface SkipLinkProps {
  target?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const SkipLink: FunctionComponent<SkipLinkProps> = ({ target, children, ...rest }) => (
  <arc-skip-link target={target} {...rest}>
    {children}
  </arc-skip-link>
);
