// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/stepper-nav';

export interface StepperNavProps {
  steps?: string;
  active?: number;
  linear?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const StepperNav: FunctionComponent<StepperNavProps> = ({ steps, active, linear, children, ...rest }) => (
  <arc-stepper-nav steps={steps} active={active} linear={linear} {...rest}>
    {children}
  </arc-stepper-nav>
);
