// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface TabProps {
  label?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Tab: FunctionComponent<TabProps> = ({ label, children, ...rest }) => (
  <arc-tab label={label} {...rest}>
    {children}
  </arc-tab>
);
