// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface TabsProps {
  selected?: number;
  align?: 'center' | 'end';
  variant?: 'pills';
  _tabs?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Tabs: FunctionComponent<TabsProps> = ({ selected, align, variant, _tabs, children, ...rest }) => (
  <arc-tabs selected={selected} align={align} variant={variant} _tabs={_tabs} {...rest}>
    {children}
  </arc-tabs>
);
