// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/tabs';

export interface TabsProps {
  selected?: number;
  align?: 'center' | 'end';
  variant?: 'pills';
  orientation?: 'vertical';
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Tabs: FunctionComponent<TabsProps> = ({ selected, align, variant, orientation, children, ...rest }) => (
  <arc-tabs selected={selected} align={align} variant={variant} orientation={orientation} {...rest}>
    {children}
  </arc-tabs>
);
