// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/tree-item';

export interface TreeItemProps {
  label?: string;
  icon?: string;
  expanded?: boolean;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const TreeItem: FunctionComponent<TreeItemProps> = ({ label, icon, expanded, children, ...rest }) =>
  h('arc-tree-item', { label, icon, expanded, ...rest }, children);
