// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/anchor-nav';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-anchor-nav': Record<string, unknown>;
    }
  }
}

export interface AnchorNavProps {
  orientation?: 'vertical' | 'horizontal';
  value?: string;
  items?: Array<{label: string, value: string}>;
  onArcChange?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const AnchorNav: Component<AnchorNavProps> = (props) => {
  const [local, rest] = splitProps(props, ['orientation', 'value', 'items', 'onArcChange', 'children']);
  return (
    <arc-anchor-nav orientation={local.orientation} value={local.value} items={local.items} on:arc-change={local.onArcChange} {...rest}>
      {local.children}
    </arc-anchor-nav>
  );
};
