// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/breadcrumb-menu';

export interface BreadcrumbMenuProps {
  items?: string;
  label?: string;
  onArcNavigate?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const BreadcrumbMenu: Component<BreadcrumbMenuProps> = (props) => {
  const [local, rest] = splitProps(props, ['items', 'label', 'onArcNavigate', 'children']);
  return (
    <arc-breadcrumb-menu items={local.items} label={local.label} on:arc-navigate={local.onArcNavigate} {...rest}>
      {local.children}
    </arc-breadcrumb-menu>
  );
};
