// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/drawer';

export interface DrawerProps {
  open?: boolean;
  position?: 'left' | 'right';
  heading?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Drawer: Component<DrawerProps> = (props) => {
  const [local, rest] = splitProps(props, ['open', 'position', 'heading', 'children']);
  return (
    <arc-drawer open={local.open} position={local.position} heading={local.heading} {...rest}>
      {local.children}
    </arc-drawer>
  );
};
