// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface LinkProps {
  href?: string;
  variant?: 'muted' | 'nav';
  underline?: 'always' | 'never';
  active?: boolean;
  external?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Link: Component<LinkProps> = (props) => {
  const [local, rest] = splitProps(props, ['href', 'variant', 'underline', 'active', 'external', 'children']);
  return (
    <arc-link href={local.href} variant={local.variant} underline={local.underline} active={local.active} external={local.external} {...rest}>
      {local.children}
    </arc-link>
  );
};
