// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface NavItemProps {
  href?: string;
  active?: boolean;
  variant?: string;
  description?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const NavItem: Component<NavItemProps> = (props) => {
  const [local, rest] = splitProps(props, ['href', 'active', 'variant', 'description', 'children']);
  return (
    <arc-nav-item href={local.href} active={local.active} variant={local.variant} description={local.description} {...rest}>
      {local.children}
    </arc-nav-item>
  );
};
