// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface TabProps {
  label?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Tab: Component<TabProps> = (props) => {
  const [local, rest] = splitProps(props, ['label', 'children']);
  return (
    <arc-tab label={local.label} {...rest}>
      {local.children}
    </arc-tab>
  );
};
