// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/tabs';

export interface TabsProps {
  selected?: number;
  align?: 'center' | 'end';
  variant?: 'pills';
  orientation?: 'vertical';
  onArcChange?: (e: CustomEvent) => void;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Tabs: Component<TabsProps> = (props) => {
  const [local, rest] = splitProps(props, ['selected', 'align', 'variant', 'orientation', 'onArcChange', 'children']);
  return (
    <arc-tabs selected={local.selected} align={local.align} variant={local.variant} orientation={local.orientation} on:arc-change={local.onArcChange} {...rest}>
      {local.children}
    </arc-tabs>
  );
};
