// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface TopBarProps {
  heading?: string;
  fixed?: boolean;
  contained?: string;
  menuOpen?: boolean;
  mobileMenu?: string;
  menuPosition?: string;
  navAlign?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const TopBar: Component<TopBarProps> = (props) => {
  const [local, rest] = splitProps(props, ['heading', 'fixed', 'contained', 'menuOpen', 'mobileMenu', 'menuPosition', 'navAlign', 'children']);
  return (
    <arc-top-bar heading={local.heading} fixed={local.fixed} contained={local.contained} menuOpen={local.menuOpen} mobileMenu={local.mobileMenu} menuPosition={local.menuPosition} navAlign={local.navAlign} {...rest}>
      {local.children}
    </arc-top-bar>
  );
};
