// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-top-bar',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-top-bar [attr.heading]="heading" [fixed]="fixed" [menuOpen]="menuOpen" (arc-toggle)="arcToggle.emit($event)"><ng-content /></arc-top-bar>`,
})
export class TopBar {
  @Input() heading: string = '';
  @Input() fixed: boolean = false;
  @Input() menuOpen: boolean = false;
  @Output() arcToggle = new EventEmitter<CustomEvent>();
}
