// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcButtonGroup } from '@arclux/arc-ui/button-group';

export interface ButtonGroupProps {
  orientation?: 'vertical';
  size?: string;
  variant?: string;
  className?: string;
  children?: React.ReactNode;
}

export const ButtonGroup = createComponent({
  tagName: 'arc-button-group',
  elementClass: ArcButtonGroup,
  react: React,
});
