// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcColorPicker } from '@arclux/arc-ui/color-picker';

export interface ColorPickerProps {
  size?: 'sm' | 'md' | 'lg';
  value?: string;
  name?: string;
  presets?: string[];
  disabled?: boolean;
  label?: string;
  className?: string;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
}

export const ColorPicker = createComponent({
  tagName: 'arc-color-picker',
  elementClass: ArcColorPicker,
  react: React,
  events: {
    onArcInput: 'arc-input' as EventName<CustomEvent>,
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
