// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcCopyButton } from '@arclux/arc-ui/copy-button';

export interface CopyButtonProps {
  value?: string;
  disabled?: boolean;
  className?: string;
  onArcCopy?: (e: CustomEvent) => void;
  onClick?: (e: Event) => void;
}

export const CopyButton = createComponent({
  tagName: 'arc-copy-button',
  elementClass: ArcCopyButton,
  react: React,
  events: {
    onArcCopy: 'arc-copy' as EventName<CustomEvent>,
    onClick: 'click' as EventName<Event>,
  },
});
