// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcDatePicker } from '@arclux/arc-ui';

export interface DatePickerProps {
  value?: string;
  min?: string;
  max?: string;
  placeholder?: string;
  disabled?: boolean;
  label?: string;
  _open?: string;
  _viewMonth?: string;
  _viewYear?: string;
  _mode?: string;
  className?: string;
  children?: React.ReactNode;
  onArcChange?: (e: CustomEvent) => void;
}

export const DatePicker = createComponent({
  tagName: 'arc-date-picker',
  elementClass: ArcDatePicker,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
