// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcFieldList } from '@arclux/arc-ui/field-list';

export interface FieldListProps {
  label?: string;
  addLabel?: string;
  min?: number;
  max?: number;
  className?: string;
  children?: React.ReactNode;
  onArcAdd?: (e: CustomEvent) => void;
  onArcRemove?: (e: CustomEvent) => void;
  onArcMove?: (e: CustomEvent) => void;
}

export const FieldList = createComponent({
  tagName: 'arc-field-list',
  elementClass: ArcFieldList,
  react: React,
  events: {
    onArcAdd: 'arc-add' as EventName<CustomEvent>,
    onArcRemove: 'arc-remove' as EventName<CustomEvent>,
    onArcMove: 'arc-move' as EventName<CustomEvent>,
  },
});
