// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcFileUpload } from '@arclux/arc-ui/file-upload';

export interface FileUploadProps {
  accept?: string;
  multiple?: boolean;
  maxSize?: number;
  disabled?: boolean;
  className?: string;
  onArcChange?: (e: CustomEvent) => void;
  onArcRemove?: (e: CustomEvent) => void;
}

export const FileUpload = createComponent({
  tagName: 'arc-file-upload',
  elementClass: ArcFileUpload,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
    onArcRemove: 'arc-remove' as EventName<CustomEvent>,
  },
});
