// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcLabel } from '@arclux/arc-ui/label';

export interface LabelProps {
  for?: string;
  required?: boolean;
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const Label = createComponent({
  tagName: 'arc-label',
  elementClass: ArcLabel,
  react: React,
});
