// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcPasswordInput } from '@arclux/arc-ui/password-input';

export interface PasswordInputProps {
  required?: boolean;
  readonly?: boolean;
  name?: string;
  label?: string;
  placeholder?: string;
  value?: string;
  disabled?: boolean;
  error?: string;
  size?: 'sm' | 'md' | 'lg';
  autocomplete?: string;
  showStrength?: boolean;
  className?: string;
  onArcStrengthChange?: (e: CustomEvent) => void;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  onClick?: (e: Event) => void;
}

export const PasswordInput = createComponent({
  tagName: 'arc-password-input',
  elementClass: ArcPasswordInput,
  react: React,
  events: {
    onArcStrengthChange: 'arc-strength-change' as EventName<CustomEvent>,
    onArcInput: 'arc-input' as EventName<CustomEvent>,
    onArcChange: 'arc-change' as EventName<CustomEvent>,
    onClick: 'click' as EventName<Event>,
  },
});
