// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcSearch } from '@arclux/arc-ui/search';

export interface SearchProps {
  value?: string;
  placeholder?: string;
  label?: string;
  disabled?: boolean;
  loading?: boolean;
  className?: string;
  children?: React.ReactNode;
  onArcInput?: (e: CustomEvent) => void;
  onArcClear?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  onArcSelect?: (e: CustomEvent) => void;
}

export const Search = createComponent({
  tagName: 'arc-search',
  elementClass: ArcSearch,
  react: React,
  events: {
    onArcInput: 'arc-input' as EventName<CustomEvent>,
    onArcClear: 'arc-clear' as EventName<CustomEvent>,
    onArcChange: 'arc-change' as EventName<CustomEvent>,
    onArcSelect: 'arc-select' as EventName<CustomEvent>,
  },
});
