// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcSelect } from '@arclux/arc-ui/select';

export interface SelectProps {
  value?: string;
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  size?: 'sm' | 'lg';
  error?: string;
  open?: boolean;
  className?: string;
  children?: React.ReactNode;
  onArcChange?: (e: CustomEvent) => void;
  onClick?: (e: Event) => void;
}

export const Select = createComponent({
  tagName: 'arc-select',
  elementClass: ArcSelect,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
    onClick: 'click' as EventName<Event>,
  },
});
