// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcSortableList } from '@arclux/arc-ui';

export interface SortableListProps {
  disabled?: boolean;
  _items?: string;
  _dragIndex?: string;
  _overIndex?: string;
  _kbSelected?: string;
  _kbMoving?: string;
  className?: string;
  children?: React.ReactNode;
  onArcChange?: (e: CustomEvent) => void;
}

export const SortableList = createComponent({
  tagName: 'arc-sortable-list',
  elementClass: ArcSortableList,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
