// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcTextarea } from '@arclux/arc-ui';

export interface TextareaProps {
  value?: string;
  placeholder?: string;
  label?: string;
  rows?: number;
  maxlength?: number;
  disabled?: boolean;
  readonly?: boolean;
  resize?: 'none' | 'vertical' | 'horizontal' | 'both';
  error?: string;
  className?: string;
  children?: React.ReactNode;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
}

export const Textarea = createComponent({
  tagName: 'arc-textarea',
  elementClass: ArcTextarea,
  react: React,
  events: {
    onArcInput: 'arc-input' as EventName<CustomEvent>,
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
