// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcToggle } from '@arclux/arc-ui/toggle';

export interface ToggleProps {
  required?: boolean;
  readonly?: boolean;
  checked?: boolean;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  label?: string;
  name?: string;
  className?: string;
  onArcChange?: (e: CustomEvent) => void;
}

export const Toggle = createComponent({
  tagName: 'arc-toggle',
  elementClass: ArcToggle,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
