<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    sidebarOpen?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { sidebarOpen = false, children, ...rest }: Props = $props();
</script>

<arc-app-shell {sidebarOpen} {...rest}>
  {@render children?.()}
</arc-app-shell>
