<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    _items?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { _items = [], children, ...rest }: Props = $props();
</script>

<arc-breadcrumb {_items} {...rest}>
  {@render children?.()}
</arc-breadcrumb>
