// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcComparisonColumn } from '@arclux/arc-ui/comparison-column';

export interface ComparisonColumnProps {
  heading?: string;
  highlight?: boolean;
  values?: string[];
  className?: string;
}

export const ComparisonColumn = createComponent({
  tagName: 'arc-comparison-column',
  elementClass: ArcComparisonColumn,
  react: React,
});
