// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcComparison } from '@arclux/arc-ui';

export interface ComparisonProps {
  features?: string;
  _columns?: string;
  className?: string;
  children?: React.ReactNode;
}

export const Comparison = createComponent({
  tagName: 'arc-comparison',
  elementClass: ArcComparison,
  react: React,
});
