// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcDataTable } from '@arclux/arc-ui/data-table';

export interface DataTableProps {
  rows?: unknown[];
  sortable?: boolean;
  selectable?: boolean;
  sortColumn?: string;
  sortDirection?: string;
  virtual?: boolean;
  rowHeight?: number;
  className?: string;
  children?: React.ReactNode;
  onArcSort?: (e: CustomEvent) => void;
  onArcSelectAll?: (e: CustomEvent) => void;
  onArcRowSelect?: (e: CustomEvent) => void;
}

export const DataTable = createComponent({
  tagName: 'arc-data-table',
  elementClass: ArcDataTable,
  react: React,
  events: {
    onArcSort: 'arc-sort' as EventName<CustomEvent>,
    onArcSelectAll: 'arc-select-all' as EventName<CustomEvent>,
    onArcRowSelect: 'arc-row-select' as EventName<CustomEvent>,
  },
});
