// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcDescriptionList } from '@arclux/arc-ui/description-list';

export interface DescriptionListProps {
  columns?: number;
  dividers?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const DescriptionList = createComponent({
  tagName: 'arc-description-list',
  elementClass: ArcDescriptionList,
  react: React,
});
