// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcDiff } from '@arclux/arc-ui';

export interface DiffProps {
  before?: string;
  after?: string;
  mode?: 'side-by-side';
  className?: string;
  children?: React.ReactNode;
}

export const Diff = createComponent({
  tagName: 'arc-diff',
  elementClass: ArcDiff,
  react: React,
});
