// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcListItem } from '@arclux/arc-ui';

export interface ListItemProps {
  value?: string;
  selected?: boolean;
  disabled?: boolean;
  href?: string;
  _hasPrefix?: string;
  _hasSuffix?: string;
  _hasDescription?: string;
  className?: string;
  children?: React.ReactNode;
  onArcItemSelect?: (e: CustomEvent) => void;
}

export const ListItem = createComponent({
  tagName: 'arc-list-item',
  elementClass: ArcListItem,
  react: React,
  events: {
    onArcItemSelect: 'arc-item-select' as EventName<CustomEvent>,
  },
});
