// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcMeter } from '@arclux/arc-ui';

export interface MeterProps {
  value?: number;
  min?: number;
  max?: number;
  low?: number;
  high?: number;
  optimum?: number;
  label?: string;
  className?: string;
  children?: React.ReactNode;
}

export const Meter = createComponent({
  tagName: 'arc-meter',
  elementClass: ArcMeter,
  react: React,
});
