// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcStepper } from '@arclux/arc-ui/stepper';

export interface StepperProps {
  active?: number;
  className?: string;
  children?: React.ReactNode;
}

export const Stepper = createComponent({
  tagName: 'arc-stepper',
  elementClass: ArcStepper,
  react: React,
});
