// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcTable } from '@arclux/arc-ui/table';

export interface TableProps {
  columns?: unknown[];
  rows?: unknown[];
  striped?: boolean;
  compact?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const Table = createComponent({
  tagName: 'arc-table',
  elementClass: ArcTable,
  react: React,
});
