// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcValueCard } from '@arclux/arc-ui/value-card';

export interface ValueCardProps {
  icon?: string;
  heading?: string;
  description?: string;
  className?: string;
  children?: React.ReactNode;
}

export const ValueCard = createComponent({
  tagName: 'arc-value-card',
  elementClass: ArcValueCard,
  react: React,
});
