// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcWaveform } from '@arclux/arc-ui/waveform';

export interface WaveformProps {
  peaks?: string;
  position?: number;
  duration?: number;
  interactive?: boolean;
  variant?: 'bars' | 'mirror';
  label?: string;
  className?: string;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
}

export const Waveform = createComponent({
  tagName: 'arc-waveform',
  elementClass: ArcWaveform,
  react: React,
  events: {
    onArcInput: 'arc-input' as EventName<CustomEvent>,
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
