import '@arclux/arc-ui/loading-overlay';
import type { Snippet } from 'svelte';
interface Props {
    active?: boolean;
    message?: string;
    global?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const LoadingOverlay: import("svelte").Component<Props, {}, "">;
type LoadingOverlay = ReturnType<typeof LoadingOverlay>;
export default LoadingOverlay;
