import '@arclux/arc-ui/snackbar';
interface Props {
    position?: 'bottom-center' | 'bottom-left' | 'bottom-right';
    duration?: number;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Snackbar: import("svelte").Component<Props, {}, "">;
type Snackbar = ReturnType<typeof Snackbar>;
export default Snackbar;
