// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/breadcrumb';

@Component({
  selector: 'arc-breadcrumb',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-breadcrumb [attr.separator]="separator" (arc-navigate)="arcNavigate.emit($event)"><ng-content /></arc-breadcrumb>`,
})
export class Breadcrumb {
  @Input() separator: string = '/';
  @Output() arcNavigate = new EventEmitter<CustomEvent>();
}
