// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/breadcrumb-menu';

@Component({
  selector: 'arc-breadcrumb-menu',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-breadcrumb-menu [attr.items]="items" (arc-navigate)="arcNavigate.emit($event)"><ng-content /></arc-breadcrumb-menu>`,
})
export class BreadcrumbMenu {
  @Input() items: string = [];
  @Output() arcNavigate = new EventEmitter<CustomEvent>();
}
