// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-page-indicator',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-page-indicator [attr.count]="count" [attr.value]="value" [clickable]="clickable" (arc-change)="arcChange.emit($event)"><ng-content /></arc-page-indicator>`,
})
export class PageIndicator {
  @Input() count: number = 0;
  @Input() value: number = 0;
  @Input() clickable: boolean = false;
  @Output() arcChange = new EventEmitter<CustomEvent>();
}
