// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/pagination';

@Component({
  selector: 'arc-pagination',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-pagination [attr.total]="this.total" [attr.current]="this.current" [attr.siblings]="this.siblings" [compact]="this.compact" (arc-change)="this.arcChange.emit($event)"></arc-pagination>`,
})
export class Pagination {
  @Input() total: number = 1;
  @Input() current: number = 1;
  @Input() siblings: number = 1;
  @Input() compact: boolean = false;
  @Output() arcChange = new EventEmitter<CustomEvent>();
}
