// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/scroll-spy';
import type { ArcScrollSpy } from '@arclux/arc-ui/scroll-spy';

@Component({
  selector: 'arc-scroll-spy',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '(arc-change)': '_onArcChange($event)',
  },
})
export class ScrollSpy {
  private readonly _el: ArcScrollSpy = inject(ElementRef).nativeElement;

  @Input() set active(value: string) {
    this._el.active = value;
  }
  get active(): string {
    return this._el.active;
  }

  @Input() set offset(value: number) {
    this._el.offset = value;
  }
  get offset(): number {
    return this._el.offset;
  }

  @Input() set progress(value: 'none' | 'ring' | 'read' | 'both') {
    this._el.progress = value;
  }
  get progress(): 'none' | 'ring' | 'read' | 'both' {
    return this._el.progress;
  }

  @Output() activeChange = new EventEmitter<string>();

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.activeChange.emit(detail.value as string);
    }
  }
}
