// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/sidebar-link';
import type { ArcSidebarLink } from '@arclux/arc-ui/sidebar-link';

@Component({
  selector: 'arc-sidebar-link',
  standalone: true,
  template: `<ng-content />`,
})
export class SidebarLink {
  private readonly _el: ArcSidebarLink = inject(ElementRef).nativeElement;

  @Input() set href(value: string) {
    this._el.href = value;
  }
  get href(): string {
    return this._el.href;
  }

  @Input() set active(value: boolean) {
    this._el.active = value;
  }
  get active(): boolean {
    return this._el.active;
  }

  @Input() set level(value: number) {
    this._el.level = value;
  }
  get level(): number {
    return this._el.level;
  }

  @Input() set icon(value: string) {
    this._el.icon = value;
  }
  get icon(): string {
    return this._el.icon;
  }

  @Input() set external(value: boolean) {
    this._el.external = value;
  }
  get external(): boolean {
    return this._el.external;
  }
}
