// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/sidebar-link';

@Component({
  selector: 'arc-sidebar-link',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-sidebar-link [attr.href]="href" [active]="active" [attr.level]="level"><ng-content /></arc-sidebar-link>`,
})
export class SidebarLink {
  @Input() href: string = '';
  @Input() active: boolean = false;
  @Input() level: number = 0;
}
