// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcSkipLink } from '@arclux/arc-ui/skip-link';

@Component({
  selector: 'arc-skip-link',
  standalone: true,
  template: `<ng-content />`,
})
export class SkipLink {
  private readonly _el: ArcSkipLink = inject(ElementRef).nativeElement;

  @Input() set target(value: string) {
    this._el.target = value;
  }
  get target(): string {
    return this._el.target;
  }
}
