// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/spy-link';
import type { ArcSpyLink } from '@arclux/arc-ui/spy-link';

@Component({
  selector: 'arc-spy-link',
  standalone: true,
  template: `<ng-content />`,
})
export class SpyLink {
  private readonly _el: ArcSpyLink = inject(ElementRef).nativeElement;

  @Input() set target(value: string) {
    this._el.target = value;
  }
  get target(): string {
    return this._el.target;
  }

  @Input() set level(value: number) {
    this._el.level = value;
  }
  get level(): number {
    return this._el.level;
  }
}
