// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-stepper-nav',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-stepper-nav [attr.steps]="steps" [attr.active]="active" [linear]="linear" (arc-change)="arcChange.emit($event)" (arc-complete)="arcComplete.emit($event)"><ng-content /></arc-stepper-nav>`,
})
export class StepperNav {
  @Input() steps: string = [];
  @Input() active: number = 0;
  @Input() linear: boolean = false;
  @Output() arcChange = new EventEmitter<CustomEvent>();
  @Output() arcComplete = new EventEmitter<CustomEvent>();
}
