// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/top-bar';
import type { ArcTopBar } from '@arclux/arc-ui/top-bar';

@Component({
  selector: 'arc-top-bar',
  standalone: true,
  template: `<ng-content />`,
})
export class TopBar {
  private readonly _el: ArcTopBar = inject(ElementRef).nativeElement;

  @Input() set heading(value: string) {
    this._el.heading = value;
  }
  get heading(): string {
    return this._el.heading;
  }

  @Input() set homeHref(value: string) {
    this._el.homeHref = value;
  }
  get homeHref(): string {
    return this._el.homeHref;
  }

  @Input() set scrolled(value: boolean) {
    this._el.scrolled = value;
  }
  get scrolled(): boolean {
    return this._el.scrolled;
  }

  @Input() set immersive(value: boolean) {
    this._el.immersive = value;
  }
  get immersive(): boolean {
    return this._el.immersive;
  }

  @Input() set fixed(value: boolean) {
    this._el.fixed = value;
  }
  get fixed(): boolean {
    return this._el.fixed;
  }

  @Input() set contained(value: string) {
    this._el.contained = value;
  }
  get contained(): string {
    return this._el.contained;
  }

  @Input() set menuOpen(value: boolean) {
    this._el.menuOpen = value;
  }
  get menuOpen(): boolean {
    return this._el.menuOpen;
  }

  @Input() set mobileMenu(value: string) {
    this._el.mobileMenu = value;
  }
  get mobileMenu(): string {
    return this._el.mobileMenu;
  }

  @Input() set menuPosition(value: string) {
    this._el.menuPosition = value;
  }
  get menuPosition(): string {
    return this._el.menuPosition;
  }

  @Input() set navAlign(value: 'left' | 'center' | 'right') {
    this._el.navAlign = value;
  }
  get navAlign(): 'left' | 'center' | 'right' {
    return this._el.navAlign;
  }
}
