// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface ColorPickerProps {
  value?: string;
  presets?: unknown[];
  disabled?: boolean;
  label?: string;
  _hue?: string;
  _sat?: string;
  _lit?: string;
  _hexInput?: string;
  _draggingArea?: string;
  _draggingHue?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const ColorPicker: FunctionComponent<ColorPickerProps> = ({ value, presets, disabled, label, _hue, _sat, _lit, _hexInput, _draggingArea, _draggingHue, children, ...rest }) => (
  <arc-color-picker value={value} presets={presets} disabled={disabled} label={label} _hue={_hue} _sat={_sat} _lit={_lit} _hexInput={_hexInput} _draggingArea={_draggingArea} _draggingHue={_draggingHue} {...rest}>
    {children}
  </arc-color-picker>
);
