// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface SearchProps {
  value?: string;
  placeholder?: string;
  label?: string;
  disabled?: boolean;
  loading?: boolean;
  _open?: string;
  _activeIndex?: string;
  _suggestions?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Search: FunctionComponent<SearchProps> = ({ value, placeholder, label, disabled, loading, _open, _activeIndex, _suggestions, children, ...rest }) => (
  <arc-search value={value} placeholder={placeholder} label={label} disabled={disabled} loading={loading} _open={_open} _activeIndex={_activeIndex} _suggestions={_suggestions} {...rest}>
    {children}
  </arc-search>
);
