// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-carousel',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-carousel [autoPlay]="autoPlay" [attr.interval]="interval" [loop]="loop" [showDots]="showDots" [showArrows]="showArrows" [attr._current]="_current" [attr._total]="_total" (arc-change)="arcChange.emit($event)"><ng-content /></arc-carousel>`,
})
export class Carousel {
  @Input() autoPlay: boolean = false;
  @Input() interval: number = 5000;
  @Input() loop: boolean = true;
  @Input() showDots: boolean = true;
  @Input() showArrows: boolean = true;
  @Input() _current: string = 0;
  @Input() _total: string = 0;
  @Output() arcChange = new EventEmitter<CustomEvent>();
}
