// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-chip',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-chip [selected]="selected" [disabled]="disabled" [attr.value]="value" (arc-change)="arcChange.emit($event)"><ng-content /></arc-chip>`,
})
export class Chip {
  @Input() selected: boolean = false;
  @Input() disabled: boolean = false;
  @Input() value: string = '';
  @Output() arcChange = new EventEmitter<CustomEvent>();
}
