// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-pin-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-pin-input [attr.length]="length" [attr.value]="value" [disabled]="disabled" [mask]="mask" [attr.type]="type" [attr.separator]="separator" [attr.label]="label" (arc-change)="arcChange.emit($event)" (arc-complete)="arcComplete.emit($event)"><ng-content /></arc-pin-input>`,
})
export class PinInput {
  @Input() length: number = 4;
  @Input() value: string = '';
  @Input() disabled: boolean = false;
  @Input() mask: boolean = false;
  @Input() type: string = 'number';
  @Input() separator: number = 0;
  @Input() label: string = '';
  @Output() arcChange = new EventEmitter<CustomEvent>();
  @Output() arcComplete = new EventEmitter<CustomEvent>();
}
