<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/bar-list';

  interface Props {
    items?: unknown[];
    max?: number;
    limit?: number;
    unsorted?: boolean;
    unit?: string;
    label?: string;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { items, max, limit, unsorted, unit = '', label = '', ...rest }: Props = $props();
</script>

<arc-bar-list {items} {max} {limit} {unsorted} {unit} {label} {...rest}>
</arc-bar-list>
