<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/comparison';
  import type { Snippet } from 'svelte';

  interface Props {
    features?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { features = '[]', children, ...rest }: Props = $props();
</script>

<arc-comparison {features} {...rest}>
  {@render children?.()}
</arc-comparison>
