<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    features?: string;
    _columns?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { features = '[]', _columns = [], children, ...rest }: Props = $props();
</script>

<arc-comparison {features} {_columns} {...rest}>
  {@render children?.()}
</arc-comparison>
