<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/countdown-timer';
  import type { Snippet } from 'svelte';

  interface Props {
    target?: string;
    label?: string;
    expired?: string;
    hideZeroSegments?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { target = '', label = '', expired = 'Expired', hideZeroSegments = false, children, ...rest }: Props = $props();
</script>

<arc-countdown-timer {target} {label} {expired} {hideZeroSegments} {...rest}>
  {@render children?.()}
</arc-countdown-timer>
