<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/diff';
  import type { Snippet } from 'svelte';

  interface Props {
    before?: string;
    after?: string;
    mode?: 'side-by-side';
    children?: Snippet;
    [key: string]: unknown;
  }

  let { before = '', after = '', mode = 'inline', children, ...rest }: Props = $props();
</script>

<arc-diff {before} {after} {mode} {...rest}>
  {@render children?.()}
</arc-diff>
