<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/event-calendar';
  import type { Snippet } from 'svelte';

  interface Props {
    events?: unknown[];
    view?: 'week';
    date?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { events = [], view = 'month', date = '', children, ...rest }: Props = $props();
</script>

<arc-event-calendar {events} {view} {date} {...rest}>
  {@render children?.()}
</arc-event-calendar>
