<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/level-meter';

  interface Props {
    value?: number;
    min?: number;
    max?: number;
    peak?: number;
    orientation?: 'vertical' | 'horizontal';
    segments?: number;
    warn?: number;
    clip?: number;
    label?: string;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { value, min, max, peak, orientation, segments, warn, clip, label = '', ...rest }: Props = $props();
</script>

<arc-level-meter {value} {min} {max} {peak} {orientation} {segments} {warn} {clip} {label} {...rest}>
</arc-level-meter>
