<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: string;
    label?: string;
    trend?: 'up' | 'down' | 'neutral';
    change?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = '', label = '', trend = '', change = '', children, ...rest }: Props = $props();
</script>

<arc-stat {value} {label} {trend} {change} {...rest}>
  {@render children?.()}
</arc-stat>
