<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/value-card';
  import type { Snippet } from 'svelte';

  interface Props {
    icon?: string;
    heading?: string;
    description?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { icon = '', heading = '', description = '', children, ...rest }: Props = $props();
</script>

<arc-value-card {icon} {heading} {description} {...rest}>
  {@render children?.()}
</arc-value-card>
