<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/accordion';

defineOptions({ name: 'Accordion' });

const props = defineProps<{
  multiple?: boolean;
}>();
</script>

<template>
  <arc-accordion
    :multiple="props.multiple"
  >
    <slot />
  </arc-accordion>
</template>
