<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/accordion-item';

defineOptions({ name: 'AccordionItem' });

const props = withDefaults(defineProps<{
  question?: string;
}>(), {
  question: '',
});
</script>

<template>
  <arc-accordion-item
    :question="props.question"
  >
    <slot />
  </arc-accordion-item>
</template>
