<!-- Auto-generated by @arclux/prism 3.2.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/accordion';

defineOptions({ name: 'Accordion' });

const props = withDefaults(defineProps<{
  multiple?: boolean;
}>(), {
  multiple: false,
});
</script>

<template>
  <arc-accordion
    :multiple="props.multiple"
  >
    <slot />
  </arc-accordion>
</template>
