<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/aspect-ratio';

defineOptions({ name: 'AspectRatio' });

const props = withDefaults(defineProps<{
  ratio?: string;
}>(), {
  ratio: '16/9',
});
</script>

<template>
  <arc-aspect-ratio
    :ratio="props.ratio"
  >
    <slot />
  </arc-aspect-ratio>
</template>
