<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/avatar-group';

defineOptions({ name: 'AvatarGroup' });

const props = withDefaults(defineProps<{
  max?: number;
  overlap?: 'sm' | 'md' | 'lg';
}>(), {
  max: Infinity,
  overlap: 'md',
});
</script>

<template>
  <arc-avatar-group
    :max="props.max"
    :overlap="props.overlap"
  >
    <slot />
  </arc-avatar-group>
</template>
