<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/callout';

defineOptions({ name: 'Callout' });

const props = withDefaults(defineProps<{
  variant?: 'info' | 'warning' | 'tip' | 'danger';
  dismissible?: boolean;
}>(), {
  variant: 'info',
  dismissible: false,
});

const emit = defineEmits<{
  'arc-close': [event: CustomEvent];
}>();
</script>

<template>
  <arc-callout
    :variant="props.variant"
    :dismissible="props.dismissible"
    @arc-close="(payload: CustomEvent) => emit('arc-close', payload)"
  >
    <slot />
    <slot name="icon" />
  </arc-callout>
</template>
