<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/carousel';

defineOptions({ name: 'Carousel' });

const props = defineProps<{
  autoPlay?: boolean;
  interval?: number;
  loop?: boolean;
  showDots?: boolean;
  showArrows?: boolean;
}>();

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-carousel
    :autoPlay="props.autoPlay"
    :interval="props.interval"
    :loop="props.loop"
    :showDots="props.showDots"
    :showArrows="props.showArrows"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
    <slot />
  </arc-carousel>
</template>
