<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Carousel' });

withDefaults(defineProps<{
  autoPlay?: boolean;
  interval?: number;
  loop?: boolean;
  showDots?: boolean;
  showArrows?: boolean;
  _current?: string;
  _total?: string;
}>(), {
  autoPlay: false,
  interval: 5000,
  loop: true,
  showDots: true,
  showArrows: true,
  _current: 0,
  _total: 0,
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-carousel
    :autoPlay="autoPlay"
    :interval="interval"
    :loop="loop"
    :showDots="showDots"
    :showArrows="showArrows"
    :_current="_current"
    :_total="_total"
  >
    <slot />
  </arc-carousel>
</template>
