<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'CodeBlock' });

withDefaults(defineProps<{
  language?: string;
  filename?: string;
  code?: string;
  _copied?: string;
}>(), {
  language: '',
  filename: '',
  code: '',
  _copied: false,
});
</script>

<template>
  <arc-code-block
    :language="language"
    :filename="filename"
    :code="code"
    :_copied="_copied"
  >
    <slot />
  </arc-code-block>
</template>
