<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/color-swatch';

defineOptions({ name: 'ColorSwatch' });

const props = withDefaults(defineProps<{
  color?: string;
  label?: string;
  size?: 'sm' | 'md' | 'lg';
}>(), {
  color: '#4d7ef7',
  label: '',
  size: 'md',
});
</script>

<template>
  <arc-color-swatch
    :color="props.color"
    :label="props.label"
    :size="props.size"
  >
    <slot />
  </arc-color-swatch>
</template>
