<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'DataTable' });

withDefaults(defineProps<{
  rows?: unknown[];
  sortable?: boolean;
  selectable?: boolean;
  sortColumn?: string;
  sortDirection?: string;
  virtual?: boolean;
  rowHeight?: number;
  _columns?: string;
  _selectedRows?: string;
  _startIndex?: string;
  _visibleCount?: string;
}>(), {
  rows: () => ([]),
  sortable: false,
  selectable: false,
  sortColumn: '',
  sortDirection: 'asc',
  virtual: false,
  rowHeight: 40,
  _columns: () => ([]),
  _selectedRows: 'new Set()',
  _startIndex: 0,
  _visibleCount: 0,
});

defineEmits<{
  'arc-sort': [event: CustomEvent];
  'arc-select-all': [event: CustomEvent];
  'arc-row-select': [event: CustomEvent];
}>();
</script>

<template>
  <arc-data-table
    :rows="rows"
    :sortable="sortable"
    :selectable="selectable"
    :sortColumn="sortColumn"
    :sortDirection="sortDirection"
    :virtual="virtual"
    :rowHeight="rowHeight"
    :_columns="_columns"
    :_selectedRows="_selectedRows"
    :_startIndex="_startIndex"
    :_visibleCount="_visibleCount"
  >
    <slot />
  </arc-data-table>
</template>
