<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Divider' });

withDefaults(defineProps<{
  variant?: 'subtle' | 'glow' | 'line-white' | 'line-primary' | 'line-gradient';
  align?: 'left' | 'right';
  vertical?: boolean;
}>(), {
  variant: 'subtle',
  vertical: false,
});
</script>

<template>
  <arc-divider
    :variant="variant"
    :align="align"
    :vertical="vertical"
  >
    <slot />
  </arc-divider>
</template>
