<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/image-hotspots';

defineOptions({ name: 'ImageHotspots' });

</script>

<template>
  <arc-image-hotspots>
    <slot />
  </arc-image-hotspots>
</template>
