<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'List' });

withDefaults(defineProps<{
  variant?: 'bordered' | 'separated';
  size?: 'sm' | 'lg';
  selectable?: boolean;
  multiple?: boolean;
  value?: string;
  _items?: string;
}>(), {
  variant: 'default',
  size: 'md',
  selectable: false,
  multiple: false,
  value: '',
  _items: () => ([]),
});

defineEmits<{
  'arc-change': [event: CustomEvent];
  'arc-item-click': [event: CustomEvent];
}>();
</script>

<template>
  <arc-list
    :variant="variant"
    :size="size"
    :selectable="selectable"
    :multiple="multiple"
    :value="value"
    :_items="_items"
  >
    <slot />
  </arc-list>
</template>
