<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Meter' });

withDefaults(defineProps<{
  value?: number;
  min?: number;
  max?: number;
  low?: number;
  high?: number;
  optimum?: number;
  label?: string;
}>(), {
  value: 0,
  min: 0,
  max: 100,
  low: 'undefined',
  high: 'undefined',
  optimum: 'undefined',
  label: '',
});
</script>

<template>
  <arc-meter
    :value="value"
    :min="min"
    :max="max"
    :low="low"
    :high="high"
    :optimum="optimum"
    :label="label"
  >
    <slot />
  </arc-meter>
</template>
