<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/scroll-indicator';

defineOptions({ name: 'ScrollIndicator' });

const props = withDefaults(defineProps<{
  target?: string;
  position?: 'top' | 'bottom';
  size?: 'sm' | 'md' | 'lg';
  color?: 'accent' | 'gradient';
}>(), {
  target: '',
});
</script>

<template>
  <arc-scroll-indicator
    :target="props.target"
    :position="props.position"
    :size="props.size"
    :color="props.color"
  >
  </arc-scroll-indicator>
</template>
