<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/spinner';

defineOptions({ name: 'Spinner' });

const props = defineProps<{
  size?: 'sm' | 'md' | 'lg';
  variant?: 'primary' | 'secondary' | 'white';
}>();
</script>

<template>
  <arc-spinner
    :size="props.size"
    :variant="props.variant"
  >
  </arc-spinner>
</template>
