<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/spinner';

defineOptions({ name: 'Spinner' });

const props = withDefaults(defineProps<{
  size?: 'sm' | 'md' | 'lg';
  variant?: 'primary' | 'secondary' | 'white';
}>(), {
  size: 'md',
  variant: 'primary',
});
</script>

<template>
  <arc-spinner
    :size="props.size"
    :variant="props.variant"
  >
    <slot />
  </arc-spinner>
</template>
