<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Text' });

withDefaults(defineProps<{
  variant?: 'accent' | 'code';
  as?: string;
}>(), {
  variant: 'body',
  as: 'p',
});
</script>

<template>
  <arc-text
    :variant="variant"
    :as="as"
  >
    <slot />
  </arc-text>
</template>
