<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/virtual-list';

defineOptions({ name: 'VirtualList' });

withDefaults(defineProps<{
  items?: unknown[];
  itemHeight?: number;
  overscan?: number;
}>(), {
  items: () => ([]),
  itemHeight: 40,
  overscan: 5,
});
</script>

<template>
  <arc-virtual-list
    :items="items"
    :itemHeight="itemHeight"
    :overscan="overscan"
  >
    <slot />
  </arc-virtual-list>
</template>
