// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface ColorPickerProps {
  value?: string;
  presets?: unknown[];
  disabled?: boolean;
  label?: string;
  _hue?: string;
  _sat?: string;
  _lit?: string;
  _hexInput?: string;
  _draggingArea?: string;
  _draggingHue?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const ColorPicker: Component<ColorPickerProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'presets', 'disabled', 'label', '_hue', '_sat', '_lit', '_hexInput', '_draggingArea', '_draggingHue', 'children']);
  return (
    <arc-color-picker value={local.value} presets={local.presets} disabled={local.disabled} label={local.label} _hue={local._hue} _sat={local._sat} _lit={local._lit} _hexInput={local._hexInput} _draggingArea={local._draggingArea} _draggingHue={local._draggingHue} {...rest}>
      {local.children}
    </arc-color-picker>
  );
};
