// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface IconButtonProps {
  name?: string;
  text?: string;
  variant?: 'ghost' | 'secondary' | 'primary';
  size?: 'xs' | 'sm' | 'md' | 'lg';
  label?: string;
  href?: string;
  disabled?: boolean;
  type?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const IconButton: Component<IconButtonProps> = (props) => {
  const [local, rest] = splitProps(props, ['name', 'text', 'variant', 'size', 'label', 'href', 'disabled', 'type', 'children']);
  return (
    <arc-icon-button name={local.name} text={local.text} variant={local.variant} size={local.size} label={local.label} href={local.href} disabled={local.disabled} type={local.type} {...rest}>
      {local.children}
    </arc-icon-button>
  );
};
