// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface InfiniteScrollProps {
  threshold?: number;
  loading?: boolean;
  finished?: boolean;
  disabled?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const InfiniteScroll: Component<InfiniteScrollProps> = (props) => {
  const [local, rest] = splitProps(props, ['threshold', 'loading', 'finished', 'disabled', 'children']);
  return (
    <arc-infinite-scroll threshold={local.threshold} loading={local.loading} finished={local.finished} disabled={local.disabled} {...rest}>
      {local.children}
    </arc-infinite-scroll>
  );
};
