// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface SegmentedControlProps {
  value?: string;
  disabled?: boolean;
  _options?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const SegmentedControl: Component<SegmentedControlProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'disabled', '_options', 'children']);
  return (
    <arc-segmented-control value={local.value} disabled={local.disabled} _options={local._options} {...rest}>
      {local.children}
    </arc-segmented-control>
  );
};
