// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface BlockquoteProps {
  cite?: string;
  variant?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Blockquote: Component<BlockquoteProps> = (props) => {
  const [local, rest] = splitProps(props, ['cite', 'variant', 'children']);
  return (
    <arc-blockquote cite={local.cite} variant={local.variant} {...rest}>
      {local.children}
    </arc-blockquote>
  );
};
