// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component } from 'solid-js';
import '@arclux/arc-ui/highlight';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-highlight': Record<string, unknown>;
    }
  }
}

export interface HighlightProps {
  text?: string;
  query?: string;
  caseSensitive?: boolean;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Highlight: Component<HighlightProps> = (props) => {
  const [local, rest] = splitProps(props, ['text', 'query', 'caseSensitive']);
  return (
    <arc-highlight text={local.text} query={local.query} prop:caseSensitive={local.caseSensitive} {...rest}>
    </arc-highlight>
  );
};
