// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/keyboard-map';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-keyboard-map': Record<string, unknown>;
    }
  }
}

export interface KeyboardMapProps {
  layout?: 'compact' | 'ansi';
  highlight?: string|string[];
  labels?: boolean;
  platform?: 'auto' | 'mac' | 'win';
  caption?: string;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const KeyboardMap: Component<KeyboardMapProps> = (props) => {
  const [local, rest] = splitProps(props, ['layout', 'highlight', 'labels', 'platform', 'caption']);
  return (
    <arc-keyboard-map layout={local.layout} highlight={local.highlight} labels={local.labels} platform={local.platform} caption={local.caption} {...rest}>
    </arc-keyboard-map>
  );
};
