// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/number-format';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-number-format': Record<string, unknown>;
    }
  }
}

export interface NumberFormatProps {
  value?: number;
  type?: 'number' | 'currency' | 'percent' | 'compact';
  locale?: string;
  currency?: string;
  decimals?: number;
  notation?: 'standard' | 'compact';
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const NumberFormat: Component<NumberFormatProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'type', 'locale', 'currency', 'decimals', 'notation']);
  return (
    <arc-number-format value={local.value} type={local.type} locale={local.locale} currency={local.currency} decimals={local.decimals} notation={local.notation} {...rest}>
    </arc-number-format>
  );
};
