// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/text';

export interface TextProps {
  variant?: 'accent' | 'code';
  as?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Text: Component<TextProps> = (props) => {
  const [local, rest] = splitProps(props, ['variant', 'as', 'children']);
  return (
    <arc-text variant={local.variant} as={local.as} {...rest}>
      {local.children}
    </arc-text>
  );
};
