// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/typewriter';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-typewriter': Record<string, unknown>;
    }
  }
}

export interface TypewriterProps {
  text?: string;
  speed?: number;
  delay?: number;
  cursor?: boolean;
  loop?: boolean;
  nowrap?: boolean;
  pauseEnd?: number;
  onArcComplete?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Typewriter: Component<TypewriterProps> = (props) => {
  const [local, rest] = splitProps(props, ['text', 'speed', 'delay', 'cursor', 'loop', 'nowrap', 'pauseEnd', 'onArcComplete', 'children']);
  return (
    <arc-typewriter text={local.text} speed={local.speed} delay={local.delay} cursor={local.cursor} loop={local.loop} nowrap={local.nowrap} prop:pauseEnd={local.pauseEnd} on:arc-complete={local.onArcComplete} {...rest}>
      {local.children}
    </arc-typewriter>
  );
};
