// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcChart } from '@arclux/arc-ui/chart';

@Component({
  selector: 'arc-chart',
  standalone: true,
  template: `<ng-content />`,
})
export class Chart {
  private readonly _el: ArcChart = inject(ElementRef).nativeElement;

  @Input() set type(value: 'line' | 'area' | 'bar' | 'donut') {
    this._el.type = value;
  }
  get type(): 'line' | 'area' | 'bar' | 'donut' {
    return this._el.type;
  }

  @Input() set series(value: Array<{label:string,data:number[]}>) {
    this._el.series = value;
  }
  get series(): Array<{label:string,data:number[]}> {
    return this._el.series;
  }

  @Input() set labels(value: string[]) {
    this._el.labels = value;
  }
  get labels(): string[] {
    return this._el.labels;
  }

  @Input() set stacked(value: boolean) {
    this._el.stacked = value;
  }
  get stacked(): boolean {
    return this._el.stacked;
  }

  @Input() set hideLegend(value: boolean) {
    this._el.hideLegend = value;
  }
  get hideLegend(): boolean {
    return this._el.hideLegend;
  }

  @Input() set hideAxis(value: boolean) {
    this._el.hideAxis = value;
  }
  get hideAxis(): boolean {
    return this._el.hideAxis;
  }

  @Input() set height(value: number) {
    this._el.height = value;
  }
  get height(): number {
    return this._el.height;
  }

  @Input() set valueFormat(value: 'number' | 'percent' | 'currency') {
    this._el.valueFormat = value;
  }
  get valueFormat(): 'number' | 'percent' | 'currency' {
    return this._el.valueFormat;
  }

  @Input() set currency(value: string) {
    this._el.currency = value;
  }
  get currency(): string {
    return this._el.currency;
  }
}
