// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/countdown-timer';

@Component({
  selector: 'arc-countdown-timer',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-countdown-timer [attr.target]="target" [attr.label]="label" [attr.expired]="expired" [hideZeroSegments]="hideZeroSegments" (arc-expired)="arcExpired.emit($event)"><ng-content /></arc-countdown-timer>`,
})
export class CountdownTimer {
  @Input() target: string = '';
  @Input() label: string = '';
  @Input() expired: string = 'Expired';
  @Input() hideZeroSegments: boolean = false;
  @Output() arcExpired = new EventEmitter<CustomEvent>();
}
