// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/data-grid';

@Component({
  selector: 'arc-data-grid',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-data-grid [columns]="this.columns" [rows]="this.rows" [sort]="this.sort" [manualSort]="this.manualSort" [selectable]="this.selectable" [virtual]="this.virtual" [attr.rowHeight]="this.rowHeight" (arc-sort)="this.onArcSort($event)" (arc-selection-change)="this.arcSelectionChange.emit($event)" (arc-cell-change)="this.arcCellChange.emit($event)"><ng-content /></arc-data-grid>`,
})
export class DataGrid {
  @Input() columns: unknown[] = [];
  @Input() rows: unknown[] = [];
  @Input() sort: unknown[] = [];
  @Input() manualSort: boolean = false;
  @Input() selectable: boolean = false;
  @Input() virtual: boolean = false;
  @Input() rowHeight: number = 40;
  @Output() arcSort = new EventEmitter<CustomEvent>();
  @Output() arcSelectionChange = new EventEmitter<CustomEvent>();
  @Output() arcCellChange = new EventEmitter<CustomEvent>();
  @Output() sortChange = new EventEmitter<unknown[]>();

  onArcSort(event: CustomEvent) {
    this.arcSort.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('sort' in detail) {
      const next = detail.sort as unknown[];
      this.sort = next;
      this.sortChange.emit(next);
    }
  }
}
