// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/description-list';
import type { ArcDescriptionList } from '@arclux/arc-ui/description-list';

@Component({
  selector: 'arc-description-list',
  standalone: true,
  template: `<ng-content />`,
})
export class DescriptionList {
  private readonly _el: ArcDescriptionList = inject(ElementRef).nativeElement;

  @Input() set columns(value: number) {
    this._el.columns = value;
  }
  get columns(): number {
    return this._el.columns;
  }

  @Input() set layout(value: 'stacked' | 'horizontal') {
    this._el.layout = value;
  }
  get layout(): 'stacked' | 'horizontal' {
    return this._el.layout;
  }

  @Input() set dividers(value: boolean) {
    this._el.dividers = value;
  }
  get dividers(): boolean {
    return this._el.dividers;
  }
}
