// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/sparkline';

@Component({
  selector: 'arc-sparkline',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-sparkline [attr.data]="this.data" [attr.type]="this.type" [attr.color]="this.color" [attr.width]="this.width" [attr.height]="this.height" [fill]="this.fill"></arc-sparkline>`,
})
export class Sparkline {
  @Input() data: string = '';
  @Input() type: 'line' | 'bar' = 'line';
  @Input() color: string = '';
  @Input() width: number = 120;
  @Input() height: number = 32;
  @Input() fill: boolean = false;
}
