// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/stat';
import type { ArcStat } from '@arclux/arc-ui/stat';

@Component({
  selector: 'arc-stat',
  standalone: true,
  template: ``,
})
export class Stat {
  private readonly _el: ArcStat = inject(ElementRef).nativeElement;

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set trend(value: '' | 'up' | 'down' | 'neutral') {
    this._el.trend = value;
  }
  get trend(): '' | 'up' | 'down' | 'neutral' {
    return this._el.trend;
  }

  @Input() set change(value: string) {
    this._el.change = value;
  }
  get change(): string {
    return this._el.change;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set plain(value: boolean) {
    this._el.plain = value;
  }
  get plain(): boolean {
    return this._el.plain;
  }
}
