// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/tag';
import type { ArcTag } from '@arclux/arc-ui/tag';

@Component({
  selector: 'arc-tag',
  standalone: true,
  template: `<ng-content />`,
})
export class Tag {
  private readonly _el: ArcTag = inject(ElementRef).nativeElement;

  @Input() set variant(value: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info') {
    this._el.variant = value;
  }
  get variant(): 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' {
    return this._el.variant;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set removable(value: boolean) {
    this._el.removable = value;
  }
  get removable(): boolean {
    return this._el.removable;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Input() set color(value: string) {
    this._el.color = value;
  }
  get color(): string {
    return this._el.color;
  }
}
