// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/timeline';
import type { ArcTimeline } from '@arclux/arc-ui/timeline';

@Component({
  selector: 'arc-timeline',
  standalone: true,
  template: `<ng-content />`,
})
export class Timeline {
  private readonly _el: ArcTimeline = inject(ElementRef).nativeElement;

  @Input() set headingLevel(value: number) {
    this._el.headingLevel = value;
  }
  get headingLevel(): number {
    return this._el.headingLevel;
  }
}
