// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface AppShellProps {
  sidebarOpen?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const AppShell: FunctionComponent<AppShellProps> = ({ sidebarOpen, children, ...rest }) => (
  <arc-app-shell sidebarOpen={sidebarOpen} {...rest}>
    {children}
  </arc-app-shell>
);
