import '@arclux/arc-ui/gradient-text';
import type { Snippet } from 'svelte';
interface Props {
    variant?: 'accent' | 'display' | 'sunset' | 'ocean' | 'custom';
    gradient?: string;
    animated?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const GradientText: import("svelte").Component<Props, {}, "">;
type GradientText = ReturnType<typeof GradientText>;
export default GradientText;
