import '@arclux/arc-ui/keyboard-map';
interface Props {
    layout?: string;
    highlight?: string | string[];
    labels?: string;
    platform?: string;
    caption?: string;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const KeyboardMap: import("svelte").Component<Props, {}, "">;
type KeyboardMap = ReturnType<typeof KeyboardMap>;
export default KeyboardMap;
