import '@arclux/arc-ui/number-format';
import type { Snippet } from 'svelte';
interface Props {
    value?: number;
    type?: 'number' | 'currency' | 'percent' | 'compact';
    locale?: string;
    currency?: string;
    decimals?: number;
    notation?: 'standard' | 'compact';
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const NumberFormat: import("svelte").Component<Props, {}, "">;
type NumberFormat = ReturnType<typeof NumberFormat>;
export default NumberFormat;
