import '@arclux/arc-ui/terminal';
interface Props {
    lines?: string;
    prompt?: string;
    title?: string;
    speed?: number;
    autoplay?: boolean;
    loop?: boolean;
    class?: string;
    id?: string;
    style?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Terminal: import("svelte").Component<Props, {}, "">;
type Terminal = ReturnType<typeof Terminal>;
export default Terminal;
