import '@arclux/arc-ui/typewriter';
import type { Snippet } from 'svelte';
interface Props {
    text?: string;
    speed?: number;
    delay?: number;
    cursor?: boolean;
    loop?: boolean;
    nowrap?: boolean;
    pauseEnd?: number;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Typewriter: import("svelte").Component<Props, {}, "">;
type Typewriter = ReturnType<typeof Typewriter>;
export default Typewriter;
