// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/app-shell';

export interface AppShellProps {
  sidebarOpen?: boolean;
  breakpoint?: number;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const AppShell: Component<AppShellProps> = (props) => {
  const [local, rest] = splitProps(props, ['sidebarOpen', 'breakpoint', 'children']);
  return (
    <arc-app-shell sidebarOpen={local.sidebarOpen} breakpoint={local.breakpoint} {...rest}>
      {local.children}
    </arc-app-shell>
  );
};
