// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/auth-shell';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-auth-shell': Record<string, unknown>;
    }
  }
}

export interface AuthShellProps {
  variant?: 'centered' | 'split';
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const AuthShell: Component<AuthShellProps> = (props) => {
  const [local, rest] = splitProps(props, ['variant', 'children']);
  return (
    <arc-auth-shell variant={local.variant} {...rest}>
      {local.children}
    </arc-auth-shell>
  );
};
