// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/resizable';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-resizable': Record<string, unknown>;
    }
  }
}

export interface ResizableProps {
  direction?: 'horizontal' | 'vertical';
  minSize?: number;
  maxSize?: number;
  size?: number;
  onArcResize?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Resizable: Component<ResizableProps> = (props) => {
  const [local, rest] = splitProps(props, ['direction', 'minSize', 'maxSize', 'size', 'onArcResize', 'children']);
  return (
    <arc-resizable direction={local.direction} prop:minSize={local.minSize} prop:maxSize={local.maxSize} size={local.size} on:arc-resize={local.onArcResize} {...rest}>
      {local.children}
    </arc-resizable>
  );
};
