// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface ResponsiveSwitcherProps {
  threshold?: string;
  gap?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  children?: JSX.Element;
  [key: string]: unknown;
}

export const ResponsiveSwitcher: Component<ResponsiveSwitcherProps> = (props) => {
  const [local, rest] = splitProps(props, ['threshold', 'gap', 'children']);
  return (
    <arc-responsive-switcher threshold={local.threshold} gap={local.gap} {...rest}>
      {local.children}
    </arc-responsive-switcher>
  );
};
