<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: number;
    type?: string;
    locale?: string;
    currency?: string;
    decimals?: number;
    notation?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = 0, type = 'number', locale = 'en-US', currency = 'USD', decimals = undefined, notation = 'standard', children, ...rest }: Props = $props();
</script>

<arc-number-format {value} {type} {locale} {currency} {decimals} {notation} {...rest}>
  {@render children?.()}
</arc-number-format>
