<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: 'accent' | 'code';
    as?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { variant = 'body', as = 'p', children, ...rest }: Props = $props();
</script>

<arc-text {variant} {as} {...rest}>
  {@render children?.()}
</arc-text>
