<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    lines?: number;
    expanded?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { lines = 3, expanded = false, children, ...rest }: Props = $props();
</script>

<arc-truncate {lines} {expanded} {...rest}>
  {@render children?.()}
</arc-truncate>
