<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    text?: string;
    speed?: number;
    delay?: number;
    cursor?: boolean;
    loop?: boolean;
    _displayText?: string;
    _complete?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { text = '', speed = 50, delay = 0, cursor = true, loop = false, _displayText = '', _complete = false, children, ...rest }: Props = $props();
</script>

<arc-typewriter {text} {speed} {delay} {cursor} {loop} {_displayText} {_complete} {...rest}>
  {@render children?.()}
</arc-typewriter>
