// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcBreadcrumbItem } from '@arclux/arc-ui/breadcrumb-item';

export interface BreadcrumbItemProps {
  href?: string;
  className?: string;
  children?: React.ReactNode;
}

export const BreadcrumbItem = createComponent({
  tagName: 'arc-breadcrumb-item',
  elementClass: ArcBreadcrumbItem,
  react: React,
});
