// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcFooter } from '@arclux/arc-ui/footer';

export interface FooterProps {
  density?: 'default' | 'compact';
  border?: boolean;
  contained?: string;
  align?: 'left' | 'center';
  className?: string;
  children?: React.ReactNode;
}

export const Footer = createComponent({
  tagName: 'arc-footer',
  elementClass: ArcFooter,
  react: React,
});
