// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcMenubar } from '@arclux/arc-ui/menubar';

export interface MenubarProps {
  items?: unknown[];
  className?: string;
  children?: React.ReactNode;
  onArcSelect?: (e: CustomEvent) => void;
  onClick?: (e: Event) => void;
}

export const Menubar = createComponent({
  tagName: 'arc-menubar',
  elementClass: ArcMenubar,
  react: React,
  events: {
    onArcSelect: 'arc-select' as EventName<CustomEvent>,
    onClick: 'click' as EventName<Event>,
  },
});
