// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcNavItem } from '@arclux/arc-ui';

export interface NavItemProps {
  href?: string;
  active?: boolean;
  variant?: string;
  description?: string;
  className?: string;
  children?: React.ReactNode;
}

export const NavItem = createComponent({
  tagName: 'arc-nav-item',
  elementClass: ArcNavItem,
  react: React,
});
