// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcPageIndicator } from '@arclux/arc-ui';

export interface PageIndicatorProps {
  count?: number;
  value?: number;
  clickable?: boolean;
  className?: string;
  children?: React.ReactNode;
  onArcChange?: (e: CustomEvent) => void;
}

export const PageIndicator = createComponent({
  tagName: 'arc-page-indicator',
  elementClass: ArcPageIndicator,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
