// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcRail } from '@arclux/arc-ui';

export interface RailProps {
  items?: string;
  value?: string;
  expanded?: boolean;
  className?: string;
  children?: React.ReactNode;
  onArcChange?: (e: CustomEvent) => void;
}

export const Rail = createComponent({
  tagName: 'arc-rail',
  elementClass: ArcRail,
  react: React,
  events: {
    onArcChange: 'arc-change' as EventName<CustomEvent>,
  },
});
