// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcScrollToTop } from '@arclux/arc-ui/scroll-to-top';

export interface ScrollToTopProps {
  threshold?: number;
  smooth?: boolean;
  position?: 'bottom-right' | 'bottom-left';
  offset?: string;
  className?: string;
  children?: React.ReactNode;
  onClick?: (e: Event) => void;
}

export const ScrollToTop = createComponent({
  tagName: 'arc-scroll-to-top',
  elementClass: ArcScrollToTop,
  react: React,
  events: {
    onClick: 'click' as EventName<Event>,
  },
});
