// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcTopBar } from '@arclux/arc-ui';

export interface TopBarProps {
  heading?: string;
  fixed?: boolean;
  menuOpen?: boolean;
  mobileMenu?: string;
  menuPosition?: string;
  className?: string;
  children?: React.ReactNode;
}

export const TopBar = createComponent({
  tagName: 'arc-top-bar',
  elementClass: ArcTopBar,
  react: React,
});
