// Auto-generated by @arclux/prism 3.2.0 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcTopBar } from '@arclux/arc-ui/top-bar';

export interface TopBarProps {
  heading?: string;
  homeHref?: string;
  scrolled?: boolean;
  immersive?: boolean;
  fixed?: boolean;
  contained?: string;
  menuOpen?: boolean;
  mobileMenu?: 'sidebar' | 'nav' | 'none';
  menuPosition?: string;
  mobileCenter?: 'center' | 'end' | 'hidden';
  navAlign?: 'left' | 'center' | 'right';
  className?: string;
  children?: React.ReactNode;
  onArcSidebarToggle?: (e: CustomEvent) => void;
  onArcMobileMenuToggle?: (e: CustomEvent) => void;
}

export const TopBar = createComponent({
  tagName: 'arc-top-bar',
  elementClass: ArcTopBar,
  react: React,
  events: {
    onArcSidebarToggle: 'arc-sidebar-toggle' as EventName<CustomEvent>,
    onArcMobileMenuToggle: 'arc-mobile-menu-toggle' as EventName<CustomEvent>,
  },
});
