// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcTreeItem } from '@arclux/arc-ui/tree-item';

export interface TreeItemProps {
  label?: string;
  icon?: string;
  expanded?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const TreeItem = createComponent({
  tagName: 'arc-tree-item',
  elementClass: ArcTreeItem,
  react: React,
});
