<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/alert';
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: 'info' | 'tip' | 'success' | 'warning' | 'error';
    live?: 'auto' | 'off' | 'polite' | 'assertive';
    density?: 'default' | 'compact';
    dismissible?: boolean;
    heading?: string;
    /** <slot name="icon"> — put slot="icon" on the element inside. */
    icon?: Snippet;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { variant, live, density, dismissible, heading = '', icon, children, ...rest }: Props = $props();
</script>

<arc-alert {variant} {live} {density} {dismissible} {heading} {...rest}>
  {@render icon?.()}
  {@render children?.()}
</arc-alert>
