<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    open?: boolean;
    position?: 'bottom' | 'top' | 'left' | 'right';
    trigger?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { open = false, position = 'bottom', trigger = '', children, ...rest }: Props = $props();
</script>

<arc-popover {open} {position} {trigger} {...rest}>
  {@render children?.()}
</arc-popover>
