<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/snackbar';
  import type { Snippet } from 'svelte';

  interface Props {
    position?: 'bottom-center' | 'bottom-left' | 'bottom-right';
    duration?: number;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { position = 'bottom-center', duration = 5000, children, ...rest }: Props = $props();
</script>

<arc-snackbar {position} {duration} {...rest}>
  {@render children?.()}
</arc-snackbar>
