<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'AspectGrid' });

withDefaults(defineProps<{
  columns?: number;
  ratio?: string;
  gap?: 'sm' | 'md' | 'lg';
}>(), {
  columns: 3,
  ratio: '1/1',
  gap: 'md',
});
</script>

<template>
  <arc-aspect-grid
    :columns="columns"
    :ratio="ratio"
    :gap="gap"
  >
    <slot />
  </arc-aspect-grid>
</template>
