<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/center';

defineOptions({ name: 'Center' });

const props = withDefaults(defineProps<{
  maxWidth?: string;
  intrinsic?: boolean;
  text?: boolean;
}>(), {
  maxWidth: '60ch',
});
</script>

<template>
  <arc-center
    :maxWidth="props.maxWidth"
    :intrinsic="props.intrinsic"
    :text="props.text"
  >
    <slot />
  </arc-center>
</template>
