<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/float-bar';

defineOptions({ name: 'FloatBar' });

const props = defineProps<{
  open?: boolean;
  position?: 'bottom' | 'top';
}>();
</script>

<template>
  <arc-float-bar
    :open="props.open"
    :position="props.position"
  >
    <slot />
  </arc-float-bar>
</template>
