<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/inset';

defineOptions({ name: 'Inset' });

const props = withDefaults(defineProps<{
  space?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
  bleed?: boolean;
}>(), {
  space: 'md',
  bleed: false,
});
</script>

<template>
  <arc-inset
    :space="props.space"
    :bleed="props.bleed"
  >
    <slot />
  </arc-inset>
</template>
