<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/masonry';

defineOptions({ name: 'Masonry' });

const props = withDefaults(defineProps<{
  columns?: number;
  gap?: 'sm' | 'md' | 'lg';
}>(), {
  columns: 3,
});
</script>

<template>
  <arc-masonry
    :columns="props.columns"
    :gap="props.gap"
  >
    <slot />
  </arc-masonry>
</template>
