<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/responsive-switcher';

defineOptions({ name: 'ResponsiveSwitcher' });

const props = withDefaults(defineProps<{
  threshold?: string;
  gap?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
}>(), {
  threshold: '600px',
});
</script>

<template>
  <arc-responsive-switcher
    :threshold="props.threshold"
    :gap="props.gap"
  >
    <slot />
  </arc-responsive-switcher>
</template>
