<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/section';

defineOptions({ name: 'Section' });

const props = withDefaults(defineProps<{
  label?: string;
}>(), {
  label: '',
});
</script>

<template>
  <arc-section
    :label="props.label"
  >
    <slot />
  </arc-section>
</template>
