<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/split-pane';

defineOptions({ name: 'SplitPane' });

withDefaults(defineProps<{
  orientation?: 'vertical' | 'horizontal';
  ratio?: number;
  minRatio?: number;
  maxRatio?: number;
}>(), {
  orientation: 'horizontal',
  ratio: 0.5,
  minRatio: 0.15,
  maxRatio: 0.85,
});

const emit = defineEmits<{
  'arc-resize': [event: CustomEvent];
  'update:ratio': [value: number];
}>();

function onArcResize(payload: CustomEvent) {
  emit('arc-resize', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('ratio' in detail) emit('update:ratio', detail.ratio as number);
  }
}
</script>

<template>
  <arc-split-pane
    :orientation="orientation"
    :ratio="ratio"
    :minRatio="minRatio"
    :maxRatio="maxRatio"
    @arc-resize="onArcResize"
  >
    <slot />
  </arc-split-pane>
</template>
