// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/app-shell';

@Component({
  selector: 'arc-app-shell',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-app-shell [sidebarOpen]="sidebarOpen" [attr.breakpoint]="breakpoint"><ng-content /></arc-app-shell>`,
})
export class AppShell {
  @Input() sidebarOpen: boolean = false;
  @Input() breakpoint: number = 900;
}
