// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-container',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-container [narrow]="narrow" [attr.size]="size" [attr.padding]="padding"><ng-content /></arc-container>`,
})
export class Container {
  @Input() narrow: boolean = false;
  @Input() size: 'sm' | 'md' | 'lg' | 'xl' | 'full' = 'md';
  @Input() padding: 'none' | 'sm' | 'lg' = 'md';
}
