// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/dashboard-grid';
import type { ArcDashboardGrid } from '@arclux/arc-ui/dashboard-grid';

@Component({
  selector: 'arc-dashboard-grid',
  standalone: true,
  template: `<ng-content />`,
})
export class DashboardGrid {
  private readonly _el: ArcDashboardGrid = inject(ElementRef).nativeElement;

  @Input() set columns(value: number) {
    this._el.columns = value;
  }
  get columns(): number {
    return this._el.columns;
  }

  @Input() set gap(value: string) {
    this._el.gap = value;
  }
  get gap(): string {
    return this._el.gap;
  }

  @Input() set minColumnWidth(value: string) {
    this._el.minColumnWidth = value;
  }
  get minColumnWidth(): string {
    return this._el.minColumnWidth;
  }
}
