// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/dock';

@Component({
  selector: 'arc-dock',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-dock [attr.position]="position" [autoHide]="autoHide" [open]="open"><ng-content /></arc-dock>`,
})
export class Dock {
  @Input() position: 'bottom' | 'left' | 'right' = 'bottom';
  @Input() autoHide: boolean = false;
  @Input() open: boolean = false;
}
