// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/resizable';

@Component({
  selector: 'arc-resizable',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-resizable [attr.direction]="direction" [attr.minSize]="minSize" [attr.maxSize]="maxSize" [attr.size]="size" (arc-resize)="onArcResize($event)"><ng-content /></arc-resizable>`,
})
export class Resizable {
  @Input() direction: 'horizontal' | 'vertical' = 'horizontal';
  @Input() minSize: number = 100;
  @Input() maxSize: number = Infinity;
  @Input() size: number = 300;
  @Output() arcResize = new EventEmitter<CustomEvent>();
  @Output() sizeChange = new EventEmitter<number>();

  onArcResize(event: CustomEvent) {
    this.arcResize.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('size' in detail) {
      const next = detail.size as number;
      this.size = next;
      this.sizeChange.emit(next);
    }
  }
}
