// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/settings-layout';
import type { ArcSettingsLayout } from '@arclux/arc-ui/settings-layout';

@Component({
  selector: 'arc-settings-layout',
  standalone: true,
  template: `<ng-content />`,
})
export class SettingsLayout {
  private readonly _el: ArcSettingsLayout = inject(ElementRef).nativeElement;

  @Input() set navPosition(value: 'left' | 'top') {
    this._el.navPosition = value;
  }
  get navPosition(): 'left' | 'top' {
    return this._el.navPosition;
  }
}
