// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/split-pane';

@Component({
  selector: 'arc-split-pane',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-split-pane [attr.orientation]="this.orientation" [attr.ratio]="this.ratio" [attr.minRatio]="this.minRatio" [attr.maxRatio]="this.maxRatio" (arc-resize)="this.onArcResize($event)"><ng-content /></arc-split-pane>`,
})
export class SplitPane {
  @Input() orientation: 'horizontal' | 'vertical' = 'horizontal';
  @Input() ratio: number = 0.5;
  @Input() minRatio: number = 0.15;
  @Input() maxRatio: number = 0.85;
  @Output() arcResize = new EventEmitter<CustomEvent>();
  @Output() ratioChange = new EventEmitter<number>();

  onArcResize(event: CustomEvent) {
    this.arcResize.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('ratio' in detail) {
      const next = detail.ratio as number;
      this.ratio = next;
      this.ratioChange.emit(next);
    }
  }
}
