// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/toolbar';

@Component({
  selector: 'arc-toolbar',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-toolbar [sticky]="this.sticky" [attr.size]="this.size" [border]="this.border" [overflow]="this.overflow" (arc-overflow-change)="this.arcOverflowChange.emit($event)"><ng-content /></arc-toolbar>`,
})
export class Toolbar {
  @Input() sticky: boolean = false;
  @Input() size: 'md' | 'sm' = 'md';
  @Input() border: boolean = true;
  @Input() overflow: boolean = false;
  @Output() arcOverflowChange = new EventEmitter<CustomEvent>();
}
