// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface AvatarGroupProps {
  max?: number;
  overlap?: 'sm' | 'lg';
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const AvatarGroup: FunctionComponent<AvatarGroupProps> = ({ max, overlap, children, ...rest }) => (
  <arc-avatar-group max={max} overlap={overlap} {...rest}>
    {children}
  </arc-avatar-group>
);
