// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/callout';

export interface CalloutProps {
  variant?: string;
  dismissible?: boolean;
  onArcDismiss?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Callout: FunctionComponent<CalloutProps> = ({ variant, dismissible, onArcDismiss, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcDismiss) {
      const fn: EventListener = (e) => onArcDismiss(e as CustomEvent);
      el.addEventListener('arc-dismiss', fn);
      listeners.push(['arc-dismiss', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcDismiss]);
  return (
    <arc-callout ref={ref} variant={variant} dismissible={dismissible} {...rest}>
      {children}
    </arc-callout>
  );
};
