// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/callout';

export interface CalloutProps {
  variant?: string;
  dismissible?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Callout: FunctionComponent<CalloutProps> = ({ variant, dismissible, children, ...rest }) => (
  <arc-callout variant={variant} dismissible={dismissible} {...rest}>
    {children}
  </arc-callout>
);
