// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/collapsible';

export interface CollapsibleProps {
  open?: boolean;
  heading?: string;
  onArcToggle?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Collapsible: FunctionComponent<CollapsibleProps> = ({ open, heading, onArcToggle, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcToggle) {
      const fn: EventListener = (e) => onArcToggle(e as CustomEvent);
      el.addEventListener('arc-toggle', fn);
      listeners.push(['arc-toggle', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcToggle]);
  return (
    <arc-collapsible ref={ref} open={open} heading={heading} {...rest}>
      {children}
    </arc-collapsible>
  );
};
