// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/divider';

export interface DividerProps {
  variant?: 'subtle' | 'glow' | 'line-white' | 'line-primary' | 'line-gradient';
  align?: '' | 'left' | 'right';
  vertical?: boolean;
  label?: string;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Divider: FunctionComponent<DividerProps> = ({ variant, align, vertical, label, ...rest }) =>
  h('arc-divider', { variant, align, vertical, label, ...rest });
