// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface MarqueeProps {
  speed?: number;
  direction?: string;
  gap?: string;
  _animDuration?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Marquee: FunctionComponent<MarqueeProps> = ({ speed, direction, gap, _animDuration, children, ...rest }) => (
  <arc-marquee speed={speed} direction={direction} gap={gap} _animDuration={_animDuration} {...rest}>
    {children}
  </arc-marquee>
);
