// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/qr-code';

export interface QrCodeProps {
  value?: string;
  size?: number;
  level?: 'L' | 'M' | 'Q' | 'H';
  label?: string;
  quietZone?: number;
  contrast?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const QrCode: FunctionComponent<QrCodeProps> = ({ value, size, level, label, quietZone, contrast, children, ...rest }) => (
  <arc-qr-code value={value} size={size} level={level} label={label} quietZone={quietZone} contrast={contrast} {...rest}>
    {children}
  </arc-qr-code>
);
