// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface ScrollIndicatorProps {
  target?: string;
  position?: 'bottom';
  size?: 'sm' | 'md' | 'lg';
  color?: 'gradient';
  _progress?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const ScrollIndicator: FunctionComponent<ScrollIndicatorProps> = ({ target, position, size, color, _progress, children, ...rest }) => (
  <arc-scroll-indicator target={target} position={position} size={size} color={color} _progress={_progress} {...rest}>
    {children}
  </arc-scroll-indicator>
);
