// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/virtual-list';

export interface VirtualListProps {
  items?: unknown[];
  itemHeight?: number;
  overscan?: number;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const VirtualList: FunctionComponent<VirtualListProps> = ({ items, itemHeight, overscan, ...rest }) => (
  <arc-virtual-list items={items} itemHeight={itemHeight} overscan={overscan} {...rest}>
  </arc-virtual-list>
);
