/**
 * arc-terminal — the animated terminal window.
 *
 * What this pins:
 *   - the instant paths (reduced motion, playback never started) render the
 *     complete transcript, so the content is never hostage to an animation
 *   - the three line types keep their distinguishing classes and the prompt
 *     glyph renders on command lines
 *   - arc-complete fires with the library's bubbles+composed contract
 *   - reset() blanks the transcript and play() runs it again
 *   - empty transcripts and empty/malformed lines never throw
 */
import { expect } from '@esm-bundle/chai';
import { cleanup } from './helpers.js';
import { ArcTerminal } from '../src/typography/terminal.js';

// The .register.js file is generated by pnpm generate; defining here keeps the
// test self-sufficient and is a no-op once the generated define has run.
if (!customElements.get('arc-terminal')) {
  customElements.define('arc-terminal', ArcTerminal);
}

const LINES = [
  { type: 'comment', text: '# install the library' },
  { type: 'command', text: 'pnpm add @arclux/arc-ui' },
  { type: 'output', text: '+ @arclux/arc-ui 3.0.0' },
];

/* Per-line delay of 1ms and 1ms per character, so the animated tests finish in
   a few milliseconds of real time. */
const FAST_LINES = [
  { type: 'command', text: 'ok', delay: 1 },
  { type: 'output', text: 'done', delay: 1 },
];

const realMatchMedia = window.matchMedia;

/** Make the component believe prefers-reduced-motion is active. */
function stubReducedMotion() {
  window.matchMedia = (query) => ({
    matches: query.includes('prefers-reduced-motion'),
    addEventListener() {},
    removeEventListener() {},
  });
}

function create({ lines = LINES, autoplay = false, ...props } = {}) {
  const el = document.createElement('arc-terminal');
  // Assign before connecting so connectedCallback sees the intended values.
  el.autoplay = autoplay;
  el.lines = lines;
  Object.assign(el, props);
  document.body.appendChild(el);
  return el;
}

function once(el, type) {
  return new Promise((resolve) => el.addEventListener(type, resolve, { once: true }));
}

const bodyText = (el) => el.shadowRoot.querySelector('.terminal__body').textContent;

afterEach(() => {
  window.matchMedia = realMatchMedia;
  cleanup();
});

describe('arc-terminal', () => {
  it('renders the complete transcript under reduced motion', async () => {
    stubReducedMotion();
    const el = create({ autoplay: true });
    await el.updateComplete;

    for (const line of LINES) {
      expect(bodyText(el)).to.contain(line.text);
    }
    expect(el.shadowRoot.querySelectorAll('.terminal__line--pending').length).to.equal(0);
  });

  it('renders the complete transcript when playback has not started', async () => {
    const el = create({ autoplay: false });
    await el.updateComplete;

    for (const line of LINES) {
      expect(bodyText(el)).to.contain(line.text);
    }
    expect(el.shadowRoot.querySelectorAll('.terminal__line--pending').length).to.equal(0);
  });

  it('marks command, output and comment lines with their own classes', async () => {
    const el = create();
    await el.updateComplete;

    const command = el.shadowRoot.querySelector('.terminal__line--command');
    const output = el.shadowRoot.querySelector('.terminal__line--output');
    const comment = el.shadowRoot.querySelector('.terminal__line--comment');

    expect(command.textContent).to.contain('pnpm add @arclux/arc-ui');
    expect(output.textContent).to.contain('+ @arclux/arc-ui 3.0.0');
    expect(comment.textContent).to.contain('# install the library');
  });

  it('treats an unknown line type as output', async () => {
    const el = create({ lines: [{ type: 'banana', text: 'mystery' }] });
    await el.updateComplete;

    expect(el.shadowRoot.querySelector('.terminal__line--output').textContent).to.contain('mystery');
  });

  it('renders the prompt glyph on command lines', async () => {
    const el = create();
    await el.updateComplete;

    const prompt = el.shadowRoot.querySelector('.terminal__line--command .terminal__prompt');
    expect(prompt.textContent).to.equal('$');

    el.prompt = '>';
    await el.updateComplete;
    expect(
      el.shadowRoot.querySelector('.terminal__line--command .terminal__prompt').textContent
    ).to.equal('>');
  });

  it('fires arc-complete with bubbles and composed', async () => {
    stubReducedMotion();
    const el = create();
    await el.updateComplete;

    // Listen on body: only a bubbling event arrives there.
    const heard = once(document.body, 'arc-complete');
    el.play();
    const event = await heard;

    expect(event.bubbles).to.equal(true);
    expect(event.composed).to.equal(true);
  });

  it('animates the sequence, and reset() + play() runs it again', async () => {
    const el = create({ lines: FAST_LINES, speed: 1 });
    await el.updateComplete;

    let done = once(el, 'arc-complete');
    el.play();
    await done;
    await el.updateComplete;

    expect(bodyText(el)).to.contain('ok');
    expect(bodyText(el)).to.contain('done');
    expect(el.shadowRoot.querySelectorAll('.terminal__line--pending').length).to.equal(0);

    el.reset();
    await el.updateComplete;

    // Blank again: the first command sits at zero typed characters and
    // everything after it is pending.
    const typed = el.shadowRoot.querySelector('.terminal__line--command .terminal__text');
    expect(typed.textContent.trim()).to.equal('');
    expect(el.shadowRoot.querySelectorAll('.terminal__line--pending').length).to.be.greaterThan(0);

    done = once(el, 'arc-complete');
    el.play();
    await done;
    await el.updateComplete;

    expect(bodyText(el)).to.contain('ok');
    expect(bodyText(el)).to.contain('done');
  });

  it('completes immediately on an empty transcript', async () => {
    const el = create({ lines: [] });
    await el.updateComplete;

    const heard = once(el, 'arc-complete');
    el.play();
    await heard;

    // Only the idle prompt-and-cursor line remains.
    expect(el.shadowRoot.querySelector('.terminal__cursor')).to.exist;
  });

  it('survives empty and malformed lines', async () => {
    const el = create({
      lines: [
        { type: 'output', text: '' },
        null,
        { text: 'no type at all' },
        { type: 'command', text: '', delay: 1 },
      ],
    });
    await el.updateComplete;

    expect(bodyText(el)).to.contain('no type at all');

    stubReducedMotion();
    const fresh = create({ lines: [{ type: 'output', text: '' }] });
    await fresh.updateComplete;
    const heard = once(fresh, 'arc-complete');
    fresh.play();
    await heard;
  });
});
