<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/animated-number';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: number;
    duration?: number;
    format?: 'number' | 'currency' | 'percent';
    prefix?: string;
    suffix?: string;
    decimals?: number;
    locale?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { value = 0, duration = 1000, format = 'number', prefix = '', suffix = '', decimals = 0, locale = 'en-US', children, ...rest }: Props = $props();
</script>

<arc-animated-number {value} {duration} {format} {prefix} {suffix} {decimals} {locale} {...rest}>
  {@render children?.()}
</arc-animated-number>
