<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/app-shell';
  import type { Snippet } from 'svelte';

  interface Props {
    sidebarOpen?: boolean;
    embedded?: boolean;
    breakpoint?: number;
    /** <slot name="topbar"> — put slot="topbar" on the element inside. */
    topbar?: Snippet;
    /** <slot name="sidebar"> — put slot="sidebar" on the element inside. */
    sidebar?: Snippet;
    /** <slot name="toc"> — put slot="toc" on the element inside. */
    toc?: Snippet;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { sidebarOpen = $bindable(), embedded, breakpoint, topbar, sidebar, toc, children, ...rest }: Props = $props();

  let __el: HTMLElement | undefined = $state();
  $effect(() => {
    const el = __el as unknown as Record<string, unknown> | undefined;
    if (!el) return;
    if (sidebarOpen !== undefined) el.sidebarOpen = sidebarOpen;
  });

  // Two-way binding — mirror the event detail back onto the prop, then
  // forward to the consumer's own handler, which {...rest} would otherwise
  // have attached. These are declared after {...rest} below so they win.
  function __onArcSidebarToggle(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) sidebarOpen = detail.value as boolean;
    }
    (rest['onarc-sidebar-toggle'] as ((e: Event) => void) | undefined)?.(e);
  }
</script>

<arc-app-shell {embedded} {breakpoint} bind:this={__el} {...rest}
  onarc-sidebar-toggle={__onArcSidebarToggle}
>
  {@render topbar?.()}
  {@render sidebar?.()}
  {@render toc?.()}
  {@render children?.()}
</arc-app-shell>
