<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/app-shell';
  import type { Snippet } from 'svelte';

  interface Props {
    sidebarOpen?: boolean;
    breakpoint?: number;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { sidebarOpen = false, breakpoint = 900, children, ...rest }: Props = $props();
</script>

<arc-app-shell {sidebarOpen} {breakpoint} {...rest}>
  {@render children?.()}
</arc-app-shell>
