<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    maxWidth?: string;
    intrinsic?: boolean;
    text?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { maxWidth = '60ch', intrinsic = false, text = false, children, ...rest }: Props = $props();
</script>

<arc-center {maxWidth} {intrinsic} {text} {...rest}>
  {@render children?.()}
</arc-center>
