<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/page-layout';
  import type { Snippet } from 'svelte';

  interface Props {
    layout?: 'sidebar-left' | 'sidebar-right' | 'centered' | 'wide';
    maxWidth?: string;
    gap?: string;
    /** <slot name="sidebar"> — put slot="sidebar" on the element inside. */
    sidebar?: Snippet;
    /** <slot name="aside"> — put slot="aside" on the element inside. */
    aside?: Snippet;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { layout, maxWidth = '1120px', gap = 'var(--space-xl)', sidebar, aside, children, ...rest }: Props = $props();

  let __el: HTMLElement | undefined = $state();
  $effect(() => {
    const el = __el as unknown as Record<string, unknown> | undefined;
    if (!el) return;
    if (maxWidth !== undefined) el.maxWidth = maxWidth;
  });
</script>

<arc-page-layout {layout} {gap} bind:this={__el} {...rest}>
  {@render sidebar?.()}
  {@render aside?.()}
  {@render children?.()}
</arc-page-layout>
