<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/status-bar';
  import type { Snippet } from 'svelte';

  interface Props {
    position?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { position = 'static', children, ...rest }: Props = $props();
</script>

<arc-status-bar {position} {...rest}>
  {@render children?.()}
</arc-status-bar>
