<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/toolbar';
  import type { Snippet } from 'svelte';

  interface Props {
    sticky?: boolean;
    size?: 'sm';
    border?: boolean;
    overflow?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { sticky = false, size = 'md', border = true, overflow = false, children, ...rest }: Props = $props();
</script>

<arc-toolbar {sticky} {size} {border} {overflow} {...rest}>
  {@render children?.()}
</arc-toolbar>
