// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface AlertProps {
  variant?: 'info' | 'success' | 'warning' | 'error';
  dismissible?: boolean;
  heading?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Alert: FunctionComponent<AlertProps> = ({ variant, dismissible, heading, children, ...rest }) => (
  <arc-alert variant={variant} dismissible={dismissible} heading={heading} {...rest}>
    {children}
  </arc-alert>
);
