// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/alert';

export interface AlertProps {
  variant?: string;
  compact?: boolean;
  dismissible?: boolean;
  heading?: string;
  onArcDismiss?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Alert: FunctionComponent<AlertProps> = ({ variant, compact, dismissible, heading, onArcDismiss, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcDismiss) {
      const fn: EventListener = (e) => onArcDismiss(e as CustomEvent);
      el.addEventListener('arc-dismiss', fn);
      listeners.push(['arc-dismiss', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcDismiss]);
  return (
    <arc-alert ref={ref} variant={variant} compact={compact} dismissible={dismissible} heading={heading} {...rest}>
      {children}
    </arc-alert>
  );
};
