// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/banner';

export interface BannerProps {
  variant?: 'info' | 'success' | 'warning' | 'error';
  dismissible?: boolean;
  sticky?: boolean;
  onArcClose?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Banner: FunctionComponent<BannerProps> = ({ variant, dismissible, sticky, onArcClose, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcClose) {
      const fn: EventListener = (e) => onArcClose(e as CustomEvent);
      el.addEventListener('arc-close', fn);
      listeners.push(['arc-close', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcClose]);
  return h('arc-banner', { ref, variant, dismissible, sticky, ...rest }, children);
};
