// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h } from 'preact';
import { forwardRef } from 'preact/compat';
import { useImperativeHandle, useRef } from 'preact/hooks';
import '@arclux/arc-ui/conversation';
import type { ArcConversation } from '@arclux/arc-ui/conversation';

export interface ConversationProps {
  autoScroll?: boolean;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

/** Driven by its methods: scrollToEnd(). A ref on it holds the element. */
export const Conversation = forwardRef<ArcConversation, ConversationProps>(({ autoScroll, children, ...rest }, forwarded) => {
  const ref = useRef<ArcConversation>(null);
  useImperativeHandle(forwarded, () => ref.current as ArcConversation, []);
  return h('arc-conversation', { ref, autoScroll, ...rest }, children);
});
