// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/hover-card';

export interface HoverCardProps {
  position?: string;
  openDelay?: number;
  closeDelay?: number;
  onArcOpen?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const HoverCard: FunctionComponent<HoverCardProps> = ({ position, openDelay, closeDelay, onArcOpen, onArcClose, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcOpen) {
      const fn: EventListener = (e) => onArcOpen(e as CustomEvent);
      el.addEventListener('arc-open', fn);
      listeners.push(['arc-open', fn]);
    }
    if (onArcClose) {
      const fn: EventListener = (e) => onArcClose(e as CustomEvent);
      el.addEventListener('arc-close', fn);
      listeners.push(['arc-close', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcOpen, onArcClose]);
  return (
    <arc-hover-card ref={ref} position={position} openDelay={openDelay} closeDelay={closeDelay} {...rest}>
      {children}
    </arc-hover-card>
  );
};
