// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/hover-card';

export interface HoverCardProps {
  position?: 'bottom' | 'top' | 'left' | 'right';
  openDelay?: number;
  closeDelay?: number;
  onArcOpen?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const HoverCard: FunctionComponent<HoverCardProps> = ({ position, openDelay, closeDelay, onArcOpen, onArcClose, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcOpen) {
      const fn: EventListener = (e) => onArcOpen(e as CustomEvent);
      el.addEventListener('arc-open', fn);
      listeners.push(['arc-open', fn]);
    }
    if (onArcClose) {
      const fn: EventListener = (e) => onArcClose(e as CustomEvent);
      el.addEventListener('arc-close', fn);
      listeners.push(['arc-close', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcOpen, onArcClose]);
  return h('arc-hover-card', { ref, position, openDelay, closeDelay, ...rest }, children);
};
