// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/inline-message';

export interface InlineMessageProps {
  variant?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const InlineMessage: FunctionComponent<InlineMessageProps> = ({ variant, children, ...rest }) => (
  <arc-inline-message variant={variant} {...rest}>
    {children}
  </arc-inline-message>
);
