// Auto-generated by @arclux/prism 3.2.0 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/sheet';

export interface SheetProps {
  open?: boolean;
  side?: 'bottom' | 'right';
  heading?: string;
  modal?: boolean;
  snapPoints?: string;
  snap?: number;
  persistent?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  onArcOpen?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Sheet: FunctionComponent<SheetProps> = ({ open, side, heading, modal, snapPoints, snap, persistent, onArcChange, onArcClose, onArcOpen, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    if (onArcClose) {
      const fn: EventListener = (e) => onArcClose(e as CustomEvent);
      el.addEventListener('arc-close', fn);
      listeners.push(['arc-close', fn]);
    }
    if (onArcOpen) {
      const fn: EventListener = (e) => onArcOpen(e as CustomEvent);
      el.addEventListener('arc-open', fn);
      listeners.push(['arc-open', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange, onArcClose, onArcOpen]);
  return h('arc-sheet', { ref, open, side, heading, modal, snapPoints, snap, persistent, ...rest }, children);
};
