// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/toast-manager';

export interface ToastManagerProps {
  position?: string;
  duration?: number;
  maxVisible?: number;
  dedupe?: boolean;
  queueLimit?: number;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const ToastManager: FunctionComponent<ToastManagerProps> = ({ position, duration, maxVisible, dedupe, queueLimit, children, ...rest }) => (
  <arc-toast-manager position={position} duration={duration} maxVisible={maxVisible} dedupe={dedupe} queueLimit={queueLimit} {...rest}>
    {children}
  </arc-toast-manager>
);
