// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/tooltip';

export interface TooltipProps {
  content?: string;
  position?: 'top' | 'bottom' | 'left' | 'right';
  delay?: number;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Tooltip: FunctionComponent<TooltipProps> = ({ content, position, delay, children, ...rest }) => (
  <arc-tooltip content={content} position={position} delay={delay} {...rest}>
    {children}
  </arc-tooltip>
);
