import '@arclux/arc-ui/color-swatch';
interface Props {
    color?: string;
    label?: string;
    size?: 'sm' | 'md' | 'lg';
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const ColorSwatch: import("svelte").Component<Props, {}, "">;
type ColorSwatch = ReturnType<typeof ColorSwatch>;
export default ColorSwatch;
