import '@arclux/arc-ui/hotspot';
import type { Snippet } from 'svelte';
interface Props {
    x?: number;
    y?: number;
    label?: string;
    open?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Hotspot: import("svelte").Component<Props, {}, "">;
type Hotspot = ReturnType<typeof Hotspot>;
export default Hotspot;
