import '@arclux/arc-ui/qr-code';
interface Props {
    value?: string;
    size?: number;
    level?: 'L' | 'M' | 'Q' | 'H';
    label?: string;
    quietZone?: number;
    contrast?: boolean;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const QrCode: import("svelte").Component<Props, {}, "">;
type QrCode = ReturnType<typeof QrCode>;
export default QrCode;
