import '@arclux/arc-ui/video';
interface Props {
    src?: string;
    poster?: string;
    label?: string;
    autoplay?: boolean;
    loop?: boolean;
    muted?: boolean;
    controls?: string;
    preload?: 'none' | 'metadata' | 'auto';
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Video: import("svelte").Component<Props, {}, "">;
type Video = ReturnType<typeof Video>;
export default Video;
