<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/command-palette';

defineOptions({ name: 'CommandPalette' });

withDefaults(defineProps<{
  open?: boolean;
  placeholder?: string;
}>(), {
  open: false,
  placeholder: 'Type a command...',
});

defineEmits<{
  'arc-select': [event: CustomEvent];
  'arc-close': [event: CustomEvent];
}>();
</script>

<template>
  <arc-command-palette
    :open="open"
    :placeholder="placeholder"
  >
    <slot />
  </arc-command-palette>
</template>
