<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/command-group';

defineOptions({ name: 'CommandGroup' });

withDefaults(defineProps<{
  heading?: string;
}>(), {
  heading: '',
});
</script>

<template>
  <arc-command-group
    :heading="heading"
  >
    <slot />
  </arc-command-group>
</template>
