<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/context-menu';

defineOptions({ name: 'ContextMenu' });

withDefaults(defineProps<{
  open?: boolean;
}>(), {
  open: false,
});

const emit = defineEmits<{
  'arc-open': [event: CustomEvent];
  'arc-close': [event: CustomEvent];
  'arc-select': [event: CustomEvent];
}>();
</script>

<template>
  <arc-context-menu
    :open="open"
    @arc-open="(payload: CustomEvent) => emit('arc-open', payload)"
    @arc-close="(payload: CustomEvent) => emit('arc-close', payload)"
    @arc-select="(payload: CustomEvent) => emit('arc-select', payload)"
  >
    <slot />
  </arc-context-menu>
</template>
