<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'LoadingOverlay' });

withDefaults(defineProps<{
  active?: boolean;
  message?: string;
  global?: boolean;
}>(), {
  active: false,
  message: '',
  global: false,
});
</script>

<template>
  <arc-loading-overlay
    :active="active"
    :message="message"
    :global="global"
  >
    <slot />
  </arc-loading-overlay>
</template>
