<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/popover';

defineOptions({ name: 'Popover' });

const props = withDefaults(defineProps<{
  open?: boolean;
  position?: 'top' | 'bottom' | 'left' | 'right';
  trigger?: string;
}>(), {
  trigger: '',
});

const emit = defineEmits<{
  'arc-open': [event: CustomEvent];
  'arc-close': [event: CustomEvent];
}>();
</script>

<template>
  <arc-popover
    :open="props.open"
    :position="props.position"
    :trigger="props.trigger"
    @arc-open="(payload: CustomEvent) => emit('arc-open', payload)"
    @arc-close="(payload: CustomEvent) => emit('arc-close', payload)"
  >
    <slot />
    <slot name="trigger" />
  </arc-popover>
</template>
