<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/spotlight';

defineOptions({ name: 'Spotlight' });

withDefaults(defineProps<{
  target?: string;
  active?: boolean;
  padding?: number;
}>(), {
  target: '',
  active: false,
  padding: 8,
});

const emit = defineEmits<{
  'arc-dismiss': [event: CustomEvent];
}>();
</script>

<template>
  <arc-spotlight
    :target="target"
    :active="active"
    :padding="padding"
    @arc-dismiss="(payload: CustomEvent) => emit('arc-dismiss', payload)"
  >
    <slot />
  </arc-spotlight>
</template>
