<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Toast' });

withDefaults(defineProps<{
  position?: 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center';
  duration?: number;
  _toasts?: string;
}>(), {
  position: 'top-right',
  duration: 4000,
  _toasts: () => ([]),
});

defineEmits<{
  'arc-dismiss': [event: CustomEvent];
}>();
</script>

<template>
  <arc-toast
    :position="position"
    :duration="duration"
    :_toasts="_toasts"
  >
    <slot />
  </arc-toast>
</template>
