// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  href?: string;
  disabled?: boolean;
  loading?: boolean;
  type?: string;
  _hasPrefix?: string;
  _hasSuffix?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Button: FunctionComponent<ButtonProps> = ({ variant, size, href, disabled, loading, type, _hasPrefix, _hasSuffix, children, ...rest }) => (
  <arc-button variant={variant} size={size} href={href} disabled={disabled} loading={loading} type={type} _hasPrefix={_hasPrefix} _hasSuffix={_hasSuffix} {...rest}>
    {children}
  </arc-button>
);
