// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/combobox';

export interface ComboboxProps {
  value?: string;
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Combobox: FunctionComponent<ComboboxProps> = ({ value, placeholder, label, name, disabled, children, ...rest }) => (
  <arc-combobox value={value} placeholder={placeholder} label={label} name={name} disabled={disabled} {...rest}>
    {children}
  </arc-combobox>
);
