// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/date-range-picker';

export interface DateRangePickerProps {
  start?: string;
  end?: string;
  name?: string;
  min?: string;
  max?: string;
  months?: number;
  presets?: unknown[];
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  label?: string;
  onArcChange?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const DateRangePicker: FunctionComponent<DateRangePickerProps> = ({ start, end, name, min, max, months, presets, placeholder, disabled, required, label, onArcChange, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return (
    <arc-date-range-picker ref={ref} start={start} end={end} name={name} min={min} max={max} months={months} presets={presets} placeholder={placeholder} disabled={disabled} required={required} label={label} {...rest}>
      {children}
    </arc-date-range-picker>
  );
};
