// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/file-upload';

export interface FileUploadProps {
  accept?: string;
  multiple?: boolean;
  maxSize?: number;
  disabled?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  onArcRemove?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const FileUpload: FunctionComponent<FileUploadProps> = ({ accept, multiple, maxSize, disabled, onArcChange, onArcRemove, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    if (onArcRemove) {
      const fn: EventListener = (e) => onArcRemove(e as CustomEvent);
      el.addEventListener('arc-remove', fn);
      listeners.push(['arc-remove', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange, onArcRemove]);
  return (
    <arc-file-upload ref={ref} accept={accept} multiple={multiple} maxSize={maxSize} disabled={disabled} {...rest}>
      {children}
    </arc-file-upload>
  );
};
