// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/hotkey';

export interface HotkeyProps {
  keys?: string;
  disabled?: boolean;
  global?: boolean;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Hotkey: FunctionComponent<HotkeyProps> = ({ keys, disabled, global, children, ...rest }) => (
  <arc-hotkey keys={keys} disabled={disabled} global={global} {...rest}>
    {children}
  </arc-hotkey>
);
