// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/icon-button';

export interface IconButtonProps {
  name?: string;
  text?: string;
  variant?: 'ghost' | 'secondary' | 'primary';
  size?: 'xs' | 'sm' | 'md' | 'lg';
  label?: string;
  href?: string;
  disabled?: boolean;
  type?: string;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const IconButton: FunctionComponent<IconButtonProps> = ({ name, text, variant, size, label, href, disabled, type, children, ...rest }) =>
  h('arc-icon-button', { name, text, variant, size, label, href, disabled, type, ...rest }, children);
