// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h } from 'preact';
import { forwardRef } from 'preact/compat';
import { useImperativeHandle, useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/inline-edit';
import type { ArcInlineEdit } from '@arclux/arc-ui/inline-edit';

export interface InlineEditProps {
  required?: boolean;
  readonly?: boolean;
  value?: string;
  label?: string;
  name?: string;
  placeholder?: string;
  multiline?: boolean;
  disabled?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  onArcCancel?: (e: CustomEvent) => void;
  onArcInput?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

/** Driven by its methods: focus(), edit(), commit(), cancel(), checkValidity() and reportValidity(). A ref on it holds the element. */
export const InlineEdit = forwardRef<ArcInlineEdit, InlineEditProps>(({ required, readonly, value, label, name, placeholder, multiline, disabled, onArcChange, onArcCancel, onArcInput, children, ...rest }, forwarded) => {
  const ref = useRef<ArcInlineEdit>(null);
  useImperativeHandle(forwarded, () => ref.current as ArcInlineEdit, []);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    if (onArcCancel) {
      const fn: EventListener = (e) => onArcCancel(e as CustomEvent);
      el.addEventListener('arc-cancel', fn);
      listeners.push(['arc-cancel', fn]);
    }
    if (onArcInput) {
      const fn: EventListener = (e) => onArcInput(e as CustomEvent);
      el.addEventListener('arc-input', fn);
      listeners.push(['arc-input', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange, onArcCancel, onArcInput]);
  return h('arc-inline-edit', { ref, required, readonly, value, label, name, placeholder, multiline, disabled, ...rest }, children);
});
