// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface InputGroupProps {
  size?: 'sm' | 'lg';
  _hasPrefix?: string;
  _hasSuffix?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const InputGroup: FunctionComponent<InputGroupProps> = ({ size, _hasPrefix, _hasSuffix, children, ...rest }) => (
  <arc-input-group size={size} _hasPrefix={_hasPrefix} _hasSuffix={_hasSuffix} {...rest}>
    {children}
  </arc-input-group>
);
