// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface LabelProps {
  for?: string;
  required?: boolean;
  size?: 'sm' | 'lg';
  disabled?: boolean;
  _hasDescription?: string;
  _hasTooltip?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Label: FunctionComponent<LabelProps> = ({ for, required, size, disabled, _hasDescription, _hasTooltip, children, ...rest }) => (
  <arc-label for={for} required={required} size={size} disabled={disabled} _hasDescription={_hasDescription} _hasTooltip={_hasTooltip} {...rest}>
    {children}
  </arc-label>
);
