// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/pin-input';

export interface PinInputProps {
  length?: number;
  value?: string;
  name?: string;
  disabled?: boolean;
  mask?: boolean;
  type?: 'number' | 'alphanumeric' | 'text';
  separator?: number;
  label?: string;
  onArcChange?: (e: CustomEvent) => void;
  onArcComplete?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const PinInput: FunctionComponent<PinInputProps> = ({ length, value, name, disabled, mask, type, separator, label, onArcChange, onArcComplete, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    if (onArcComplete) {
      const fn: EventListener = (e) => onArcComplete(e as CustomEvent);
      el.addEventListener('arc-complete', fn);
      listeners.push(['arc-complete', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange, onArcComplete]);
  return h('arc-pin-input', { ref, length, value, name, disabled, mask, type, separator, label, ...rest }, children);
};
