// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h } from 'preact';
import { forwardRef } from 'preact/compat';
import { useImperativeHandle, useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/range-slider';
import type { ArcRangeSlider } from '@arclux/arc-ui/range-slider';

export interface RangeSliderProps {
  required?: boolean;
  readonly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  min?: number;
  max?: number;
  step?: number;
  low?: number;
  high?: number;
  name?: string;
  disabled?: boolean;
  label?: string;
  showValues?: boolean;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

/** Driven by its methods: checkValidity() and reportValidity(). A ref on it holds the element. */
export const RangeSlider = forwardRef<ArcRangeSlider, RangeSliderProps>(({ required, readonly, size, min, max, step, low, high, name, disabled, label, showValues, onArcInput, onArcChange, ...rest }, forwarded) => {
  const ref = useRef<ArcRangeSlider>(null);
  useImperativeHandle(forwarded, () => ref.current as ArcRangeSlider, []);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcInput) {
      const fn: EventListener = (e) => onArcInput(e as CustomEvent);
      el.addEventListener('arc-input', fn);
      listeners.push(['arc-input', fn]);
    }
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcInput, onArcChange]);
  return h('arc-range-slider', { ref, required, readonly, size, min, max, step, low, high, name, disabled, label, showValues, ...rest });
});
