// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface SelectProps {
  value?: string;
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  open?: boolean;
  _options?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Select: FunctionComponent<SelectProps> = ({ value, placeholder, label, name, disabled, open, _options, children, ...rest }) => (
  <arc-select value={value} placeholder={placeholder} label={label} name={name} disabled={disabled} open={open} _options={_options} {...rest}>
    {children}
  </arc-select>
);
