// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/select';

export interface SelectProps {
  value?: string;
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  size?: 'sm' | 'lg';
  error?: string;
  open?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Select: FunctionComponent<SelectProps> = ({ value, placeholder, label, name, disabled, size, error, open, onArcChange, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return (
    <arc-select ref={ref} value={value} placeholder={placeholder} label={label} name={name} disabled={disabled} size={size} error={error} open={open} {...rest}>
      {children}
    </arc-select>
  );
};
