// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/slider';

export interface SliderProps {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  name?: string;
  disabled?: boolean;
  label?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Slider: FunctionComponent<SliderProps> = ({ value, min, max, step, name, disabled, label, children, ...rest }) => (
  <arc-slider value={value} min={min} max={max} step={step} name={name} disabled={disabled} label={label} {...rest}>
    {children}
  </arc-slider>
);
