// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/theme-toggle';

export interface ThemeToggleProps {
  theme?: string;
  disabled?: boolean;
  iconOnly?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const ThemeToggle: FunctionComponent<ThemeToggleProps> = ({ theme, disabled, iconOnly, onArcChange, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return (
    <arc-theme-toggle ref={ref} theme={theme} disabled={disabled} iconOnly={iconOnly} {...rest}>
      {children}
    </arc-theme-toggle>
  );
};
