// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/time-picker';

export interface TimePickerProps {
  value?: string;
  name?: string;
  min?: string;
  max?: string;
  step?: number;
  format?: string;
  placeholder?: string;
  disabled?: boolean;
  label?: string;
  onArcChange?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const TimePicker: FunctionComponent<TimePickerProps> = ({ value, name, min, max, step, format, placeholder, disabled, label, onArcChange, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return (
    <arc-time-picker ref={ref} value={value} name={name} min={min} max={max} step={step} format={format} placeholder={placeholder} disabled={disabled} label={label} {...rest}>
      {children}
    </arc-time-picker>
  );
};
