// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h } from 'preact';
import { forwardRef } from 'preact/compat';
import { useImperativeHandle, useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/time-picker';
import type { ArcTimePicker } from '@arclux/arc-ui/time-picker';

export interface TimePickerProps {
  required?: boolean;
  readonly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  value?: string;
  name?: string;
  min?: string;
  max?: string;
  step?: 1 | 5 | 15 | 30;
  format?: '12h' | '24h';
  placeholder?: string;
  disabled?: boolean;
  label?: string;
  open?: boolean;
  onArcChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

/** Driven by its methods: checkValidity() and reportValidity(). A ref on it holds the element. */
export const TimePicker = forwardRef<ArcTimePicker, TimePickerProps>(({ required, readonly, size, value, name, min, max, step, format, placeholder, disabled, label, open, onArcChange, ...rest }, forwarded) => {
  const ref = useRef<ArcTimePicker>(null);
  useImperativeHandle(forwarded, () => ref.current as ArcTimePicker, []);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return h('arc-time-picker', { ref, required, readonly, size, value, name, min, max, step, format, placeholder, disabled, label, open, ...rest });
});
