// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/time-picker';

export interface TimePickerProps {
  value?: string;
  name?: string;
  min?: string;
  max?: string;
  step?: number;
  format?: string;
  placeholder?: string;
  disabled?: boolean;
  label?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const TimePicker: FunctionComponent<TimePickerProps> = ({ value, name, min, max, step, format, placeholder, disabled, label, children, ...rest }) => (
  <arc-time-picker value={value} name={name} min={min} max={max} step={step} format={format} placeholder={placeholder} disabled={disabled} label={label} {...rest}>
    {children}
  </arc-time-picker>
);
