// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { h } from 'preact';
import { forwardRef } from 'preact/compat';
import { useImperativeHandle, useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/toggle';
import type { ArcToggle } from '@arclux/arc-ui/toggle';

export interface ToggleProps {
  required?: boolean;
  readonly?: boolean;
  checked?: boolean;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  label?: string;
  name?: string;
  onArcChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

/** Driven by its methods: checkValidity() and reportValidity(). A ref on it holds the element. */
export const Toggle = forwardRef<ArcToggle, ToggleProps>(({ required, readonly, checked, disabled, size, label, name, onArcChange, ...rest }, forwarded) => {
  const ref = useRef<ArcToggle>(null);
  useImperativeHandle(forwarded, () => ref.current as ArcToggle, []);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange]);
  return h('arc-toggle', { ref, required, readonly, checked, disabled, size, label, name, ...rest });
});
