// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface ToggleProps {
  checked?: boolean;
  disabled?: boolean;
  label?: string;
  name?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Toggle: FunctionComponent<ToggleProps> = ({ checked, disabled, label, name, children, ...rest }) => (
  <arc-toggle checked={checked} disabled={disabled} label={label} name={name} {...rest}>
    {children}
  </arc-toggle>
);
