// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcAspectGrid } from '@arclux/arc-ui/aspect-grid';

export interface AspectGridProps {
  columns?: number;
  ratio?: string;
  gap?: 'sm' | 'md' | 'lg';
  className?: string;
  children?: React.ReactNode;
}

export const AspectGrid = createComponent({
  tagName: 'arc-aspect-grid',
  elementClass: ArcAspectGrid,
  react: React,
});
