// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcContainer } from '@arclux/arc-ui';

export interface ContainerProps {
  narrow?: boolean;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  padding?: 'none' | 'sm' | 'lg';
  className?: string;
  children?: React.ReactNode;
}

export const Container = createComponent({
  tagName: 'arc-container',
  elementClass: ArcContainer,
  react: React,
});
