// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/avatar';
import type { ArcAvatar } from '@arclux/arc-ui/avatar';

@Component({
  selector: 'arc-avatar',
  standalone: true,
  template: ``,
})
export class Avatar {
  private readonly _el: ArcAvatar = inject(ElementRef).nativeElement;

  @Input() set src(value: string) {
    this._el.src = value;
  }
  get src(): string {
    return this._el.src;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set shape(value: 'circle' | 'square' | 'rounded') {
    this._el.shape = value;
  }
  get shape(): 'circle' | 'square' | 'rounded' {
    return this._el.shape;
  }

  @Input() set status(value: '' | 'online' | 'offline' | 'busy' | 'away') {
    this._el.status = value;
  }
  get status(): '' | 'online' | 'offline' | 'busy' | 'away' {
    return this._el.status;
  }
}
