// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-code-block',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-code-block [attr.language]="language" [attr.filename]="filename" [attr.code]="code" [attr._copied]="_copied"><ng-content /></arc-code-block>`,
})
export class CodeBlock {
  @Input() language: string = '';
  @Input() filename: string = '';
  @Input() code: string = '';
  @Input() _copied: string = false;
}
