// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-data-table',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-data-table [attr.rows]="rows" [sortable]="sortable" [selectable]="selectable" [attr.sortColumn]="sortColumn" [attr.sortDirection]="sortDirection" [virtual]="virtual" [attr.rowHeight]="rowHeight" [attr._columns]="_columns" [attr._selectedRows]="_selectedRows" [attr._startIndex]="_startIndex" [attr._visibleCount]="_visibleCount" (arc-sort)="arcSort.emit($event)" (arc-select-all)="arcSelectAll.emit($event)" (arc-row-select)="arcRowSelect.emit($event)"><ng-content /></arc-data-table>`,
})
export class DataTable {
  @Input() rows: unknown[] = [];
  @Input() sortable: boolean = false;
  @Input() selectable: boolean = false;
  @Input() sortColumn: string = '';
  @Input() sortDirection: string = 'asc';
  @Input() virtual: boolean = false;
  @Input() rowHeight: number = 40;
  @Input() _columns: string = [];
  @Input() _selectedRows: string = 'new Set()';
  @Input() _startIndex: string = 0;
  @Input() _visibleCount: string = 0;
  @Output() arcSort = new EventEmitter<CustomEvent>();
  @Output() arcSelectAll = new EventEmitter<CustomEvent>();
  @Output() arcRowSelect = new EventEmitter<CustomEvent>();
}
