// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-feature-card',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-feature-card [attr.icon]="icon" [attr.heading]="heading" [attr.description]="description" [attr.href]="href" [attr.action]="action"><ng-content /></arc-feature-card>`,
})
export class FeatureCard {
  @Input() icon: string = '';
  @Input() heading: string = '';
  @Input() description: string = '';
  @Input() href: string = '';
  @Input() action: string = '';
}
