// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-icon-library',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-icon-library><ng-content /></arc-icon-library>`,
})
export class IconLibrary {
}
