// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/marquee';

@Component({
  selector: 'arc-marquee',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-marquee [attr.speed]="speed" [attr.direction]="direction" [attr.gap]="gap"><ng-content /></arc-marquee>`,
})
export class Marquee {
  @Input() speed: number = 40;
  @Input() direction: string = 'left';
  @Input() gap: string = 'var(--space-xl)';
}
