// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcQrCode } from '@arclux/arc-ui/qr-code';

@Component({
  selector: 'arc-qr-code',
  standalone: true,
  template: ``,
})
export class QrCode {
  private readonly _el: ArcQrCode = inject(ElementRef).nativeElement;

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Input() set size(value: number) {
    this._el.size = value;
  }
  get size(): number {
    return this._el.size;
  }

  @Input() set level(value: 'L' | 'M' | 'Q' | 'H') {
    this._el.level = value;
  }
  get level(): 'L' | 'M' | 'Q' | 'H' {
    return this._el.level;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set quietZone(value: number) {
    this._el.quietZone = value;
  }
  get quietZone(): number {
    return this._el.quietZone;
  }

  @Input() set contrast(value: boolean) {
    this._el.contrast = value;
  }
  get contrast(): boolean {
    return this._el.contrast;
  }
}
