// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/scroll-area';
import type { ArcScrollArea } from '@arclux/arc-ui/scroll-area';

@Component({
  selector: 'arc-scroll-area',
  standalone: true,
  template: `<ng-content />`,
})
export class ScrollArea {
  private readonly _el: ArcScrollArea = inject(ElementRef).nativeElement;

  @Input() set maxHeight(value: string) {
    this._el.maxHeight = value;
  }
  get maxHeight(): string {
    return this._el.maxHeight;
  }

  @Input() set orientation(value: 'vertical' | 'horizontal' | 'both') {
    this._el.orientation = value;
  }
  get orientation(): 'vertical' | 'horizontal' | 'both' {
    return this._el.orientation;
  }
}
