// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-scroll-area',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-scroll-area [attr.maxHeight]="maxHeight" [attr.orientation]="orientation"><ng-content /></arc-scroll-area>`,
})
export class ScrollArea {
  @Input() maxHeight: string = '';
  @Input() orientation: 'vertical' | 'horizontal' | 'both' = 'vertical';
}
