// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/spinner';
import type { ArcSpinner } from '@arclux/arc-ui/spinner';

@Component({
  selector: 'arc-spinner',
  standalone: true,
  template: ``,
})
export class Spinner {
  private readonly _el: ArcSpinner = inject(ElementRef).nativeElement;

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set variant(value: 'primary' | 'secondary' | 'white') {
    this._el.variant = value;
  }
  get variant(): 'primary' | 'secondary' | 'white' {
    return this._el.variant;
  }
}
