// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcVirtualList } from '@arclux/arc-ui/virtual-list';

@Component({
  selector: 'arc-virtual-list',
  standalone: true,
  template: `<ng-content />`,
})
export class VirtualList {
  private readonly _el: ArcVirtualList = inject(ElementRef).nativeElement;

  @Input() set items(value: unknown[]) {
    this._el.items = value;
  }
  get items(): unknown[] {
    return this._el.items;
  }

  @Input() set itemHeight(value: number) {
    this._el.itemHeight = value;
  }
  get itemHeight(): number {
    return this._el.itemHeight;
  }

  @Input() set overscan(value: number) {
    this._el.overscan = value;
  }
  get overscan(): number {
    return this._el.overscan;
  }
}
