// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/virtual-list';

@Component({
  selector: 'arc-virtual-list',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-virtual-list [items]="items" [attr.itemHeight]="itemHeight" [attr.overscan]="overscan"><ng-content /></arc-virtual-list>`,
})
export class VirtualList {
  @Input() items: unknown[] = [];
  @Input() itemHeight: number = 40;
  @Input() overscan: number = 5;
}
