// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcMenuItem } from '@arclux/arc-ui';

export interface MenuItemProps {
  shortcut?: string;
  disabled?: boolean;
  icon?: string;
  className?: string;
  children?: React.ReactNode;
}

export const MenuItem = createComponent({
  tagName: 'arc-menu-item',
  elementClass: ArcMenuItem,
  react: React,
});
