import '@arclux/arc-ui/calendar';
interface Props {
    locale?: string;
    firstDayOfWeek?: number;
    value?: string;
    min?: string;
    max?: string;
    month?: number;
    year?: number;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Calendar: import("svelte").Component<Props, {}, "value" | "month" | "year">;
type Calendar = ReturnType<typeof Calendar>;
export default Calendar;
