import '@arclux/arc-ui/color-picker';
interface Props {
    size?: 'sm' | 'md' | 'lg';
    value?: string;
    name?: string;
    presets?: string[];
    disabled?: boolean;
    label?: string;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const ColorPicker: import("svelte").Component<Props, {}, "value">;
type ColorPicker = ReturnType<typeof ColorPicker>;
export default ColorPicker;
