import '@arclux/arc-ui/form';
import type { Snippet } from 'svelte';
interface Props {
    action?: string;
    method?: string;
    novalidate?: boolean;
    loading?: boolean;
    disabled?: boolean;
    errorSummary?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Form: import("svelte").Component<Props, {}, "">;
type Form = ReturnType<typeof Form>;
export default Form;
