import '@arclux/arc-ui/image-cropper';
interface Props {
    src?: string;
    height?: number;
    aspect?: number;
    zoom?: number;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const ImageCropper: import("svelte").Component<Props, {}, "">;
type ImageCropper = ReturnType<typeof ImageCropper>;
export default ImageCropper;
