import '@arclux/arc-ui/inline-edit';
import type { Snippet } from 'svelte';
interface Props {
    value?: string;
    label?: string;
    name?: string;
    placeholder?: string;
    multiline?: boolean;
    disabled?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const InlineEdit: import("svelte").Component<Props, {}, "value">;
type InlineEdit = ReturnType<typeof InlineEdit>;
export default InlineEdit;
