import '@arclux/arc-ui/knob';
interface Props {
    size?: 'sm' | 'md' | 'lg';
    value?: number;
    min?: number;
    max?: number;
    step?: number;
    name?: string;
    disabled?: boolean;
    label?: string;
    detents?: number[] | string;
    format?: Function;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Knob: import("svelte").Component<Props, {}, "value">;
type Knob = ReturnType<typeof Knob>;
export default Knob;
