import '@arclux/arc-ui/pin-input';
interface Props {
    length?: number;
    value?: string;
    name?: string;
    disabled?: boolean;
    mask?: boolean;
    type?: 'number' | 'alphanumeric' | 'text';
    separator?: number;
    label?: string;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const PinInput: import("svelte").Component<Props, {}, "value">;
type PinInput = ReturnType<typeof PinInput>;
export default PinInput;
