import '@arclux/arc-ui/range-slider';
interface Props {
    size?: 'sm' | 'md' | 'lg';
    min?: number;
    max?: number;
    step?: number;
    low?: number;
    high?: number;
    name?: string;
    disabled?: boolean;
    label?: string;
    showValues?: boolean;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const RangeSlider: import("svelte").Component<Props, {}, "low" | "high">;
type RangeSlider = ReturnType<typeof RangeSlider>;
export default RangeSlider;
