import '@arclux/arc-ui/signature-pad';
interface Props {
    value?: string;
    name?: string;
    label?: string;
    disabled?: boolean;
    penColor?: string;
    penWidth?: number;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const SignaturePad: import("svelte").Component<Props, {}, "value">;
type SignaturePad = ReturnType<typeof SignaturePad>;
export default SignaturePad;
