import '@arclux/arc-ui/tag-input';
import type { Snippet } from 'svelte';
interface Props {
    value?: string[];
    suggestions?: string[];
    delimiter?: string;
    maxTags?: number;
    allowCustom?: boolean;
    label?: string;
    placeholder?: string;
    name?: string;
    disabled?: boolean;
    error?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const TagInput: import("svelte").Component<Props, {}, "value">;
type TagInput = ReturnType<typeof TagInput>;
export default TagInput;
