import '@arclux/arc-ui/time-picker';
interface Props {
    value?: string;
    name?: string;
    min?: string;
    max?: string;
    step?: number;
    format?: string;
    placeholder?: string;
    disabled?: boolean;
    label?: string;
    open?: boolean;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const TimePicker: import("svelte").Component<Props, {}, "value">;
type TimePicker = ReturnType<typeof TimePicker>;
export default TimePicker;
