import '@arclux/arc-ui/transfer-list';
import type { Snippet } from 'svelte';
interface Props {
    options?: Array<{
        value: string;
        label: string;
        disabled?: boolean;
    }>;
    value?: string[];
    name?: string;
    disabled?: boolean;
    searchable?: boolean;
    sourceLabel?: string;
    targetLabel?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const TransferList: import("svelte").Component<Props, {}, "value">;
type TransferList = ReturnType<typeof TransferList>;
export default TransferList;
