<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/center';
  import type { Snippet } from 'svelte';

  interface Props {
    maxWidth?: string;
    intrinsic?: boolean;
    text?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { maxWidth = '60ch', intrinsic = false, text = false, children, ...rest }: Props = $props();

  let __el: HTMLElement | undefined = $state();
  $effect(() => {
    const el = __el as unknown as Record<string, unknown> | undefined;
    if (!el) return;
    if (maxWidth !== undefined) el.maxWidth = maxWidth;
  });
</script>

<arc-center {intrinsic} {text} bind:this={__el} {...rest}>
  {@render children?.()}
</arc-center>
