import '@arclux/arc-ui/inset';
import type { Snippet } from 'svelte';
interface Props {
    space?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
    bleed?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Inset: import("svelte").Component<Props, {}, "">;
type Inset = ReturnType<typeof Inset>;
export default Inset;
