import '@arclux/arc-ui/resizable';
import type { Snippet } from 'svelte';
interface Props {
    direction?: 'horizontal' | 'vertical';
    minSize?: number;
    maxSize?: number;
    size?: number;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Resizable: import("svelte").Component<Props, {}, "size">;
type Resizable = ReturnType<typeof Resizable>;
export default Resizable;
