import '@arclux/arc-ui/responsive-switcher';
import type { Snippet } from 'svelte';
interface Props {
    threshold?: string;
    gap?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const ResponsiveSwitcher: import("svelte").Component<Props, {}, "">;
type ResponsiveSwitcher = ReturnType<typeof ResponsiveSwitcher>;
export default ResponsiveSwitcher;
