<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/status-bar';
  import type { Snippet } from 'svelte';

  interface Props {
    position?: 'static' | 'fixed';
    /** <slot name="start"> — put slot="start" on the element inside. */
    start?: Snippet;
    /** <slot name="end"> — put slot="end" on the element inside. */
    end?: Snippet;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { position = 'static', start, end, children, ...rest }: Props = $props();
</script>

<arc-status-bar {position} {...rest}>
  {@render start?.()}
  {@render end?.()}
  {@render children?.()}
</arc-status-bar>
