// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface MenuItemProps {
  shortcut?: string;
  disabled?: boolean;
  icon?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const MenuItem: Component<MenuItemProps> = (props) => {
  const [local, rest] = splitProps(props, ['shortcut', 'disabled', 'icon', 'children']);
  return (
    <arc-menu-item shortcut={local.shortcut} disabled={local.disabled} icon={local.icon} {...rest}>
      {local.children}
    </arc-menu-item>
  );
};
