import '@arclux/arc-ui/drawer';
import type { Snippet } from 'svelte';
interface Props {
    open?: boolean;
    position?: 'left' | 'right';
    heading?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Drawer: import("svelte").Component<Props, {}, "">;
type Drawer = ReturnType<typeof Drawer>;
export default Drawer;
