import '@arclux/arc-ui/nav-item';
import type { Snippet } from 'svelte';
interface Props {
    href?: string;
    active?: boolean;
    variant?: 'default' | 'primary' | 'muted';
    description?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const NavItem: import("svelte").Component<Props, {}, "">;
type NavItem = ReturnType<typeof NavItem>;
export default NavItem;
