import '@arclux/arc-ui/rail';
import type { Snippet } from 'svelte';
interface Props {
    items?: Array<{
        icon: string;
        label: string;
        value: string;
    }>;
    value?: string;
    expanded?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const Rail: import("svelte").Component<Props, {}, "value">;
type Rail = ReturnType<typeof Rail>;
export default Rail;
