import '@arclux/arc-ui/sidebar-section';
import type { Snippet } from 'svelte';
interface Props {
    heading?: string;
    collapsible?: boolean;
    open?: boolean;
    icon?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
}
declare const SidebarSection: import("svelte").Component<Props, {}, "open">;
type SidebarSection = ReturnType<typeof SidebarSection>;
export default SidebarSection;
