<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/anchor-nav';

defineOptions({ name: 'AnchorNav' });

withDefaults(defineProps<{
  orientation?: 'vertical';
  value?: string;
  items?: string;
}>(), {
  orientation: 'horizontal',
  value: '',
  items: () => ([]),
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-anchor-nav
    :orientation="orientation"
    :value="value"
    :items="items"
  >
    <slot />
  </arc-anchor-nav>
</template>
