<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'BottomNav' });

withDefaults(defineProps<{
  items?: string;
  value?: string;
}>(), {
  items: () => ([]),
  value: '',
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-bottom-nav
    :items="items"
    :value="value"
  >
    <slot />
  </arc-bottom-nav>
</template>
