<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/breadcrumb-menu';

defineOptions({ name: 'BreadcrumbMenu' });

const props = withDefaults(defineProps<{
  items?: Array<{label: string, href?: string, siblings?: Array<{label: string, href?: string}>}>;
  label?: string;
}>(), {
  items: () => ([]),
  label: 'Breadcrumb',
});

const emit = defineEmits<{
  'arc-navigate': [event: CustomEvent];
}>();
</script>

<template>
  <arc-breadcrumb-menu
    :items="props.items"
    :label="props.label"
    @arc-navigate="(payload: CustomEvent) => emit('arc-navigate', payload)"
  >
  </arc-breadcrumb-menu>
</template>
