<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Breadcrumb' });

withDefaults(defineProps<{
  separator?: string;
  _items?: string;
}>(), {
  separator: '/',
  _items: () => ([]),
});

defineEmits<{
  'arc-navigate': [event: CustomEvent];
}>();
</script>

<template>
  <arc-breadcrumb
    :separator="separator"
    :_items="_items"
  >
    <slot />
  </arc-breadcrumb>
</template>
