<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/footer';

defineOptions({ name: 'Footer' });

withDefaults(defineProps<{
  compact?: boolean;
  border?: boolean;
  contained?: string;
  align?: 'center';
}>(), {
  compact: false,
  border: true,
  contained: 'null',
  align: 'left',
});
</script>

<template>
  <arc-footer
    :compact="compact"
    :border="border"
    :contained="contained"
    :align="align"
  >
    <slot />
  </arc-footer>
</template>
