<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/navigation-menu';

defineOptions({ name: 'NavigationMenu' });

const props = withDefaults(defineProps<{
  label?: string;
}>(), {
  label: 'Navigation menu',
});

const emit = defineEmits<{
  'arc-mobile-menu-toggle': [event: CustomEvent];
  'arc-navigate': [event: CustomEvent];
}>();
</script>

<template>
  <arc-navigation-menu
    :label="props.label"
    @arc-mobile-menu-toggle="(payload: CustomEvent) => emit('arc-mobile-menu-toggle', payload)"
    @arc-navigate="(payload: CustomEvent) => emit('arc-navigate', payload)"
  >
    <slot />
  </arc-navigation-menu>
</template>
