<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/navigation-menu';

defineOptions({ name: 'NavigationMenu' });


defineEmits<{
  'arc-mobile-menu-toggle': [event: CustomEvent];
}>();
</script>

<template>
  <arc-navigation-menu>
    <slot />
  </arc-navigation-menu>
</template>
