<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/pagination';

defineOptions({ name: 'Pagination' });

const props = defineProps<{
  total?: number;
  current?: number;
  siblings?: number;
  compact?: boolean;
}>();

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-pagination
    :total="props.total"
    :current="props.current"
    :siblings="props.siblings"
    :compact="props.compact"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
  </arc-pagination>
</template>
