<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/pagination';

defineOptions({ name: 'Pagination' });

const props = withDefaults(defineProps<{
  total?: number;
  current?: number;
  siblings?: number;
  compact?: boolean;
}>(), {
  total: 1,
  current: 1,
  siblings: 1,
  compact: false,
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-pagination
    :total="props.total"
    :current="props.current"
    :siblings="props.siblings"
    :compact="props.compact"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
    <slot />
  </arc-pagination>
</template>
