<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/scroll-spy';

defineOptions({ name: 'ScrollSpy' });

withDefaults(defineProps<{
  active?: string;
  offset?: number;
}>(), {
  active: '',
  offset: 80,
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-scroll-spy
    :active="active"
    :offset="offset"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
    <slot />
  </arc-scroll-spy>
</template>
