<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'StepperNav' });

withDefaults(defineProps<{
  steps?: string;
  active?: number;
  linear?: boolean;
}>(), {
  steps: () => ([]),
  active: 0,
  linear: false,
});

defineEmits<{
  'arc-change': [event: CustomEvent];
  'arc-complete': [event: CustomEvent];
}>();
</script>

<template>
  <arc-stepper-nav
    :steps="steps"
    :active="active"
    :linear="linear"
  >
    <slot />
  </arc-stepper-nav>
</template>
