<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/tabs';

defineOptions({ name: 'Tabs' });

const props = defineProps<{
  selected?: number;
  align?: 'start' | 'center' | 'end';
  variant?: 'underline' | 'pills';
  orientation?: 'horizontal' | 'vertical';
}>();

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-tabs
    :selected="props.selected"
    :align="props.align"
    :variant="props.variant"
    :orientation="props.orientation"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
    <slot />
  </arc-tabs>
</template>
