<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/menu-item';

defineOptions({ name: 'MenuItem' });

const props = withDefaults(defineProps<{
  label?: string;
  shortcut?: string;
  disabled?: boolean;
  icon?: string;
  value?: string;
}>(), {
  label: '',
  shortcut: '',
  icon: '',
  value: '',
});
</script>

<template>
  <arc-menu-item
    :label="props.label"
    :shortcut="props.shortcut"
    :disabled="props.disabled"
    :icon="props.icon"
    :value="props.value"
  >
    <slot />
  </arc-menu-item>
</template>
