<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/menu-divider';

defineOptions({ name: 'MenuDivider' });

</script>

<template>
  <arc-menu-divider>
  </arc-menu-divider>
</template>
