<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Option' });

withDefaults(defineProps<{
  value?: string;
  disabled?: boolean;
  selected?: boolean;
}>(), {
  value: '',
  disabled: false,
  selected: false,
});
</script>

<template>
  <arc-option
    :value="value"
    :disabled="disabled"
    :selected="selected"
  >
    <slot />
  </arc-option>
</template>
