<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/menubar';
  import type { Snippet } from 'svelte';

  interface Props {
    items?: unknown[];
    children?: Snippet;
    [key: string]: unknown;
  }

  let { items = [], children, ...rest }: Props = $props();
</script>

<arc-menubar {items} {...rest}>
  {@render children?.()}
</arc-menubar>
