<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/pagination';

  interface Props {
    total?: number;
    current?: number;
    siblings?: number;
    compact?: boolean;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { total, current = $bindable(), siblings, compact, ...rest }: Props = $props();

  // Two-way binding — mirror the event detail back onto the prop, then
  // forward to the consumer's own handler, which {...rest} would otherwise
  // have attached. These are declared after {...rest} below so they win.
  function __onArcChange(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) current = detail.value as number;
    }
    (rest['onarc-change'] as ((e: Event) => void) | undefined)?.(e);
  }
</script>

<arc-pagination {total} {current} {siblings} {compact} {...rest}
  onarc-change={__onArcChange}
>
</arc-pagination>
