<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    threshold?: number;
    smooth?: boolean;
    position?: 'bottom-right' | 'bottom-left';
    offset?: string;
    _visible?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { threshold = 300, smooth = true, position = 'bottom-right', offset = 'var(--space-lg)', _visible = false, children, ...rest }: Props = $props();
</script>

<arc-scroll-to-top {threshold} {smooth} {position} {offset} {_visible} {...rest}>
  {@render children?.()}
</arc-scroll-to-top>
