<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/sidebar-link';
  import type { Snippet } from 'svelte';

  interface Props {
    href?: string;
    active?: boolean;
    level?: number;
    icon?: string;
    external?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { href = '', active, level = 0, icon = '', external, children, ...rest }: Props = $props();
</script>

<arc-sidebar-link {href} {active} {level} {icon} {external} {...rest}>
  {@render children?.()}
</arc-sidebar-link>
