<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/tab';
  import type { Snippet } from 'svelte';

  interface Props {
    label?: string;
    disabled?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { label = '', disabled, children, ...rest }: Props = $props();
</script>

<arc-tab {label} {disabled} {...rest}>
  {@render children?.()}
</arc-tab>
