<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/tabs';
  import type { Snippet } from 'svelte';

  interface Props {
    selected?: number;
    align?: 'start' | 'center' | 'end';
    variant?: 'underline' | 'pills';
    orientation?: 'horizontal' | 'vertical';
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { selected, align, variant, orientation, children, ...rest }: Props = $props();
</script>

<arc-tabs {selected} {align} {variant} {orientation} {...rest}>
  {@render children?.()}
</arc-tabs>
