<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    label?: string;
    icon?: string;
    expanded?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { label = '', icon = '', expanded = false, children, ...rest }: Props = $props();
</script>

<arc-tree-item {label} {icon} {expanded} {...rest}>
  {@render children?.()}
</arc-tree-item>
