// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter } from '@angular/core';
import { ArcCheckbox } from '@arclux/arc-ui/checkbox';

@Component({
  selector: 'arc-checkbox',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '(arc-change)': '_onArcChange($event)',
  },
})
export class Checkbox {
  private readonly _el: ArcCheckbox = inject(ElementRef).nativeElement;

  @Input() set checked(value: boolean) {
    this._el.checked = value;
  }
  get checked(): boolean {
    return this._el.checked;
  }

  @Input() set indeterminate(value: boolean) {
    this._el.indeterminate = value;
  }
  get indeterminate(): boolean {
    return this._el.indeterminate;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Output() checkedChange = new EventEmitter<boolean>();

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('checked' in detail) {
      this.checkedChange.emit(detail.checked as boolean);
    }
  }
}
