// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import '@arclux/arc-ui/checkbox';
import type { ArcCheckbox } from '@arclux/arc-ui/checkbox';

@Component({
  selector: 'arc-checkbox',
  standalone: true,
  template: ``,
  host: {
    '(arc-change)': '_onArcChange($event)',
  },
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => Checkbox), multi: true },
  ],
})
export class Checkbox implements ControlValueAccessor {
  private readonly _el: ArcCheckbox = inject(ElementRef).nativeElement;

  /** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
  get element(): ArcCheckbox {
    return this._el;
  }

  @Input() set required(value: boolean) {
    this._el.required = value;
  }
  get required(): boolean {
    return this._el.required;
  }

  @Input() set readonly(value: boolean) {
    this._el.readonly = value;
  }
  get readonly(): boolean {
    return this._el.readonly;
  }

  @Input() set checked(value: boolean) {
    this._el.checked = value;
  }
  get checked(): boolean {
    return this._el.checked;
  }

  @Input() set indeterminate(value: boolean) {
    this._el.indeterminate = value;
  }
  get indeterminate(): boolean {
    return this._el.indeterminate;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Output() checkedChange = new EventEmitter<boolean>();

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('checked' in detail) {
      this.checkedChange.emit(detail.checked as boolean);
    }
  }

  /* ── ControlValueAccessor ──
     Bound to `checked`, committed on `arc-change`.
     The listener lives in the constructor because the host metadata already
     maps that event to this component’s own @Output. writeValue deliberately
     does not call _onChangeFn: it is the form writing into the element, and
     echoing it back would mark the control dirty on every setValue. */
  private _onChangeFn: (value: boolean) => void = () => {};
  private _onTouchedFn: () => void = () => {};

  constructor() {
    this._el.addEventListener('arc-change', () => {
      this._onChangeFn(this._el.checked);
      this._onTouchedFn();
    });
  }

  writeValue(value: boolean | null | undefined): void {
    const next = value ?? false;
    this._el.checked = next;
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this._onChangeFn = fn;
  }

  registerOnTouched(fn: () => void): void {
    this._onTouchedFn = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this._el.disabled = isDisabled;
  }
}
