// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/combobox';

@Component({
  selector: 'arc-combobox',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-combobox [attr.value]="this.value" [attr.placeholder]="this.placeholder" [attr.label]="this.label" [attr.name]="this.name" [disabled]="this.disabled" (arc-change)="this.onArcChange($event)"><ng-content /></arc-combobox>`,
})
export class Combobox {
  @Input() value: string = '';
  @Input() placeholder: string = '';
  @Input() label: string = '';
  @Input() name: string = '';
  @Input() disabled: boolean = false;
  @Output() arcChange = new EventEmitter<CustomEvent>();
  @Output() valueChange = new EventEmitter<string>();

  onArcChange(event: CustomEvent) {
    this.arcChange.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      const next = detail.value as string;
      this.value = next;
      this.valueChange.emit(next);
    }
  }
}
