// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/copy-button';
import type { ArcCopyButton } from '@arclux/arc-ui/copy-button';

@Component({
  selector: 'arc-copy-button',
  standalone: true,
  template: ``,
})
export class CopyButton {
  private readonly _el: ArcCopyButton = inject(ElementRef).nativeElement;

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }
}
