// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/date-picker';

@Component({
  selector: 'arc-date-picker',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-date-picker [attr.value]="value" [attr.name]="name" [attr.min]="min" [attr.max]="max" [attr.placeholder]="placeholder" [disabled]="disabled" [attr.label]="label" (arc-change)="arcChange.emit($event)"><ng-content /></arc-date-picker>`,
})
export class DatePicker {
  @Input() value: string = '';
  @Input() name: string = '';
  @Input() min: string = '';
  @Input() max: string = '';
  @Input() placeholder: string = 'Select date';
  @Input() disabled: boolean = false;
  @Input() label: string = '';
  @Output() arcChange = new EventEmitter<CustomEvent>();
}
