// Auto-generated by @arclux/prism 3.4.0 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/field-list';
import type { ArcFieldList } from '@arclux/arc-ui/field-list';

@Component({
  selector: 'arc-field-list',
  standalone: true,
  template: `<ng-content />`,
})
export class FieldList {
  private readonly _el: ArcFieldList = inject(ElementRef).nativeElement;

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set addLabel(value: string) {
    this._el.addLabel = value;
  }
  get addLabel(): string {
    return this._el.addLabel;
  }

  @Input() set min(value: number) {
    this._el.min = value;
  }
  get min(): number {
    return this._el.min;
  }

  @Input() set max(value: number) {
    this._el.max = value;
  }
  get max(): number {
    return this._el.max;
  }

  @Input() set readonly(value: boolean) {
    this._el.readonly = value;
  }
  get readonly(): boolean {
    return this._el.readonly;
  }
}
