// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcFileUpload } from '@arclux/arc-ui/file-upload';

@Component({
  selector: 'arc-file-upload',
  standalone: true,
  template: `<ng-content />`,
})
export class FileUpload {
  private readonly _el: ArcFileUpload = inject(ElementRef).nativeElement;

  @Input() set accept(value: string) {
    this._el.accept = value;
  }
  get accept(): string {
    return this._el.accept;
  }

  @Input() set multiple(value: boolean) {
    this._el.multiple = value;
  }
  get multiple(): boolean {
    return this._el.multiple;
  }

  @Input() set maxSize(value: number) {
    this._el.maxSize = value;
  }
  get maxSize(): number {
    return this._el.maxSize;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }
}
