// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/icon-button';

@Component({
  selector: 'arc-icon-button',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-icon-button [attr.name]="this.name" [attr.text]="this.text" [attr.variant]="this.variant" [attr.size]="this.size" [attr.label]="this.label" [attr.href]="this.href" [disabled]="this.disabled" [attr.type]="this.type"><ng-content /></arc-icon-button>`,
})
export class IconButton {
  @Input() name: string = '';
  @Input() text: string = '';
  @Input() variant: 'ghost' | 'secondary' | 'primary' = 'ghost';
  @Input() size: 'xs' | 'sm' | 'md' | 'lg' = 'md';
  @Input() label: string = '';
  @Input() href: string = '';
  @Input() disabled: boolean = false;
  @Input() type: string = 'button';
}
