// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcImageCropper } from '@arclux/arc-ui/image-cropper';

@Component({
  selector: 'arc-image-cropper',
  standalone: true,
  template: ``,
})
export class ImageCropper {
  private readonly _el: ArcImageCropper = inject(ElementRef).nativeElement;

  @Input() set src(value: string) {
    this._el.src = value;
  }
  get src(): string {
    return this._el.src;
  }

  @Input() set height(value: number) {
    this._el.height = value;
  }
  get height(): number {
    return this._el.height;
  }

  @Input() set aspect(value: number) {
    this._el.aspect = value;
  }
  get aspect(): number {
    return this._el.aspect;
  }

  @Input() set zoom(value: number) {
    this._el.zoom = value;
  }
  get zoom(): number {
    return this._el.zoom;
  }
}
