// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import '@arclux/arc-ui/inline-edit';
import type { ArcInlineEdit } from '@arclux/arc-ui/inline-edit';

@Component({
  selector: 'arc-inline-edit',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '(arc-change)': '_onArcChange($event)',
    '(arc-cancel)': '_onArcCancel($event)',
    '(arc-input)': '_onArcInput($event)',
  },
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => InlineEdit), multi: true },
  ],
})
export class InlineEdit implements ControlValueAccessor {
  private readonly _el: ArcInlineEdit = inject(ElementRef).nativeElement;

  @Input() set required(value: boolean) {
    this._el.required = value;
  }
  get required(): boolean {
    return this._el.required;
  }

  @Input() set readonly(value: boolean) {
    this._el.readonly = value;
  }
  get readonly(): boolean {
    return this._el.readonly;
  }

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set placeholder(value: string) {
    this._el.placeholder = value;
  }
  get placeholder(): string {
    return this._el.placeholder;
  }

  @Input() set multiline(value: boolean) {
    this._el.multiline = value;
  }
  get multiline(): boolean {
    return this._el.multiline;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Output() valueChange = new EventEmitter<string>();

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }

  _onArcCancel(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }

  _onArcInput(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }

  /* ── ControlValueAccessor ──
     Bound to `value`, committed on `arc-change`.
     The listener lives in the constructor because the host metadata already
     maps that event to this component’s own @Output. writeValue deliberately
     does not call _onChangeFn: it is the form writing into the element, and
     echoing it back would mark the control dirty on every setValue. */
  private _onChangeFn: (value: string) => void = () => {};
  private _onTouchedFn: () => void = () => {};

  constructor() {
    this._el.addEventListener('arc-change', () => {
      this._onChangeFn(this._el.value);
      this._onTouchedFn();
    });
  }

  writeValue(value: string | null | undefined): void {
    const next = value ?? '';
    this._el.value = next;
  }

  registerOnChange(fn: (value: string) => void): void {
    this._onChangeFn = fn;
  }

  registerOnTouched(fn: () => void): void {
    this._onTouchedFn = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this._el.disabled = isDisabled;
  }
}
