// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input as NgInput, Output, EventEmitter, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import '@arclux/arc-ui/input';
import type { ArcInput } from '@arclux/arc-ui/input';

@Component({
  selector: 'arc-input',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '(arc-input)': '_onArcInput($event)',
    '(arc-change)': '_onArcChange($event)',
  },
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => Input), multi: true },
  ],
})
export class Input implements ControlValueAccessor {
  private readonly _el: ArcInput = inject(ElementRef).nativeElement;

  /** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
  get element(): ArcInput {
    return this._el;
  }

  @NgInput() set required(value: boolean) {
    this._el.required = value;
  }
  get required(): boolean {
    return this._el.required;
  }

  @NgInput() set readonly(value: boolean) {
    this._el.readonly = value;
  }
  get readonly(): boolean {
    return this._el.readonly;
  }

  @NgInput() set type(value: 'text' | 'email' | 'tel' | 'url' | 'password') {
    this._el.type = value;
  }
  get type(): 'text' | 'email' | 'tel' | 'url' | 'password' {
    return this._el.type;
  }

  @NgInput() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @NgInput() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @NgInput() set placeholder(value: string) {
    this._el.placeholder = value;
  }
  get placeholder(): string {
    return this._el.placeholder;
  }

  @NgInput() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @NgInput() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @NgInput() set error(value: string) {
    this._el.error = value;
  }
  get error(): string {
    return this._el.error;
  }

  @NgInput() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @NgInput() set multiline(value: boolean) {
    this._el.multiline = value;
  }
  get multiline(): boolean {
    return this._el.multiline;
  }

  @NgInput() set rows(value: number) {
    this._el.rows = value;
  }
  get rows(): number {
    return this._el.rows;
  }

  @Output() valueChange = new EventEmitter<string>();

  _onArcInput(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }

  /* ── ControlValueAccessor ──
     Bound to `value`, committed on `arc-change`.
     The listener lives in the constructor because the host metadata already
     maps that event to this component’s own @Output. writeValue deliberately
     does not call _onChangeFn: it is the form writing into the element, and
     echoing it back would mark the control dirty on every setValue. */
  private _onChangeFn: (value: string) => void = () => {};
  private _onTouchedFn: () => void = () => {};

  constructor() {
    this._el.addEventListener('arc-change', () => {
      this._onChangeFn(this._el.value);
      this._onTouchedFn();
    });
  }

  writeValue(value: string | null | undefined): void {
    const next = value ?? '';
    this._el.value = next;
  }

  registerOnChange(fn: (value: string) => void): void {
    this._onChangeFn = fn;
  }

  registerOnTouched(fn: () => void): void {
    this._onTouchedFn = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this._el.disabled = isDisabled;
  }
}
