// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/knob';
import type { ArcKnob } from '@arclux/arc-ui/knob';

@Component({
  selector: 'arc-knob',
  standalone: true,
  template: ``,
  host: {
    '(arc-input)': '_onArcInput($event)',
    '(arc-change)': '_onArcChange($event)',
  },
})
export class Knob {
  private readonly _el: ArcKnob = inject(ElementRef).nativeElement;

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set value(value: number) {
    this._el.value = value;
  }
  get value(): number {
    return this._el.value;
  }

  @Input() set min(value: number) {
    this._el.min = value;
  }
  get min(): number {
    return this._el.min;
  }

  @Input() set max(value: number) {
    this._el.max = value;
  }
  get max(): number {
    return this._el.max;
  }

  @Input() set step(value: number) {
    this._el.step = value;
  }
  get step(): number {
    return this._el.step;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set detents(value: number[]) {
    this._el.detents = value;
  }
  get detents(): number[] {
    return this._el.detents;
  }

  @Input() set format(value: Function) {
    this._el.format = value;
  }
  get format(): Function {
    return this._el.format;
  }

  @Output() valueChange = new EventEmitter<number>();

  _onArcInput(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as number);
    }
  }

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as number);
    }
  }
}
