// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/masked-input';
import type { ArcMaskedInput } from '@arclux/arc-ui/masked-input';

@Component({
  selector: 'arc-masked-input',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '(arc-input)': '_onArcInput($event)',
    '(arc-change)': '_onArcChange($event)',
  },
})
export class MaskedInput {
  private readonly _el: ArcMaskedInput = inject(ElementRef).nativeElement;

  @Input() set mask(value: string) {
    this._el.mask = value;
  }
  get mask(): string {
    return this._el.mask;
  }

  @Input() set value(value: string) {
    this._el.value = value;
  }
  get value(): string {
    return this._el.value;
  }

  @Input() set placeholderChar(value: string) {
    this._el.placeholderChar = value;
  }
  get placeholderChar(): string {
    return this._el.placeholderChar;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Input() set required(value: boolean) {
    this._el.required = value;
  }
  get required(): boolean {
    return this._el.required;
  }

  @Input() set autocomplete(value: string) {
    this._el.autocomplete = value;
  }
  get autocomplete(): string {
    return this._el.autocomplete;
  }

  @Input() set error(value: string) {
    this._el.error = value;
  }
  get error(): string {
    return this._el.error;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Output() valueChange = new EventEmitter<string>();

  _onArcInput(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as string);
    }
  }
}
