// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/pin-input';

@Component({
  selector: 'arc-pin-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-pin-input [attr.length]="this.length" [attr.value]="this.value" [attr.name]="this.name" [disabled]="this.disabled" [mask]="this.mask" [attr.type]="this.type" [attr.separator]="this.separator" [attr.label]="this.label" (arc-change)="this.onArcChange($event)" (arc-complete)="this.onArcComplete($event)"><ng-content /></arc-pin-input>`,
})
export class PinInput {
  @Input() length: number = 4;
  @Input() value: string = '';
  @Input() name: string = '';
  @Input() disabled: boolean = false;
  @Input() mask: boolean = false;
  @Input() type: 'number' | 'alphanumeric' | 'text' = 'number';
  @Input() separator: number = 0;
  @Input() label: string = '';
  @Output() arcChange = new EventEmitter<CustomEvent>();
  @Output() arcComplete = new EventEmitter<CustomEvent>();
  @Output() valueChange = new EventEmitter<string>();

  onArcChange(event: CustomEvent) {
    this.arcChange.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      const next = detail.value as string;
      this.value = next;
      this.valueChange.emit(next);
    }
  }

  onArcComplete(event: CustomEvent) {
    this.arcComplete.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      const next = detail.value as string;
      this.value = next;
      this.valueChange.emit(next);
    }
  }
}
