// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/range-slider';

@Component({
  selector: 'arc-range-slider',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-range-slider [attr.min]="this.min" [attr.max]="this.max" [attr.step]="this.step" [attr.low]="this.low" [attr.high]="this.high" [attr.name]="this.name" [disabled]="this.disabled" [attr.label]="this.label" [showValues]="this.showValues" (arc-input)="this.onArcInput($event)" (arc-change)="this.onArcChange($event)"></arc-range-slider>`,
})
export class RangeSlider {
  @Input() min: number = 0;
  @Input() max: number = 100;
  @Input() step: number = 1;
  @Input() low: number = 0;
  @Input() high: number = 100;
  @Input() name: string = '';
  @Input() disabled: boolean = false;
  @Input() label: string = '';
  @Input() showValues: boolean = true;
  @Output() arcInput = new EventEmitter<CustomEvent>();
  @Output() arcChange = new EventEmitter<CustomEvent>();
  @Output() lowChange = new EventEmitter<number>();
  @Output() highChange = new EventEmitter<number>();

  onArcInput(event: CustomEvent) {
    this.arcInput.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('high' in detail) {
      const next = detail.high as number;
      this.high = next;
      this.highChange.emit(next);
    }
    if ('low' in detail) {
      const next = detail.low as number;
      this.low = next;
      this.lowChange.emit(next);
    }
  }

  onArcChange(event: CustomEvent) {
    this.arcChange.emit(event);
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('high' in detail) {
      const next = detail.high as number;
      this.high = next;
      this.highChange.emit(next);
    }
    if ('low' in detail) {
      const next = detail.low as number;
      this.low = next;
      this.lowChange.emit(next);
    }
  }
}
