// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import '@arclux/arc-ui/rating';
import type { ArcRating } from '@arclux/arc-ui/rating';

@Component({
  selector: 'arc-rating',
  standalone: true,
  template: ``,
  host: {
    '(arc-change)': '_onArcChange($event)',
  },
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => Rating), multi: true },
  ],
})
export class Rating implements ControlValueAccessor {
  private readonly _el: ArcRating = inject(ElementRef).nativeElement;

  /** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
  get element(): ArcRating {
    return this._el;
  }

  @Input() set required(value: boolean) {
    this._el.required = value;
  }
  get required(): boolean {
    return this._el.required;
  }

  @Input() set readonly(value: boolean) {
    this._el.readonly = value;
  }
  get readonly(): boolean {
    return this._el.readonly;
  }

  @Input() set size(value: 'sm' | 'md' | 'lg') {
    this._el.size = value;
  }
  get size(): 'sm' | 'md' | 'lg' {
    return this._el.size;
  }

  @Input() set value(value: number) {
    this._el.value = value;
  }
  get value(): number {
    return this._el.value;
  }

  @Input() set max(value: number) {
    this._el.max = value;
  }
  get max(): number {
    return this._el.max;
  }

  @Input() set name(value: string) {
    this._el.name = value;
  }
  get name(): string {
    return this._el.name;
  }

  @Input() set label(value: string) {
    this._el.label = value;
  }
  get label(): string {
    return this._el.label;
  }

  @Input() set disabled(value: boolean) {
    this._el.disabled = value;
  }
  get disabled(): boolean {
    return this._el.disabled;
  }

  @Output() valueChange = new EventEmitter<number>();

  _onArcChange(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('value' in detail) {
      this.valueChange.emit(detail.value as number);
    }
  }

  /* ── ControlValueAccessor ──
     Bound to `value`, committed on `arc-change`.
     The listener lives in the constructor because the host metadata already
     maps that event to this component’s own @Output. writeValue deliberately
     does not call _onChangeFn: it is the form writing into the element, and
     echoing it back would mark the control dirty on every setValue. */
  private _onChangeFn: (value: number) => void = () => {};
  private _onTouchedFn: () => void = () => {};

  constructor() {
    this._el.addEventListener('arc-change', () => {
      this._onChangeFn(this._el.value);
      this._onTouchedFn();
    });
  }

  writeValue(value: number | null | undefined): void {
    const next = value ?? 0;
    this._el.value = next;
  }

  registerOnChange(fn: (value: number) => void): void {
    this._onChangeFn = fn;
  }

  registerOnTouched(fn: () => void): void {
    this._onTouchedFn = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this._el.disabled = isDisabled;
  }
}
