// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/command-palette';

@Component({
  selector: 'arc-command-palette',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-command-palette [open]="this.open" [attr.placeholder]="this.placeholder" (arc-select)="this.arcSelect.emit($event)" (arc-close)="this.arcClose.emit($event)"><ng-content /></arc-command-palette>`,
})
export class CommandPalette {
  @Input() open: boolean = false;
  @Input() placeholder: string = 'Type a command...';
  @Output() arcSelect = new EventEmitter<CustomEvent>();
  @Output() arcClose = new EventEmitter<CustomEvent>();
}
