// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject } from '@angular/core';
import { ArcConnectionStatus } from '@arclux/arc-ui/connection-status';

@Component({
  selector: 'arc-connection-status',
  standalone: true,
  template: ``,
})
export class ConnectionStatus {
  private readonly _el: ArcConnectionStatus = inject(ElementRef).nativeElement;
}
