// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/dropdown-menu';
import type { ArcDropdownMenu } from '@arclux/arc-ui/dropdown-menu';

@Component({
  selector: 'arc-dropdown-menu',
  standalone: true,
  template: `<ng-content />`,
})
export class DropdownMenu {
  private readonly _el: ArcDropdownMenu = inject(ElementRef).nativeElement;

  @Input() set open(value: boolean) {
    this._el.open = value;
  }
  get open(): boolean {
    return this._el.open;
  }
}
