// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-popover',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-popover [open]="open" [attr.position]="position" [attr.trigger]="trigger" (arc-close)="arcClose.emit($event)"><ng-content /></arc-popover>`,
})
export class Popover {
  @Input() open: boolean = false;
  @Input() position: string = 'bottom';
  @Input() trigger: string = '';
  @Output() arcClose = new EventEmitter<CustomEvent>();
}
