// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcToast } from '@arclux/arc-ui/toast';

@Component({
  selector: 'arc-toast',
  standalone: true,
  template: `<ng-content />`,
})
export class Toast {
  private readonly _el: ArcToast = inject(ElementRef).nativeElement;

  @Input() set position(value: 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center') {
    this._el.position = value;
  }
  get position(): 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center' {
    return this._el.position;
  }

  @Input() set duration(value: number) {
    this._el.duration = value;
  }
  get duration(): number {
    return this._el.duration;
  }
}
