// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/tooltip';
import type { ArcTooltip } from '@arclux/arc-ui/tooltip';

@Component({
  selector: 'arc-tooltip',
  standalone: true,
  template: `<ng-content />`,
})
export class Tooltip {
  private readonly _el: ArcTooltip = inject(ElementRef).nativeElement;

  @Input() set content(value: string) {
    this._el.content = value;
  }
  get content(): string {
    return this._el.content;
  }

  @Input() set position(value: 'top' | 'bottom' | 'left' | 'right') {
    this._el.position = value;
  }
  get position(): 'top' | 'bottom' | 'left' | 'right' {
    return this._el.position;
  }

  @Input() set delay(value: number) {
    this._el.delay = value;
  }
  get delay(): number {
    return this._el.delay;
  }
}
