// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/aspect-ratio';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-aspect-ratio': Record<string, unknown>;
    }
  }
}

export interface AspectRatioProps {
  ratio?: string;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const AspectRatio: Component<AspectRatioProps> = (props) => {
  const [local, rest] = splitProps(props, ['ratio', 'children']);
  return (
    <arc-aspect-ratio ratio={local.ratio} {...rest}>
      {local.children}
    </arc-aspect-ratio>
  );
};
