// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface AvatarProps {
  src?: string;
  name?: string;
  size?: 'sm' | 'md' | 'lg';
  shape?: 'square' | 'rounded';
  status?: 'online' | 'offline' | 'busy' | 'away';
  _imgState?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Avatar: Component<AvatarProps> = (props) => {
  const [local, rest] = splitProps(props, ['src', 'name', 'size', 'shape', 'status', '_imgState', 'children']);
  return (
    <arc-avatar src={local.src} name={local.name} size={local.size} shape={local.shape} status={local.status} _imgState={local._imgState} {...rest}>
      {local.children}
    </arc-avatar>
  );
};
