// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/avatar';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-avatar': Record<string, unknown>;
    }
  }
}

export interface AvatarProps {
  src?: string;
  name?: string;
  size?: 'sm' | 'md' | 'lg';
  shape?: 'circle' | 'square' | 'rounded';
  status?: 'online' | 'offline' | 'busy' | 'away';
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Avatar: Component<AvatarProps> = (props) => {
  const [local, rest] = splitProps(props, ['src', 'name', 'size', 'shape', 'status']);
  return (
    <arc-avatar src={local.src} name={local.name} size={local.size} shape={local.shape} status={local.status} {...rest}>
    </arc-avatar>
  );
};
