// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface CalloutProps {
  variant?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Callout: Component<CalloutProps> = (props) => {
  const [local, rest] = splitProps(props, ['variant', 'children']);
  return (
    <arc-callout variant={local.variant} {...rest}>
      {local.children}
    </arc-callout>
  );
};
