// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/cta-banner';

export interface CtaBannerProps {
  eyebrow?: string;
  headline?: string;
  nogradient?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const CtaBanner: Component<CtaBannerProps> = (props) => {
  const [local, rest] = splitProps(props, ['eyebrow', 'headline', 'nogradient', 'children']);
  return (
    <arc-cta-banner eyebrow={local.eyebrow} headline={local.headline} nogradient={local.nogradient} {...rest}>
      {local.children}
    </arc-cta-banner>
  );
};
