// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/hotspot';
import type { ArcHotspot } from '@arclux/arc-ui/hotspot';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-hotspot': Record<string, unknown>;
    }
  }
}

export interface HotspotProps {
  x?: number;
  y?: number;
  label?: string;
  open?: boolean;
  onArcOpen?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  children?: JSX.Element;
  /** The element, for the methods it is driven by: close(). */
  ref?: ArcHotspot | ((el: ArcHotspot) => void);
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Hotspot: Component<HotspotProps> = (props) => {
  const [local, rest] = splitProps(props, ['x', 'y', 'label', 'open', 'onArcOpen', 'onArcClose', 'children', 'ref']);
  return (
    <arc-hotspot x={local.x} y={local.y} label={local.label} open={local.open} on:arc-open={local.onArcOpen} on:arc-close={local.onArcClose} ref={(el: ArcHotspot) => { if (typeof local.ref === 'function') local.ref(el); }} {...rest}>
      {local.children}
    </arc-hotspot>
  );
};
