// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface IconLibraryProps {
  children?: JSX.Element;
  [key: string]: unknown;
}

export const IconLibrary: Component<IconLibraryProps> = (props) => {
  const [local, rest] = splitProps(props, ['children']);
  return (
    <arc-icon-library {...rest}>
      {local.children}
    </arc-icon-library>
  );
};
