// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/image';

export interface ImageProps {
  src?: string;
  alt?: string;
  aspect?: '1/1' | '4/3' | '16/9' | '21/9' | '3/4' | '9/16';
  fit?: 'contain' | 'fill' | 'none' | 'scale-down';
  loading?: string;
  fallback?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Image: Component<ImageProps> = (props) => {
  const [local, rest] = splitProps(props, ['src', 'alt', 'aspect', 'fit', 'loading', 'fallback', 'children']);
  return (
    <arc-image src={local.src} alt={local.alt} aspect={local.aspect} fit={local.fit} loading={local.loading} fallback={local.fallback} {...rest}>
      {local.children}
    </arc-image>
  );
};
