// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/image';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-image': Record<string, unknown>;
    }
  }
}

export interface ImageProps {
  src?: string;
  alt?: string;
  aspect?: '' | '1/1' | '4/3' | '16/9' | '21/9' | '3/4' | '9/16';
  fit?: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down';
  loading?: 'lazy' | 'eager';
  fallback?: string;
  onArcLoad?: (e: CustomEvent) => void;
  onArcError?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Image: Component<ImageProps> = (props) => {
  const [local, rest] = splitProps(props, ['src', 'alt', 'aspect', 'fit', 'loading', 'fallback', 'onArcLoad', 'onArcError']);
  return (
    <arc-image src={local.src} alt={local.alt} aspect={local.aspect} fit={local.fit} loading={local.loading} fallback={local.fallback} on:arc-load={local.onArcLoad} on:arc-error={local.onArcError} {...rest}>
    </arc-image>
  );
};
