// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/qr-code';

export interface QrCodeProps {
  value?: string;
  size?: number;
  level?: string;
  label?: string;
  quietZone?: number;
  contrast?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const QrCode: Component<QrCodeProps> = (props) => {
  const [local, rest] = splitProps(props, ['value', 'size', 'level', 'label', 'quietZone', 'contrast', 'children']);
  return (
    <arc-qr-code value={local.value} size={local.size} level={local.level} label={local.label} quietZone={local.quietZone} contrast={local.contrast} {...rest}>
      {local.children}
    </arc-qr-code>
  );
};
