// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface ScrollAreaProps {
  maxHeight?: string;
  orientation?: 'vertical' | 'horizontal' | 'both';
  children?: JSX.Element;
  [key: string]: unknown;
}

export const ScrollArea: Component<ScrollAreaProps> = (props) => {
  const [local, rest] = splitProps(props, ['maxHeight', 'orientation', 'children']);
  return (
    <arc-scroll-area maxHeight={local.maxHeight} orientation={local.orientation} {...rest}>
      {local.children}
    </arc-scroll-area>
  );
};
