// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface SeparatorProps {
  orientation?: 'vertical';
  label?: string;
  variant?: 'dashed' | 'dotted' | 'fade';
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Separator: Component<SeparatorProps> = (props) => {
  const [local, rest] = splitProps(props, ['orientation', 'label', 'variant', 'children']);
  return (
    <arc-separator orientation={local.orientation} label={local.label} variant={local.variant} {...rest}>
      {local.children}
    </arc-separator>
  );
};
