// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/spinner';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-spinner': Record<string, unknown>;
    }
  }
}

export interface SpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  variant?: 'primary' | 'secondary' | 'white';
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Spinner: Component<SpinnerProps> = (props) => {
  const [local, rest] = splitProps(props, ['size', 'variant', 'children']);
  return (
    <arc-spinner size={local.size} variant={local.variant} {...rest}>
      {local.children}
    </arc-spinner>
  );
};
