<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'SegmentedControl' });

withDefaults(defineProps<{
  value?: string;
  disabled?: boolean;
  _options?: string;
}>(), {
  value: '',
  disabled: false,
  _options: () => ([]),
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-segmented-control
    :value="value"
    :disabled="disabled"
    :_options="_options"
  >
    <slot />
  </arc-segmented-control>
</template>
