<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Tooltip' });

withDefaults(defineProps<{
  content?: string;
  position?: 'top' | 'bottom' | 'left' | 'right';
  delay?: number;
  _visible?: string;
}>(), {
  content: '',
  position: 'top',
  delay: 200,
  _visible: false,
});
</script>

<template>
  <arc-tooltip
    :content="content"
    :position="position"
    :delay="delay"
    :_visible="_visible"
  >
    <slot />
  </arc-tooltip>
</template>
