<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/chip';
  import type { Snippet } from 'svelte';

  interface Props {
    selected?: boolean;
    disabled?: boolean;
    value?: string;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { selected = $bindable(), disabled, value = '', children, ...rest }: Props = $props();

  // Two-way binding — mirror the event detail back onto the prop, then
  // forward to the consumer's own handler, which {...rest} would otherwise
  // have attached. These are declared after {...rest} below so they win.
  function __onArcChange(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('selected' in detail) selected = detail.selected as boolean;
    }
    (rest['onarc-change'] as ((e: Event) => void) | undefined)?.(e);
  }
</script>

<arc-chip {selected} {disabled} {value} {...rest}
  onarc-change={__onArcChange}
>
  {@render children?.()}
</arc-chip>
