<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/color-picker';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: string;
    name?: string;
    presets?: unknown[];
    disabled?: boolean;
    label?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = '#4d7ef7', name = '', presets = [], disabled = false, label = '', children, ...rest }: Props = $props();
</script>

<arc-color-picker {value} {name} {presets} {disabled} {label} {...rest}>
  {@render children?.()}
</arc-color-picker>
