<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/copy-button';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: string;
    disabled?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = '', disabled = false, children, ...rest }: Props = $props();
</script>

<arc-copy-button {value} {disabled} {...rest}>
  {@render children?.()}
</arc-copy-button>
