<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    legend?: string;
    description?: string;
    disabled?: boolean;
    error?: string;
    variant?: 'card';
    _hasLegend?: string;
    _hasActions?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { legend = '', description = '', disabled = false, error = '', variant = 'default', _hasLegend = false, _hasActions = false, children, ...rest }: Props = $props();
</script>

<arc-fieldset {legend} {description} {disabled} {error} {variant} {_hasLegend} {_hasActions} {...rest}>
  {@render children?.()}
</arc-fieldset>
