<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/file-upload';
  import type { Snippet } from 'svelte';

  interface Props {
    accept?: string;
    multiple?: boolean;
    maxSize?: number;
    disabled?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { accept = '', multiple = false, maxSize = 0, disabled = false, children, ...rest }: Props = $props();
</script>

<arc-file-upload {accept} {multiple} {maxSize} {disabled} {...rest}>
  {@render children?.()}
</arc-file-upload>
