<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/label';
  import type { Snippet } from 'svelte';

  interface Props {
    for?: string;
    required?: boolean;
    size?: 'sm' | 'md' | 'lg';
    disabled?: boolean;
    /** <slot name="tooltip"> — put slot="tooltip" on the element inside. */
    tooltip?: Snippet;
    /** <slot name="description"> — put slot="description" on the element inside. */
    description?: Snippet;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { for: forProp = '', required, size, disabled, tooltip, description, children, ...rest }: Props = $props();
</script>

<arc-label for={forProp} {required} {size} {disabled} {...rest}>
  {@render tooltip?.()}
  {@render description?.()}
  {@render children?.()}
</arc-label>
