<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/radio-group';
  import type { Snippet } from 'svelte';

  interface Props {
    required?: boolean;
    readonly?: boolean;
    value?: string;
    name?: string;
    disabled?: boolean;
    size?: 'sm' | 'md' | 'lg';
    orientation?: 'vertical' | 'horizontal';
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { required, readonly, value = $bindable(''), name = '', disabled = false, size, orientation, children, ...rest }: Props = $props();

  // Two-way binding — mirror the event detail back onto the prop, then
  // forward to the consumer's own handler, which {...rest} would otherwise
  // have attached. These are declared after {...rest} below so they win.
  function __onArcChange(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) value = detail.value as string;
    }
    (rest['onarc-change'] as ((e: Event) => void) | undefined)?.(e);
  }
</script>

<arc-radio-group {required} {readonly} {value} {name} {disabled} {size} {orientation} {...rest}
  onarc-change={__onArcChange}
>
  {@render children?.()}
</arc-radio-group>
