<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/range-slider';
  import type { Snippet } from 'svelte';

  interface Props {
    min?: number;
    max?: number;
    step?: number;
    low?: number;
    high?: number;
    name?: string;
    disabled?: boolean;
    label?: string;
    showValues?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { min = 0, max = 100, step = 1, low = 0, high = 100, name = '', disabled = false, label = '', showValues = true, children, ...rest }: Props = $props();
</script>

<arc-range-slider {min} {max} {step} {low} {high} {name} {disabled} {label} {showValues} {...rest}>
  {@render children?.()}
</arc-range-slider>
