<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    min?: number;
    max?: number;
    step?: number;
    low?: number;
    high?: number;
    disabled?: boolean;
    label?: string;
    showValues?: boolean;
    _dragging?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { min = 0, max = 100, step = 1, low = 0, high = 100, disabled = false, label = '', showValues = true, _dragging = null, children, ...rest }: Props = $props();
</script>

<arc-range-slider {min} {max} {step} {low} {high} {disabled} {label} {showValues} {_dragging} {...rest}>
  {@render children?.()}
</arc-range-slider>
