<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/search';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: string;
    placeholder?: string;
    label?: string;
    disabled?: boolean;
    loading?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = $bindable(''), placeholder = 'Search...', label = '', disabled = false, loading = false, children, ...rest }: Props = $props();

  // Two-way binding — mirror the event detail back onto the prop, then
  // forward to the consumer's own handler, which {...rest} would otherwise
  // have attached. These are declared after {...rest} below so they win.
  function __onArcInput(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) value = detail.value as string;
    }
    (rest['onarc-input'] as ((e: Event) => void) | undefined)?.(e);
  }
  function __onArcChange(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) value = detail.value as string;
    }
    (rest['onarc-change'] as ((e: Event) => void) | undefined)?.(e);
  }
  function __onArcSelect(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) value = detail.value as string;
    }
    (rest['onarc-select'] as ((e: Event) => void) | undefined)?.(e);
  }
</script>

<arc-search {value} {placeholder} {label} {disabled} {loading} {...rest}
  onarc-input={__onArcInput}
  onarc-change={__onArcChange}
  onarc-select={__onArcSelect}
>
  {@render children?.()}
</arc-search>
