<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/search';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: string;
    placeholder?: string;
    label?: string;
    disabled?: boolean;
    loading?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = '', placeholder = 'Search...', label = '', disabled = false, loading = false, children, ...rest }: Props = $props();
</script>

<arc-search {value} {placeholder} {label} {disabled} {loading} {...rest}>
  {@render children?.()}
</arc-search>
