<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/select';
  import type { ArcSelect } from '@arclux/arc-ui/select';
  import type { Snippet } from 'svelte';

  interface Props {
    required?: boolean;
    readonly?: boolean;
    value?: string;
    placeholder?: string;
    label?: string;
    name?: string;
    disabled?: boolean;
    size?: 'sm' | 'md' | 'lg';
    error?: string;
    open?: boolean;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { required, readonly, value = $bindable(''), placeholder = 'Select...', label = '', name = '', disabled = false, size, error = '', open = false, children, ...rest }: Props = $props();

  let __el: HTMLElement | undefined = $state();

  /**
   * The element, for the methods it is driven by: checkValidity() and reportValidity().
   *
   * A function rather than a property: an instance `export` in runes mode
   * captures its binding once, which would be before the element exists.
   * Reach it with `bind:this` on this component, then `element()`.
   */
  export function element(): ArcSelect | undefined {
    return __el as ArcSelect | undefined;
  }

  // Two-way binding — mirror the event detail back onto the prop, then
  // forward to the consumer's own handler, which {...rest} would otherwise
  // have attached. These are declared after {...rest} below so they win.
  function __onArcChange(e: Event) {
    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;
    if (detail) {
      if ('value' in detail) value = detail.value as string;
    }
    (rest['onarc-change'] as ((e: Event) => void) | undefined)?.(e);
  }
</script>

<arc-select {required} {readonly} {value} {placeholder} {label} {name} {disabled} {size} {error} {open} bind:this={__el} {...rest}
  onarc-change={__onArcChange}
>
  {@render children?.()}
</arc-select>
