<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/transfer-list';
  import type { Snippet } from 'svelte';

  interface Props {
    options?: unknown[];
    value?: unknown[];
    name?: string;
    disabled?: boolean;
    searchable?: boolean;
    sourceLabel?: string;
    targetLabel?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { options = [], value = [], name = '', disabled = false, searchable = false, sourceLabel = 'Available', targetLabel = 'Selected', children, ...rest }: Props = $props();
</script>

<arc-transfer-list {options} {value} {name} {disabled} {searchable} {sourceLabel} {targetLabel} {...rest}>
  {@render children?.()}
</arc-transfer-list>
