<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    open?: boolean;
    position?: 'left' | 'right';
    heading?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { open = false, position = 'left', heading = '', children, ...rest }: Props = $props();
</script>

<arc-drawer {open} {position} {heading} {...rest}>
  {@render children?.()}
</arc-drawer>
