<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    value?: unknown[];
    placeholder?: string;
    label?: string;
    disabled?: boolean;
    _query?: string;
    _open?: string;
    _activeIndex?: string;
    _options?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { value = [], placeholder = '', label = '', disabled = false, _query = '', _open = false, _activeIndex = -1, _options = [], children, ...rest }: Props = $props();
</script>

<arc-multi-select {value} {placeholder} {label} {disabled} {_query} {_open} {_activeIndex} {_options} {...rest}>
  {@render children?.()}
</arc-multi-select>
