// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject } from '@angular/core';
import { ArcMenuDivider } from '@arclux/arc-ui/menu-divider';

@Component({
  selector: 'arc-menu-divider',
  standalone: true,
  template: `<ng-content />`,
})
export class MenuDivider {
  private readonly _el: ArcMenuDivider = inject(ElementRef).nativeElement;
}
