// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-option',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-option [attr.value]="value" [disabled]="disabled" [selected]="selected"><ng-content /></arc-option>`,
})
export class Option {
  @Input() value: string = '';
  @Input() disabled: boolean = false;
  @Input() selected: boolean = false;
}
