// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcAvatarGroup } from '@arclux/arc-ui';

export interface AvatarGroupProps {
  max?: number;
  overlap?: 'sm' | 'lg';
  className?: string;
  children?: React.ReactNode;
}

export const AvatarGroup = createComponent({
  tagName: 'arc-avatar-group',
  elementClass: ArcAvatarGroup,
  react: React,
});
