// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcBadge } from '@arclux/arc-ui';

export interface BadgeProps {
  variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info';
  className?: string;
  children?: React.ReactNode;
}

export const Badge = createComponent({
  tagName: 'arc-badge',
  elementClass: ArcBadge,
  react: React,
});
