// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcCard } from '@arclux/arc-ui/card';

export interface CardProps {
  href?: string;
  padding?: 'none' | 'sm' | 'md' | 'lg';
  interactive?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export const Card = createComponent({
  tagName: 'arc-card',
  elementClass: ArcCard,
  react: React,
});
