// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcColumn } from '@arclux/arc-ui';

export interface ColumnProps {
  key?: string;
  label?: string;
  sortable?: boolean;
  width?: string;
  className?: string;
  children?: React.ReactNode;
}

export const Column = createComponent({
  tagName: 'arc-column',
  elementClass: ArcColumn,
  react: React,
});
