// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcColumn } from '@arclux/arc-ui/column';

export interface ColumnProps {
  field?: string;
  key?: string;
  label?: string;
  sortable?: boolean;
  width?: string;
  className?: string;
  children?: React.ReactNode;
}

export const Column = createComponent({
  tagName: 'arc-column',
  elementClass: ArcColumn,
  react: React,
});
