// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcSeparator } from '@arclux/arc-ui/separator';

export interface SeparatorProps {
  orientation?: 'horizontal' | 'vertical';
  label?: string;
  variant?: 'line' | 'dashed' | 'dotted' | 'fade';
  className?: string;
}

export const Separator = createComponent({
  tagName: 'arc-separator',
  elementClass: ArcSeparator,
  react: React,
});
