// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcTimelineItem } from '@arclux/arc-ui';

export interface TimelineItemProps {
  heading?: string;
  date?: string;
  className?: string;
  children?: React.ReactNode;
}

export const TimelineItem = createComponent({
  tagName: 'arc-timeline-item',
  elementClass: ArcTimelineItem,
  react: React,
});
