<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/animated-number';

defineOptions({ name: 'AnimatedNumber' });

const props = withDefaults(defineProps<{
  value?: number;
  duration?: number;
  format?: 'number' | 'currency' | 'percent';
  prefix?: string;
  suffix?: string;
  decimals?: number;
  locale?: string;
}>(), {
  value: 0,
  prefix: '',
  suffix: '',
  decimals: 0,
  locale: 'en-US',
});
</script>

<template>
  <arc-animated-number
    :value="props.value"
    :duration="props.duration"
    :format="props.format"
    :prefix="props.prefix"
    :suffix="props.suffix"
    :decimals="props.decimals"
    :locale="props.locale"
  >
  </arc-animated-number>
</template>
