<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/bar-list';

defineOptions({ name: 'BarList' });

const props = withDefaults(defineProps<{
  items?: unknown[];
  max?: number;
  limit?: number;
  unsorted?: boolean;
  unit?: string;
  label?: string;
}>(), {
  unit: '',
  label: '',
});
</script>

<template>
  <arc-bar-list
    :items="props.items"
    :max="props.max"
    :limit="props.limit"
    :unsorted="props.unsorted"
    :unit="props.unit"
    :label="props.label"
  >
  </arc-bar-list>
</template>
