<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/comparison-column';

defineOptions({ name: 'ComparisonColumn' });

const props = withDefaults(defineProps<{
  heading?: string;
  highlight?: boolean;
  values?: string[];
}>(), {
  heading: '',
});
</script>

<template>
  <arc-comparison-column
    :heading="props.heading"
    :highlight="props.highlight"
    :values="props.values"
  >
  </arc-comparison-column>
</template>
