<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/data-table';

defineOptions({ name: 'DataTable' });

withDefaults(defineProps<{
  rows?: unknown[];
  sortable?: boolean;
  selectable?: boolean;
  sortColumn?: string;
  sortDirection?: string;
  virtual?: boolean;
  rowHeight?: number;
}>(), {
  rows: () => ([]),
  sortable: false,
  selectable: false,
  sortColumn: '',
  sortDirection: 'asc',
  virtual: false,
  rowHeight: 40,
});

const emit = defineEmits<{
  'arc-sort': [event: CustomEvent];
  'arc-select-all': [event: CustomEvent];
  'arc-row-select': [event: CustomEvent];
}>();
</script>

<template>
  <arc-data-table
    :rows="rows"
    :sortable="sortable"
    :selectable="selectable"
    :sortColumn="sortColumn"
    :sortDirection="sortDirection"
    :virtual="virtual"
    :rowHeight="rowHeight"
    @arc-sort="(payload: CustomEvent) => emit('arc-sort', payload)"
    @arc-select-all="(payload: CustomEvent) => emit('arc-select-all', payload)"
    @arc-row-select="(payload: CustomEvent) => emit('arc-row-select', payload)"
  >
    <slot />
  </arc-data-table>
</template>
