<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/data-grid';

defineOptions({ name: 'DataGrid' });

withDefaults(defineProps<{
  columns?: unknown[];
  rows?: unknown[];
  sort?: unknown[];
  manualSort?: boolean;
  selectable?: boolean;
  virtual?: boolean;
  rowHeight?: number;
}>(), {
  columns: () => ([]),
  rows: () => ([]),
  sort: () => ([]),
  manualSort: false,
  selectable: false,
  virtual: false,
  rowHeight: 40,
});

const emit = defineEmits<{
  'arc-sort': [event: CustomEvent];
  'arc-selection-change': [event: CustomEvent];
  'arc-cell-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-data-grid
    :columns="columns"
    :rows="rows"
    :sort="sort"
    :manualSort="manualSort"
    :selectable="selectable"
    :virtual="virtual"
    :rowHeight="rowHeight"
    @arc-sort="(payload: CustomEvent) => emit('arc-sort', payload)"
    @arc-selection-change="(payload: CustomEvent) => emit('arc-selection-change', payload)"
    @arc-cell-change="(payload: CustomEvent) => emit('arc-cell-change', payload)"
  >
    <slot />
  </arc-data-grid>
</template>
