<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/key-value';

defineOptions({ name: 'KeyValue' });

withDefaults(defineProps<{
  layout?: 'horizontal' | 'stacked';
  dividers?: boolean;
}>(), {
  layout: 'horizontal',
  dividers: true,
});
</script>

<template>
  <arc-key-value
    :layout="layout"
    :dividers="dividers"
  >
    <slot />
  </arc-key-value>
</template>
