<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/list-item';

defineOptions({ name: 'ListItem' });

withDefaults(defineProps<{
  value?: string;
  selected?: boolean;
  disabled?: boolean;
  href?: string;
}>(), {
  value: '',
  selected: false,
  disabled: false,
  href: '',
});

const emit = defineEmits<{
  'arc-item-select': [event: CustomEvent];
}>();
</script>

<template>
  <arc-list-item
    :value="value"
    :selected="selected"
    :disabled="disabled"
    :href="href"
    @arc-item-select="(payload: CustomEvent) => emit('arc-item-select', payload)"
  >
    <slot />
  </arc-list-item>
</template>
