<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/meter';

defineOptions({ name: 'Meter' });

const props = withDefaults(defineProps<{
  value?: number;
  min?: number;
  max?: number;
  low?: number;
  high?: number;
  optimum?: number;
  label?: string;
}>(), {
  label: '',
});
</script>

<template>
  <arc-meter
    :value="props.value"
    :min="props.min"
    :max="props.max"
    :low="props.low"
    :high="props.high"
    :optimum="props.optimum"
    :label="props.label"
  >
  </arc-meter>
</template>
