<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/sparkline';

defineOptions({ name: 'Sparkline' });

const props = withDefaults(defineProps<{
  data?: string;
  type?: 'line' | 'bar';
  color?: string;
  width?: number;
  height?: number;
  fill?: boolean;
}>(), {
  data: '',
  type: 'line',
  color: '',
  width: 120,
  height: 32,
  fill: false,
});
</script>

<template>
  <arc-sparkline
    :data="props.data"
    :type="props.type"
    :color="props.color"
    :width="props.width"
    :height="props.height"
    :fill="props.fill"
  >
    <slot />
  </arc-sparkline>
</template>
