<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Stat' });

withDefaults(defineProps<{
  value?: string;
  label?: string;
  trend?: 'up' | 'down' | 'neutral';
  change?: string;
}>(), {
  value: '',
  label: '',
  trend: '',
  change: '',
});
</script>

<template>
  <arc-stat
    :value="value"
    :label="label"
    :trend="trend"
    :change="change"
  >
    <slot />
  </arc-stat>
</template>
