<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/table';

defineOptions({ name: 'Table' });

const props = withDefaults(defineProps<{
  columns?: string[];
  rows?: string[][];
  striped?: boolean;
  compact?: boolean;
}>(), {
  columns: () => ([]),
  rows: () => ([]),
  striped: false,
  compact: false,
});
</script>

<template>
  <arc-table
    :columns="props.columns"
    :rows="props.rows"
    :striped="props.striped"
    :compact="props.compact"
  >
    <slot />
  </arc-table>
</template>
