<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/tag';

defineOptions({ name: 'Tag' });

const props = withDefaults(defineProps<{
  variant?: 'default' | 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  removable?: boolean;
  disabled?: boolean;
  color?: string;
}>(), {
  variant: 'default',
  size: 'md',
  removable: false,
  disabled: false,
  color: '',
});

const emit = defineEmits<{
  'arc-remove': [event: CustomEvent];
}>();
</script>

<template>
  <arc-tag
    :variant="props.variant"
    :size="props.size"
    :removable="props.removable"
    :disabled="props.disabled"
    :color="props.color"
    @arc-remove="(payload: CustomEvent) => emit('arc-remove', payload)"
  >
    <slot />
  </arc-tag>
</template>
