// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent } from '@lit/react';
import { ArcBlockquote } from '@arclux/arc-ui/blockquote';

export interface BlockquoteProps {
  cite?: string;
  variant?: 'accent';
  className?: string;
  children?: React.ReactNode;
}

export const Blockquote = createComponent({
  tagName: 'arc-blockquote',
  elementClass: ArcBlockquote,
  react: React,
});
