// Auto-generated by @arclux/prism 3.2.0 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcCodeBlock } from '@arclux/arc-ui/code-block';

export interface CodeBlockProps {
  language?: string;
  label?: string;
  filename?: string;
  code?: string;
  variant?: 'default' | 'window' | 'basic';
  prompt?: string;
  lineNumbers?: boolean;
  highlight?: string;
  diff?: boolean;
  wrap?: boolean;
  maxLines?: number;
  className?: string;
  onArcToggle?: (e: CustomEvent) => void;
}

export const CodeBlock = createComponent({
  tagName: 'arc-code-block',
  elementClass: ArcCodeBlock,
  react: React,
  events: {
    onArcToggle: 'arc-toggle' as EventName<CustomEvent>,
  },
});
