// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcCodeBlock } from '@arclux/arc-ui/code-block';

export interface CodeBlockProps {
  language?: string;
  filename?: string;
  code?: string;
  variant?: 'window' | 'basic';
  className?: string;
  children?: React.ReactNode;
}

export const CodeBlock = createComponent({
  tagName: 'arc-code-block',
  elementClass: ArcCodeBlock,
  react: React,
});
