// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcTerminal } from '@arclux/arc-ui/terminal';

export interface TerminalProps {
  lines?: unknown[];
  prompt?: string;
  title?: string;
  speed?: number;
  autoplay?: boolean;
  loop?: boolean;
  className?: string;
  onArcComplete?: (e: CustomEvent) => void;
}

export const Terminal = createComponent({
  tagName: 'arc-terminal',
  elementClass: ArcTerminal,
  react: React,
  events: {
    onArcComplete: 'arc-complete' as EventName<CustomEvent>,
  },
});
