<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/checkbox';

defineOptions({ name: 'Checkbox' });

const props = withDefaults(defineProps<{
  checked?: boolean;
  indeterminate?: boolean;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  label?: string;
  name?: string;
  value?: string;
}>(), {
  checked: false,
  indeterminate: false,
  disabled: false,
  size: 'md',
  label: '',
  name: '',
  value: '',
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
  'update:checked': [value: boolean];
}>();

function onArcChange(payload: CustomEvent) {
  emit('arc-change', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('checked' in detail) emit('update:checked', detail.checked as boolean);
  }
}
</script>

<template>
  <arc-checkbox
    :checked="props.checked"
    :indeterminate="props.indeterminate"
    :disabled="props.disabled"
    :size="props.size"
    :label="props.label"
    :name="props.name"
    :value="props.value"
    @arc-change="onArcChange"
  >
    <slot />
  </arc-checkbox>
</template>
