<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/chip';

defineOptions({ name: 'Chip' });

withDefaults(defineProps<{
  selected?: boolean;
  disabled?: boolean;
  value?: string;
}>(), {
  selected: false,
  disabled: false,
  value: '',
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-chip
    :selected="selected"
    :disabled="disabled"
    :value="value"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
    <slot />
  </arc-chip>
</template>
