<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/chip';

defineOptions({ name: 'Chip' });

const props = withDefaults(defineProps<{
  selected?: boolean;
  disabled?: boolean;
  value?: string;
}>(), {
  selected: false,
  disabled: false,
  value: '',
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
  'update:selected': [value: boolean];
}>();

function onArcChange(payload: CustomEvent) {
  emit('arc-change', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('selected' in detail) emit('update:selected', detail.selected as boolean);
  }
}
</script>

<template>
  <arc-chip
    :selected="props.selected"
    :disabled="props.disabled"
    :value="props.value"
    @arc-change="onArcChange"
  >
    <slot />
  </arc-chip>
</template>
