<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/color-picker';

defineOptions({ name: 'ColorPicker' });

withDefaults(defineProps<{
  value?: string;
  name?: string;
  presets?: unknown[];
  disabled?: boolean;
  label?: string;
}>(), {
  value: '#4d7ef7',
  name: '',
  presets: () => ([]),
  disabled: false,
  label: '',
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-color-picker
    :value="value"
    :name="name"
    :presets="presets"
    :disabled="disabled"
    :label="label"
  >
    <slot />
  </arc-color-picker>
</template>
