<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/combobox';
import { ref } from 'vue';
import type { ArcCombobox } from '@arclux/arc-ui/combobox';

defineOptions({ name: 'Combobox' });

const props = withDefaults(defineProps<{
  required?: boolean;
  readonly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  value?: string;
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
}>(), {
  value: '',
  placeholder: '',
  label: '',
  name: '',
  disabled: false,
});

const emit = defineEmits<{
  'arc-input': [event: CustomEvent];
  'arc-change': [event: CustomEvent];
  'update:value': [value: string];
}>();

function onArcInput(payload: CustomEvent) {
  emit('arc-input', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('value' in detail) emit('update:value', detail.value as string);
  }
}
function onArcChange(payload: CustomEvent) {
  emit('arc-change', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('value' in detail) emit('update:value', detail.value as string);
  }
}

const __el = ref<ArcCombobox | null>(null);
/** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
defineExpose({ element: __el });
</script>

<template>
  <arc-combobox
    :required="props.required"
    :readonly="props.readonly"
    :size="props.size"
    :value="props.value"
    :placeholder="props.placeholder"
    :label="props.label"
    :name="props.name"
    :disabled="props.disabled"
    @arc-input="onArcInput"
    @arc-change="onArcChange"
    ref="__el"
  >
    <slot />
  </arc-combobox>
</template>
