<!-- Auto-generated by @arclux/prism 3.2.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/copy-button';

defineOptions({ name: 'CopyButton' });

const props = withDefaults(defineProps<{
  value?: string;
  disabled?: boolean;
  iconOnly?: boolean;
  label?: string;
}>(), {
  value: '',
  disabled: false,
  iconOnly: false,
  label: '',
});

const emit = defineEmits<{
  'arc-copy': [event: CustomEvent];
}>();
</script>

<template>
  <arc-copy-button
    :value="props.value"
    :disabled="props.disabled"
    :iconOnly="props.iconOnly"
    :label="props.label"
    @arc-copy="(payload: CustomEvent) => emit('arc-copy', payload)"
  >
  </arc-copy-button>
</template>
