<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/date-picker';

defineOptions({ name: 'DatePicker' });

withDefaults(defineProps<{
  value?: string;
  name?: string;
  min?: string;
  max?: string;
  placeholder?: string;
  disabled?: boolean;
  label?: string;
}>(), {
  value: '',
  name: '',
  min: '',
  max: '',
  placeholder: 'Select date',
  disabled: false,
  label: '',
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-date-picker
    :value="value"
    :name="name"
    :min="min"
    :max="max"
    :placeholder="placeholder"
    :disabled="disabled"
    :label="label"
  >
    <slot />
  </arc-date-picker>
</template>
