<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'FileUpload' });

withDefaults(defineProps<{
  accept?: string;
  multiple?: boolean;
  maxSize?: number;
  disabled?: boolean;
  _files?: string;
  _dragOver?: string;
  _error?: string;
}>(), {
  accept: '',
  multiple: false,
  maxSize: 0,
  disabled: false,
  _files: () => ([]),
  _dragOver: false,
  _error: '',
});

defineEmits<{
  'arc-change': [event: CustomEvent];
  'arc-remove': [event: CustomEvent];
}>();
</script>

<template>
  <arc-file-upload
    :accept="accept"
    :multiple="multiple"
    :maxSize="maxSize"
    :disabled="disabled"
    :_files="_files"
    :_dragOver="_dragOver"
    :_error="_error"
  >
    <slot />
  </arc-file-upload>
</template>
