<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/file-upload';

defineOptions({ name: 'FileUpload' });

withDefaults(defineProps<{
  accept?: string;
  multiple?: boolean;
  maxSize?: number;
  disabled?: boolean;
}>(), {
  accept: '',
  multiple: false,
  maxSize: 0,
  disabled: false,
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
  'arc-remove': [event: CustomEvent];
}>();
</script>

<template>
  <arc-file-upload
    :accept="accept"
    :multiple="multiple"
    :maxSize="maxSize"
    :disabled="disabled"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
    @arc-remove="(payload: CustomEvent) => emit('arc-remove', payload)"
  >
    <slot />
  </arc-file-upload>
</template>
