<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'Form' });

withDefaults(defineProps<{
  action?: string;
  method?: string;
  novalidate?: boolean;
}>(), {
  action: '',
  method: '',
  novalidate: false,
});

defineEmits<{
  'arc-invalid': [event: CustomEvent];
  'arc-submit': [event: CustomEvent];
}>();
</script>

<template>
  <arc-form
    :action="action"
    :method="method"
    :novalidate="novalidate"
  >
    <slot />
  </arc-form>
</template>
