<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/icon-button';

defineOptions({ name: 'IconButton' });

const props = withDefaults(defineProps<{
  name?: string;
  text?: string;
  variant?: 'ghost' | 'secondary' | 'primary';
  size?: 'xs' | 'sm' | 'md' | 'lg';
  label?: string;
  href?: string;
  disabled?: boolean;
  type?: string;
}>(), {
  name: '',
  text: '',
  label: '',
  href: '',
  type: 'button',
});
</script>

<template>
  <arc-icon-button
    :name="props.name"
    :text="props.text"
    :variant="props.variant"
    :size="props.size"
    :label="props.label"
    :href="props.href"
    :disabled="props.disabled"
    :type="props.type"
  >
    <slot />
  </arc-icon-button>
</template>
