<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/number-input';
import { ref } from 'vue';
import type { ArcNumberInput } from '@arclux/arc-ui/number-input';

defineOptions({ name: 'NumberInput' });

const props = withDefaults(defineProps<{
  required?: boolean;
  readonly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  label?: string;
  name?: string;
  disabled?: boolean;
}>(), {
  value: 0,
  step: 1,
  label: '',
  name: '',
  disabled: false,
});

const emit = defineEmits<{
  'arc-input': [event: CustomEvent];
  'arc-change': [event: CustomEvent];
  'update:value': [value: number];
}>();

function onArcInput(payload: CustomEvent) {
  emit('arc-input', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('value' in detail) emit('update:value', detail.value as number);
  }
}
function onArcChange(payload: CustomEvent) {
  emit('arc-change', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('value' in detail) emit('update:value', detail.value as number);
  }
}

const __el = ref<ArcNumberInput | null>(null);
/** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
defineExpose({ element: __el });
</script>

<template>
  <arc-number-input
    :required="props.required"
    :readonly="props.readonly"
    :size="props.size"
    :value="props.value"
    :min="props.min"
    :max="props.max"
    :step="props.step"
    :label="props.label"
    :name="props.name"
    :disabled="props.disabled"
    @arc-input="onArcInput"
    @arc-change="onArcChange"
    ref="__el"
  >
  </arc-number-input>
</template>
