<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/pin-input';

defineOptions({ name: 'PinInput' });

withDefaults(defineProps<{
  length?: number;
  value?: string;
  name?: string;
  disabled?: boolean;
  mask?: boolean;
  type?: string;
  separator?: number;
  label?: string;
}>(), {
  length: 4,
  value: '',
  name: '',
  disabled: false,
  mask: false,
  type: 'number',
  separator: 0,
  label: '',
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
  'arc-complete': [event: CustomEvent];
}>();
</script>

<template>
  <arc-pin-input
    :length="length"
    :value="value"
    :name="name"
    :disabled="disabled"
    :mask="mask"
    :type="type"
    :separator="separator"
    :label="label"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
    @arc-complete="(payload: CustomEvent) => emit('arc-complete', payload)"
  >
    <slot />
  </arc-pin-input>
</template>
