<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/radio';

defineOptions({ name: 'Radio' });

const props = withDefaults(defineProps<{
  value?: string;
  disabled?: boolean;
}>(), {
  value: '',
  disabled: false,
});
</script>

<template>
  <arc-radio
    :value="props.value"
    :disabled="props.disabled"
  >
    <slot />
  </arc-radio>
</template>
