<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/segmented-control';
import { ref } from 'vue';
import type { ArcSegmentedControl } from '@arclux/arc-ui/segmented-control';

defineOptions({ name: 'SegmentedControl' });

const props = withDefaults(defineProps<{
  required?: boolean;
  readonly?: boolean;
  value?: string;
  name?: string;
  disabled?: boolean;
}>(), {
  value: '',
  name: '',
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
  'update:value': [value: string];
}>();

function onArcChange(payload: CustomEvent) {
  emit('arc-change', payload);
  const detail = payload.detail as Record<string, unknown> | null;
  if (detail) {
    if ('value' in detail) emit('update:value', detail.value as string);
  }
}

const __el = ref<ArcSegmentedControl | null>(null);
/** The element, for the methods it is driven by: checkValidity() and reportValidity(). */
defineExpose({ element: __el });
</script>

<template>
  <arc-segmented-control
    :required="props.required"
    :readonly="props.readonly"
    :value="props.value"
    :name="props.name"
    :disabled="props.disabled"
    @arc-change="onArcChange"
    ref="__el"
  >
    <slot />
  </arc-segmented-control>
</template>
