<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/select';

defineOptions({ name: 'Select' });

withDefaults(defineProps<{
  value?: string;
  placeholder?: string;
  label?: string;
  name?: string;
  disabled?: boolean;
  size?: 'sm' | 'lg';
  error?: string;
  open?: boolean;
}>(), {
  value: '',
  placeholder: 'Select...',
  label: '',
  name: '',
  disabled: false,
  size: 'md',
  error: '',
  open: false,
});

defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-select
    :value="value"
    :placeholder="placeholder"
    :label="label"
    :name="name"
    :disabled="disabled"
    :size="size"
    :error="error"
    :open="open"
  >
    <slot />
  </arc-select>
</template>
