<!-- Auto-generated by @arclux/prism 3.1.1 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/sortable-list';

defineOptions({ name: 'SortableList' });

const props = defineProps<{
  disabled?: boolean;
}>();

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-sortable-list
    :disabled="props.disabled"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
    <slot />
  </arc-sortable-list>
</template>
