<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/theme-toggle';

defineOptions({ name: 'ThemeToggle' });

const props = withDefaults(defineProps<{
  theme?: 'dark' | 'light' | 'auto';
  disabled?: boolean;
  iconOnly?: boolean;
  size?: 'xs' | 'sm' | 'md' | 'lg';
}>(), {
  theme: 'auto',
  disabled: false,
  iconOnly: false,
  size: 'md',
});

const emit = defineEmits<{
  'arc-change': [event: CustomEvent];
}>();
</script>

<template>
  <arc-theme-toggle
    :theme="props.theme"
    :disabled="props.disabled"
    :iconOnly="props.iconOnly"
    :size="props.size"
    @arc-change="(payload: CustomEvent) => emit('arc-change', payload)"
  >
  </arc-theme-toggle>
</template>
