// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface SparklineProps {
  data?: string;
  type?: string;
  color?: string;
  width?: number;
  height?: number;
  fill?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Sparkline: Component<SparklineProps> = (props) => {
  const [local, rest] = splitProps(props, ['data', 'type', 'color', 'width', 'height', 'fill', 'children']);
  return (
    <arc-sparkline data={local.data} type={local.type} color={local.color} width={local.width} height={local.height} fill={local.fill} {...rest}>
      {local.children}
    </arc-sparkline>
  );
};
