// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/stepper';

export interface StepperProps {
  active?: number;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Stepper: Component<StepperProps> = (props) => {
  const [local, rest] = splitProps(props, ['active', 'children']);
  return (
    <arc-stepper active={local.active} {...rest}>
      {local.children}
    </arc-stepper>
  );
};
