// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/table';

export interface TableProps {
  columns?: string[];
  rows?: string[][];
  striped?: boolean;
  compact?: boolean;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Table: Component<TableProps> = (props) => {
  const [local, rest] = splitProps(props, ['columns', 'rows', 'striped', 'compact']);
  return (
    <arc-table columns={local.columns} rows={local.rows} striped={local.striped} compact={local.compact} {...rest}>
    </arc-table>
  );
};
