// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/timeline';

export interface TimelineProps {
  headingLevel?: number;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Timeline: Component<TimelineProps> = (props) => {
  const [local, rest] = splitProps(props, ['headingLevel', 'children']);
  return (
    <arc-timeline headingLevel={local.headingLevel} {...rest}>
      {local.children}
    </arc-timeline>
  );
};
