// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface TimelineProps {
  _items?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Timeline: Component<TimelineProps> = (props) => {
  const [local, rest] = splitProps(props, ['_items', 'children']);
  return (
    <arc-timeline _items={local._items} {...rest}>
      {local.children}
    </arc-timeline>
  );
};
