// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/waveform';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-waveform': Record<string, unknown>;
    }
  }
}

export interface WaveformProps {
  peaks?: unknown[];
  position?: number;
  duration?: number;
  interactive?: boolean;
  variant?: 'bars' | 'mirror';
  label?: string;
  onArcInput?: (e: CustomEvent) => void;
  onArcChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Waveform: Component<WaveformProps> = (props) => {
  const [local, rest] = splitProps(props, ['peaks', 'position', 'duration', 'interactive', 'variant', 'label', 'onArcInput', 'onArcChange']);
  return (
    <arc-waveform peaks={local.peaks} position={local.position} duration={local.duration} interactive={local.interactive} variant={local.variant} label={local.label} on:arc-input={local.onArcInput} on:arc-change={local.onArcChange} {...rest}>
    </arc-waveform>
  );
};
