// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/gradient-text';
import type { ArcGradientText } from '@arclux/arc-ui/gradient-text';

@Component({
  selector: 'arc-gradient-text',
  standalone: true,
  template: `<ng-content />`,
})
export class GradientText {
  private readonly _el: ArcGradientText = inject(ElementRef).nativeElement;

  @Input() set variant(value: 'accent' | 'display' | 'sunset' | 'ocean' | 'custom') {
    this._el.variant = value;
  }
  get variant(): 'accent' | 'display' | 'sunset' | 'ocean' | 'custom' {
    return this._el.variant;
  }

  @Input() set gradient(value: string) {
    this._el.gradient = value;
  }
  get gradient(): string {
    return this._el.gradient;
  }

  @Input() set animated(value: boolean) {
    this._el.animated = value;
  }
  get animated(): boolean {
    return this._el.animated;
  }
}
