// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import '@arclux/arc-ui/highlight';
import type { ArcHighlight } from '@arclux/arc-ui/highlight';

@Component({
  selector: 'arc-highlight',
  standalone: true,
  template: ``,
})
export class Highlight {
  private readonly _el: ArcHighlight = inject(ElementRef).nativeElement;

  @Input() set text(value: string) {
    this._el.text = value;
  }
  get text(): string {
    return this._el.text;
  }

  @Input() set query(value: string) {
    this._el.query = value;
  }
  get query(): string {
    return this._el.query;
  }

  @Input() set caseSensitive(value: boolean) {
    this._el.caseSensitive = value;
  }
  get caseSensitive(): boolean {
    return this._el.caseSensitive;
  }
}
