// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui/highlight';

@Component({
  selector: 'arc-highlight',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-highlight [attr.text]="this.text" [attr.query]="this.query" [caseSensitive]="this.caseSensitive"></arc-highlight>`,
})
export class Highlight {
  @Input() text: string = '';
  @Input() query: string = '';
  @Input() caseSensitive: boolean = false;
}
