// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-kbd',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-kbd><ng-content /></arc-kbd>`,
})
export class Kbd {
}
