// Auto-generated by @arclux/prism — do not edit manually

import { Component, ElementRef, inject, Input } from '@angular/core';
import { ArcMarkdown } from '@arclux/arc-ui/markdown';

@Component({
  selector: 'arc-markdown',
  standalone: true,
  template: `<ng-content />`,
})
export class Markdown {
  private readonly _el: ArcMarkdown = inject(ElementRef).nativeElement;

  @Input() set content(value: string) {
    this._el.content = value;
  }
  get content(): string {
    return this._el.content;
  }
}
