// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import '@arclux/arc-ui';

@Component({
  selector: 'arc-number-format',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-number-format [attr.value]="value" [attr.type]="type" [attr.locale]="locale" [attr.currency]="currency" [attr.decimals]="decimals" [attr.notation]="notation"><ng-content /></arc-number-format>`,
})
export class NumberFormat {
  @Input() value: number = 0;
  @Input() type: string = 'number';
  @Input() locale: string = 'en-US';
  @Input() currency: string = 'USD';
  @Input() decimals: number = 'undefined';
  @Input() notation: string = 'standard';
}
