// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { Component, ElementRef, inject, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/truncate';
import type { ArcTruncate } from '@arclux/arc-ui/truncate';

@Component({
  selector: 'arc-truncate',
  standalone: true,
  template: `<ng-content />`,
  host: {
    '(arc-toggle)': '_onArcToggle($event)',
  },
})
export class Truncate {
  private readonly _el: ArcTruncate = inject(ElementRef).nativeElement;

  @Input() set lines(value: number) {
    this._el.lines = value;
  }
  get lines(): number {
    return this._el.lines;
  }

  @Input() set expanded(value: boolean) {
    this._el.expanded = value;
  }
  get expanded(): boolean {
    return this._el.expanded;
  }

  @Output() expandedChange = new EventEmitter<boolean>();

  _onArcToggle(event: CustomEvent) {
    const detail = event.detail as Record<string, unknown> | null;
    if (!detail) return;
    if ('expanded' in detail) {
      this.expandedChange.emit(detail.expanded as boolean);
    }
  }
}
