// Auto-generated by @arclux/prism — do not edit manually

import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from '@angular/core';
import '@arclux/arc-ui/typewriter';

@Component({
  selector: 'arc-typewriter',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<arc-typewriter [attr.text]="this.text" [attr.speed]="this.speed" [attr.delay]="this.delay" [cursor]="this.cursor" [loop]="this.loop" [nowrap]="this.nowrap" [attr.pauseEnd]="this.pauseEnd" (arc-complete)="this.arcComplete.emit($event)"><ng-content /></arc-typewriter>`,
})
export class Typewriter {
  @Input() text: string = '';
  @Input() speed: number = 50;
  @Input() delay: number = 0;
  @Input() cursor: boolean = true;
  @Input() loop: boolean = false;
  @Input() nowrap: boolean = false;
  @Input() pauseEnd: number = 2000;
  @Output() arcComplete = new EventEmitter<CustomEvent>();
}
