<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    src?: string;
    name?: string;
    size?: 'sm' | 'md' | 'lg';
    children?: Snippet;
    [key: string]: unknown;
  }

  let { src = '', name = '', size = 'md', children, ...rest }: Props = $props();
</script>

<arc-avatar {src} {name} {size} {...rest}>
  {@render children?.()}
</arc-avatar>
