<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    src?: string;
    name?: string;
    size?: 'sm' | 'md' | 'lg';
    shape?: 'square' | 'rounded';
    status?: 'online' | 'offline' | 'busy' | 'away';
    children?: Snippet;
    [key: string]: unknown;
  }

  let { src = '', name = '', size = 'md', shape = 'circle', status = '', children, ...rest }: Props = $props();
</script>

<arc-avatar {src} {name} {size} {shape} {status} {...rest}>
  {@render children?.()}
</arc-avatar>
