<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: string;
    dismissible?: boolean;
    _dismissed?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { variant = 'info', dismissible = false, _dismissed = false, children, ...rest }: Props = $props();
</script>

<arc-callout {variant} {dismissible} {_dismissed} {...rest}>
  {@render children?.()}
</arc-callout>
