<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: 'subtle' | 'glow' | 'line-white' | 'line-primary' | 'line-gradient';
    align?: 'left' | 'right';
    vertical?: boolean;
    label?: string;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { variant = 'subtle', align, vertical = false, label = '', children, ...rest }: Props = $props();
</script>

<arc-divider {variant} {align} {vertical} {label} {...rest}>
  {@render children?.()}
</arc-divider>
