<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui';
  import type { Snippet } from 'svelte';

  interface Props {
    threshold?: number;
    loading?: boolean;
    finished?: boolean;
    disabled?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  }

  let { threshold = 200, loading = false, finished = false, disabled = false, children, ...rest }: Props = $props();
</script>

<arc-infinite-scroll {threshold} {loading} {finished} {disabled} {...rest}>
  {@render children?.()}
</arc-infinite-scroll>
