<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script lang="ts">
  import '@arclux/arc-ui/virtual-list';
  import type { Snippet } from 'svelte';

  interface Props {
    items?: unknown[];
    itemHeight?: number;
    overscan?: number;
    children?: Snippet;
    class?: string;
    id?: string;
    style?: string;
    title?: string;
    role?: string;
    slot?: string;
    part?: string;
    exportparts?: string;
    dir?: string;
    lang?: string;
    translate?: string;
    accesskey?: string;
    enterkeyhint?: string;
    inputmode?: string;
    popover?: string;
    contenteditable?: boolean | string;
    tabindex?: number;
    hidden?: boolean;
    inert?: boolean;
    draggable?: boolean;
    spellcheck?: boolean;
    autofocus?: boolean;
    [key: `data-${string}`]: unknown;
    [key: `aria-${string}`]: unknown;
    [key: `on${string}`]: unknown;
  }

  let { items = [], itemHeight = 40, overscan = 5, children, ...rest }: Props = $props();
</script>

<arc-virtual-list {items} {itemHeight} {overscan} {...rest}>
  {@render children?.()}
</arc-virtual-list>
