// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcAlert } from '@arclux/arc-ui/alert';

export interface AlertProps {
  variant?: 'info' | 'tip' | 'success' | 'warning' | 'error';
  live?: 'auto' | 'off' | 'polite' | 'assertive';
  density?: 'default' | 'compact';
  dismissible?: boolean;
  heading?: string;
  className?: string;
  children?: React.ReactNode;
  onArcClose?: (e: CustomEvent) => void;
}

export const Alert = createComponent({
  tagName: 'arc-alert',
  elementClass: ArcAlert,
  react: React,
  events: {
    onArcClose: 'arc-close' as EventName<CustomEvent>,
  },
});
