// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcBanner } from '@arclux/arc-ui/banner';

export interface BannerProps {
  variant?: 'info' | 'success' | 'warning' | 'error';
  dismissible?: boolean;
  sticky?: boolean;
  className?: string;
  children?: React.ReactNode;
  onArcClose?: (e: CustomEvent) => void;
}

export const Banner = createComponent({
  tagName: 'arc-banner',
  elementClass: ArcBanner,
  react: React,
  events: {
    onArcClose: 'arc-close' as EventName<CustomEvent>,
  },
});
