// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcContextMenu } from '@arclux/arc-ui';

export interface ContextMenuProps {
  open?: boolean;
  _x?: string;
  _y?: string;
  _activeIndex?: string;
  _children?: string;
  className?: string;
  children?: React.ReactNode;
  onArcOpen?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  onArcSelect?: (e: CustomEvent) => void;
  onClick?: (e: Event) => void;
}

export const ContextMenu = createComponent({
  tagName: 'arc-context-menu',
  elementClass: ArcContextMenu,
  react: React,
  events: {
    onArcOpen: 'arc-open' as EventName<CustomEvent>,
    onArcClose: 'arc-close' as EventName<CustomEvent>,
    onArcSelect: 'arc-select' as EventName<CustomEvent>,
    onClick: 'click' as EventName<Event>,
  },
});
