// Auto-generated by @arclux/prism 3.0.0 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcModal } from '@arclux/arc-ui/modal';

export interface ModalProps {
  open?: boolean;
  heading?: string;
  size?: 'sm' | 'md' | 'lg';
  fullscreen?: boolean;
  dismissible?: boolean;
  closable?: boolean;
  className?: string;
  children?: React.ReactNode;
  onArcOpen?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
}

export const Modal = createComponent({
  tagName: 'arc-modal',
  elementClass: ArcModal,
  react: React,
  events: {
    onArcOpen: 'arc-open' as EventName<CustomEvent>,
    onArcClose: 'arc-close' as EventName<CustomEvent>,
  },
});
