// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcPopover } from '@arclux/arc-ui/popover';

export interface PopoverProps {
  open?: boolean;
  position?: 'top' | 'bottom' | 'left' | 'right';
  trigger?: string;
  className?: string;
  children?: React.ReactNode;
  onArcOpen?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
}

export const Popover = createComponent({
  tagName: 'arc-popover',
  elementClass: ArcPopover,
  react: React,
  events: {
    onArcOpen: 'arc-open' as EventName<CustomEvent>,
    onArcClose: 'arc-close' as EventName<CustomEvent>,
  },
});
