// Auto-generated by @arclux/prism — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcToast } from '@arclux/arc-ui';

export interface ToastProps {
  position?: 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center';
  duration?: number;
  _toasts?: string;
  className?: string;
  children?: React.ReactNode;
  onArcDismiss?: (e: CustomEvent) => void;
}

export const Toast = createComponent({
  tagName: 'arc-toast',
  elementClass: ArcToast,
  react: React,
  events: {
    onArcDismiss: 'arc-dismiss' as EventName<CustomEvent>,
  },
});
