// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import React from 'react';
import { createComponent, type EventName } from '@lit/react';
import { ArcToast } from '@arclux/arc-ui/toast';

export interface ToastProps {
  position?: 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center';
  duration?: number;
  maxVisible?: number;
  dedupe?: boolean;
  queueLimit?: number;
  className?: string;
  onArcQueueOverflow?: (e: CustomEvent) => void;
  onArcQueueChange?: (e: CustomEvent) => void;
  onArcComplete?: (e: CustomEvent) => void;
  onArcCancel?: (e: CustomEvent) => void;
  onArcAction?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
}

export const Toast = createComponent({
  tagName: 'arc-toast',
  elementClass: ArcToast,
  react: React,
  events: {
    onArcQueueOverflow: 'arc-queue-overflow' as EventName<CustomEvent>,
    onArcQueueChange: 'arc-queue-change' as EventName<CustomEvent>,
    onArcComplete: 'arc-complete' as EventName<CustomEvent>,
    onArcCancel: 'arc-cancel' as EventName<CustomEvent>,
    onArcAction: 'arc-action' as EventName<CustomEvent>,
    onArcClose: 'arc-close' as EventName<CustomEvent>,
  },
});
