// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/center';

export interface CenterProps {
  maxWidth?: string;
  intrinsic?: boolean;
  text?: boolean;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Center: FunctionComponent<CenterProps> = ({ maxWidth, intrinsic, text, children, ...rest }) =>
  h('arc-center', { maxWidth, intrinsic, text, ...rest }, children);
