// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/float-bar';

export interface FloatBarProps {
  open?: boolean;
  position?: 'top';
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const FloatBar: FunctionComponent<FloatBarProps> = ({ open, position, children, ...rest }) => (
  <arc-float-bar open={open} position={position} {...rest}>
    {children}
  </arc-float-bar>
);
