// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/toolbar';

export interface ToolbarProps {
  sticky?: boolean;
  size?: 'sm';
  border?: boolean;
  overflow?: boolean;
  onArcOverflowChange?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Toolbar: FunctionComponent<ToolbarProps> = ({ sticky, size, border, overflow, onArcOverflowChange, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcOverflowChange) {
      const fn: EventListener = (e) => onArcOverflowChange(e as CustomEvent);
      el.addEventListener('arc-overflow-change', fn);
      listeners.push(['arc-overflow-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcOverflowChange]);
  return (
    <arc-toolbar ref={ref} sticky={sticky} size={size} border={border} overflow={overflow} {...rest}>
      {children}
    </arc-toolbar>
  );
};
