// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface AlertProps {
  variant?: string;
  compact?: boolean;
  dismissible?: boolean;
  heading?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Alert: Component<AlertProps> = (props) => {
  const [local, rest] = splitProps(props, ['variant', 'compact', 'dismissible', 'heading', 'children']);
  return (
    <arc-alert variant={local.variant} compact={local.compact} dismissible={local.dismissible} heading={local.heading} {...rest}>
      {local.children}
    </arc-alert>
  );
};
