// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/banner';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-banner': Record<string, unknown>;
    }
  }
}

export interface BannerProps {
  variant?: 'info' | 'success' | 'warning' | 'error';
  dismissible?: boolean;
  sticky?: boolean;
  onArcDismiss?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Banner: Component<BannerProps> = (props) => {
  const [local, rest] = splitProps(props, ['variant', 'dismissible', 'sticky', 'onArcDismiss', 'children']);
  return (
    <arc-banner variant={local.variant} dismissible={local.dismissible} sticky={local.sticky} on:arc-dismiss={local.onArcDismiss} {...rest}>
      {local.children}
    </arc-banner>
  );
};
