// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface BannerProps {
  variant?: string;
  dismissible?: boolean;
  sticky?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Banner: Component<BannerProps> = (props) => {
  const [local, rest] = splitProps(props, ['variant', 'dismissible', 'sticky', 'children']);
  return (
    <arc-banner variant={local.variant} dismissible={local.dismissible} sticky={local.sticky} {...rest}>
      {local.children}
    </arc-banner>
  );
};
