// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/command-item';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-command-item': Record<string, unknown>;
    }
  }
}

export interface CommandItemProps {
  shortcut?: string;
  icon?: string;
  keywords?: string;
  description?: string;
  value?: string;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const CommandItem: Component<CommandItemProps> = (props) => {
  const [local, rest] = splitProps(props, ['shortcut', 'icon', 'keywords', 'description', 'value', 'children']);
  return (
    <arc-command-item shortcut={local.shortcut} icon={local.icon} keywords={local.keywords} description={local.description} value={local.value} {...rest}>
      {local.children}
    </arc-command-item>
  );
};
