// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/command-palette';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-command-palette': Record<string, unknown>;
    }
  }
}

export interface CommandPaletteProps {
  open?: boolean;
  placeholder?: string;
  maxResults?: number;
  onArcSelect?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const CommandPalette: Component<CommandPaletteProps> = (props) => {
  const [local, rest] = splitProps(props, ['open', 'placeholder', 'maxResults', 'onArcSelect', 'onArcClose', 'children']);
  return (
    <arc-command-palette open={local.open} placeholder={local.placeholder} prop:maxResults={local.maxResults} on:arc-select={local.onArcSelect} on:arc-close={local.onArcClose} {...rest}>
      {local.children}
    </arc-command-palette>
  );
};
