// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface ConfirmProps {
  open?: boolean;
  heading?: string;
  message?: string;
  variant?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Confirm: Component<ConfirmProps> = (props) => {
  const [local, rest] = splitProps(props, ['open', 'heading', 'message', 'variant', 'children']);
  return (
    <arc-confirm open={local.open} heading={local.heading} message={local.message} variant={local.variant} {...rest}>
      {local.children}
    </arc-confirm>
  );
};
