// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/confirm';

export interface ConfirmProps {
  open?: boolean;
  heading?: string;
  message?: string;
  confirmLabel?: string;
  cancelLabel?: string;
  variant?: string;
  onArcConfirm?: (e: CustomEvent) => void;
  onArcCancel?: (e: CustomEvent) => void;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Confirm: Component<ConfirmProps> = (props) => {
  const [local, rest] = splitProps(props, ['open', 'heading', 'message', 'confirmLabel', 'cancelLabel', 'variant', 'onArcConfirm', 'onArcCancel', 'children']);
  return (
    <arc-confirm open={local.open} heading={local.heading} message={local.message} confirmLabel={local.confirmLabel} cancelLabel={local.cancelLabel} variant={local.variant} on:arc-confirm={local.onArcConfirm} on:arc-cancel={local.onArcCancel} {...rest}>
      {local.children}
    </arc-confirm>
  );
};
