// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui';

export interface LoadingOverlayProps {
  active?: boolean;
  message?: string;
  global?: boolean;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const LoadingOverlay: Component<LoadingOverlayProps> = (props) => {
  const [local, rest] = splitProps(props, ['active', 'message', 'global', 'children']);
  return (
    <arc-loading-overlay active={local.active} message={local.message} global={local.global} {...rest}>
      {local.children}
    </arc-loading-overlay>
  );
};
