// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/sheet';

export interface SheetProps {
  open?: boolean;
  side?: 'bottom' | 'right';
  heading?: string;
  children?: JSX.Element;
  [key: string]: unknown;
}

export const Sheet: Component<SheetProps> = (props) => {
  const [local, rest] = splitProps(props, ['open', 'side', 'heading', 'children']);
  return (
    <arc-sheet open={local.open} side={local.side} heading={local.heading} {...rest}>
      {local.children}
    </arc-sheet>
  );
};
