// Auto-generated by @arclux/prism — do not edit manually

import { splitProps, type Component, type JSX } from 'solid-js';
import '@arclux/arc-ui/toast';

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-toast': Record<string, unknown>;
    }
  }
}

export interface ToastProps {
  position?: 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center';
  duration?: number;
  onArcClose?: (e: CustomEvent) => void;
  children?: JSX.Element;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Toast: Component<ToastProps> = (props) => {
  const [local, rest] = splitProps(props, ['position', 'duration', 'onArcClose', 'children']);
  return (
    <arc-toast position={local.position} duration={local.duration} on:arc-close={local.onArcClose} {...rest}>
      {local.children}
    </arc-toast>
  );
};
