// Auto-generated by @arclux/prism 3.1.1 — do not edit manually

import { splitProps, type Component } from 'solid-js';
import '@arclux/arc-ui/toast';
import type { ArcToast } from '@arclux/arc-ui/toast';

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'arc-toast': Record<string, unknown>;
    }
  }
}

export interface ToastProps {
  position?: 'top-right' | 'top-left' | 'top-center' | 'bottom-right' | 'bottom-left' | 'bottom-center';
  duration?: number;
  maxVisible?: number;
  dedupe?: boolean;
  queueLimit?: number;
  onArcQueueOverflow?: (e: CustomEvent) => void;
  onArcQueueChange?: (e: CustomEvent) => void;
  onArcComplete?: (e: CustomEvent) => void;
  onArcCancel?: (e: CustomEvent) => void;
  onArcAction?: (e: CustomEvent) => void;
  onArcClose?: (e: CustomEvent) => void;
  /** The element, for the methods it is driven by: show(), dismiss(), clear(), updateToast() and complete(). */
  ref?: ArcToast | ((el: ArcToast) => void);
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Toast: Component<ToastProps> = (props) => {
  const [local, rest] = splitProps(props, ['position', 'duration', 'maxVisible', 'dedupe', 'queueLimit', 'onArcQueueOverflow', 'onArcQueueChange', 'onArcComplete', 'onArcCancel', 'onArcAction', 'onArcClose', 'ref']);
  return (
    <arc-toast position={local.position} duration={local.duration} prop:maxVisible={local.maxVisible} dedupe={local.dedupe} prop:queueLimit={local.queueLimit} on:arc-queue-overflow={local.onArcQueueOverflow} on:arc-queue-change={local.onArcQueueChange} on:arc-complete={local.onArcComplete} on:arc-cancel={local.onArcCancel} on:arc-action={local.onArcAction} on:arc-close={local.onArcClose} ref={(el: ArcToast) => { if (typeof local.ref === 'function') local.ref(el); }} {...rest}>
    </arc-toast>
  );
};
