<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/blockquote';

defineOptions({ name: 'Blockquote' });

withDefaults(defineProps<{
  cite?: string;
  variant?: string;
}>(), {
  cite: '',
  variant: 'default',
});
</script>

<template>
  <arc-blockquote
    :cite="cite"
    :variant="variant"
  >
    <slot />
  </arc-blockquote>
</template>
