<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/gradient-text';

defineOptions({ name: 'GradientText' });

const props = withDefaults(defineProps<{
  variant?: 'accent' | 'display' | 'sunset' | 'ocean' | 'custom';
  gradient?: string;
  animate?: boolean;
}>(), {
  variant: 'accent',
  gradient: '',
  animate: false,
});
</script>

<template>
  <arc-gradient-text
    :variant="props.variant"
    :gradient="props.gradient"
    :animate="props.animate"
  >
    <slot />
  </arc-gradient-text>
</template>
