<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/highlight';

defineOptions({ name: 'Highlight' });

const props = withDefaults(defineProps<{
  text?: string;
  query?: string;
  caseSensitive?: boolean;
}>(), {
  text: '',
  query: '',
});
</script>

<template>
  <arc-highlight
    :text="props.text"
    :query="props.query"
    :caseSensitive="props.caseSensitive"
  >
  </arc-highlight>
</template>
