<!-- Auto-generated by @arclux/prism 3.0.0 — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/number-format';

defineOptions({ name: 'NumberFormat' });

const props = withDefaults(defineProps<{
  value?: number;
  type?: 'number' | 'currency' | 'percent' | 'compact';
  locale?: string;
  currency?: string;
  decimals?: number;
  notation?: 'standard' | 'compact';
}>(), {
  locale: 'en-US',
  currency: 'USD',
});
</script>

<template>
  <arc-number-format
    :value="props.value"
    :type="props.type"
    :locale="props.locale"
    :currency="props.currency"
    :decimals="props.decimals"
    :notation="props.notation"
  >
  </arc-number-format>
</template>
