<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui';

defineOptions({ name: 'NumberFormat' });

withDefaults(defineProps<{
  value?: number;
  type?: string;
  locale?: string;
  currency?: string;
  decimals?: number;
  notation?: string;
}>(), {
  value: 0,
  type: 'number',
  locale: 'en-US',
  currency: 'USD',
  decimals: 'undefined',
  notation: 'standard',
});
</script>

<template>
  <arc-number-format
    :value="value"
    :type="type"
    :locale="locale"
    :currency="currency"
    :decimals="decimals"
    :notation="notation"
  >
    <slot />
  </arc-number-format>
</template>
