<!-- Auto-generated by @arclux/prism — do not edit manually -->
<script setup lang="ts">
import '@arclux/arc-ui/typewriter';

defineOptions({ name: 'Typewriter' });

withDefaults(defineProps<{
  text?: string;
  speed?: number;
  delay?: number;
  cursor?: boolean;
  loop?: boolean;
  nowrap?: boolean;
  pauseEnd?: number;
}>(), {
  text: '',
  speed: 50,
  delay: 0,
  cursor: true,
  loop: false,
  nowrap: false,
  pauseEnd: 2000,
});

const emit = defineEmits<{
  'arc-complete': [event: CustomEvent];
}>();
</script>

<template>
  <arc-typewriter
    :text="text"
    :speed="speed"
    :delay="delay"
    :cursor="cursor"
    :loop="loop"
    :nowrap="nowrap"
    :pauseEnd="pauseEnd"
    @arc-complete="(payload: CustomEvent) => emit('arc-complete', payload)"
  >
    <slot />
  </arc-typewriter>
</template>
