// Auto-generated by @arclux/prism 3.4.0 — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/bar-list';

export interface BarListProps {
  items?: unknown[];
  max?: number;
  limit?: number;
  unsorted?: boolean;
  unit?: string;
  label?: string;
  reference?: number;
  referenceLabel?: string;
  referenceDisplay?: string;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const BarList: FunctionComponent<BarListProps> = ({ items, max, limit, unsorted, unit, label, reference, referenceLabel, referenceDisplay, children, ...rest }) =>
  h('arc-bar-list', { items, max, limit, unsorted, unit, label, reference, referenceLabel, referenceDisplay, ...rest }, children);
