// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/data-table';

export interface DataTableProps {
  rows?: unknown[];
  sortable?: boolean;
  selectable?: boolean;
  sortColumn?: string;
  sortDirection?: string;
  virtual?: boolean;
  rowHeight?: number;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const DataTable: FunctionComponent<DataTableProps> = ({ rows, sortable, selectable, sortColumn, sortDirection, virtual, rowHeight, children, ...rest }) => (
  <arc-data-table rows={rows} sortable={sortable} selectable={selectable} sortColumn={sortColumn} sortDirection={sortDirection} virtual={virtual} rowHeight={rowHeight} {...rest}>
    {children}
  </arc-data-table>
);
