// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/data-grid';

export interface DataGridProps {
  columns?: Array<{key:string,label:string,sortable?:boolean,editable?:boolean,pinned?:boolean,width?:string,align?:string}>;
  rows?: Array<Record<string, any>>;
  sort?: Array<{key:string,direction:'asc'|'desc'}>;
  manualSort?: boolean;
  selectable?: boolean;
  virtual?: boolean;
  rowHeight?: number;
  onArcSort?: (e: CustomEvent) => void;
  onArcSelect?: (e: CustomEvent) => void;
  onArcCellChange?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const DataGrid: FunctionComponent<DataGridProps> = ({ columns, rows, sort, manualSort, selectable, virtual, rowHeight, onArcSort, onArcSelect, onArcCellChange, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcSort) {
      const fn: EventListener = (e) => onArcSort(e as CustomEvent);
      el.addEventListener('arc-sort', fn);
      listeners.push(['arc-sort', fn]);
    }
    if (onArcSelect) {
      const fn: EventListener = (e) => onArcSelect(e as CustomEvent);
      el.addEventListener('arc-select', fn);
      listeners.push(['arc-select', fn]);
    }
    if (onArcCellChange) {
      const fn: EventListener = (e) => onArcCellChange(e as CustomEvent);
      el.addEventListener('arc-cell-change', fn);
      listeners.push(['arc-cell-change', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcSort, onArcSelect, onArcCellChange]);
  return h('arc-data-grid', { ref, columns, rows, sort, manualSort, selectable, virtual, rowHeight, ...rest });
};
