// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/event-calendar';

export interface EventCalendarProps {
  locale?: string;
  firstDayOfWeek?: number;
  events?: Array<{date:string,end?:string,label:string,color?:number}>;
  view?: 'month' | 'week';
  date?: string;
  onArcPeriodChange?: (e: CustomEvent) => void;
  onArcDateClick?: (e: CustomEvent) => void;
  onArcEventClick?: (e: CustomEvent) => void;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const EventCalendar: FunctionComponent<EventCalendarProps> = ({ locale, firstDayOfWeek, events, view, date, onArcPeriodChange, onArcDateClick, onArcEventClick, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcPeriodChange) {
      const fn: EventListener = (e) => onArcPeriodChange(e as CustomEvent);
      el.addEventListener('arc-period-change', fn);
      listeners.push(['arc-period-change', fn]);
    }
    if (onArcDateClick) {
      const fn: EventListener = (e) => onArcDateClick(e as CustomEvent);
      el.addEventListener('arc-date-click', fn);
      listeners.push(['arc-date-click', fn]);
    }
    if (onArcEventClick) {
      const fn: EventListener = (e) => onArcEventClick(e as CustomEvent);
      el.addEventListener('arc-event-click', fn);
      listeners.push(['arc-event-click', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcPeriodChange, onArcDateClick, onArcEventClick]);
  return h('arc-event-calendar', { ref, locale, firstDayOfWeek, events, view, date, ...rest });
};
