// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/kanban';

export interface KanbanProps {
  columns?: Array<{id:string,title?:string,limit?:number,items:Array<{id:string,label:string,description?:string,tag?:string,variant?:string}>}>;
  disabled?: boolean;
  onArcCardMove?: (e: CustomEvent) => void;
  onArcCardClick?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const Kanban: FunctionComponent<KanbanProps> = ({ columns, disabled, onArcCardMove, onArcCardClick, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcCardMove) {
      const fn: EventListener = (e) => onArcCardMove(e as CustomEvent);
      el.addEventListener('arc-card-move', fn);
      listeners.push(['arc-card-move', fn]);
    }
    if (onArcCardClick) {
      const fn: EventListener = (e) => onArcCardClick(e as CustomEvent);
      el.addEventListener('arc-card-click', fn);
      listeners.push(['arc-card-click', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcCardMove, onArcCardClick]);
  return (
    <arc-kanban ref={ref} columns={columns} disabled={disabled} {...rest}>
      {children}
    </arc-kanban>
  );
};
