// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import { useLayoutEffect, useRef } from 'preact/hooks';
import '@arclux/arc-ui/list';

export interface ListProps {
  variant?: 'default' | 'bordered' | 'separated';
  size?: 'sm' | 'md' | 'lg';
  selectable?: boolean;
  multiple?: boolean;
  value?: string;
  label?: string;
  onArcChange?: (e: CustomEvent) => void;
  onArcSelect?: (e: CustomEvent) => void;
  children?: preact.ComponentChildren;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const List: FunctionComponent<ListProps> = ({ variant, size, selectable, multiple, value, label, onArcChange, onArcSelect, children, ...rest }) => {
  const ref = useRef<HTMLElement>(null);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const listeners: Array<[string, EventListener]> = [];
    if (onArcChange) {
      const fn: EventListener = (e) => onArcChange(e as CustomEvent);
      el.addEventListener('arc-change', fn);
      listeners.push(['arc-change', fn]);
    }
    if (onArcSelect) {
      const fn: EventListener = (e) => onArcSelect(e as CustomEvent);
      el.addEventListener('arc-select', fn);
      listeners.push(['arc-select', fn]);
    }
    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));
  }, [onArcChange, onArcSelect]);
  return h('arc-list', { ref, variant, size, selectable, multiple, value, label, ...rest }, children);
};
