// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/timeline';

export interface TimelineProps {
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Timeline: FunctionComponent<TimelineProps> = ({ children, ...rest }) => (
  <arc-timeline {...rest}>
    {children}
  </arc-timeline>
);
