// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/blockquote';

export interface BlockquoteProps {
  cite?: string;
  variant?: 'accent';
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Blockquote: FunctionComponent<BlockquoteProps> = ({ cite, variant, children, ...rest }) => (
  <arc-blockquote cite={cite} variant={variant} {...rest}>
    {children}
  </arc-blockquote>
);
