// Auto-generated by @arclux/prism — do not edit manually

import { h, type FunctionComponent } from 'preact';
import '@arclux/arc-ui/keyboard-map';

export interface KeyboardMapProps {
  layout?: string;
  highlight?: string|string[];
  labels?: string;
  platform?: string;
  caption?: string;
  class?: string;
  id?: string;
  style?: string;
  title?: string;
  role?: string;
  slot?: string;
  part?: string;
  exportparts?: string;
  dir?: string;
  lang?: string;
  translate?: string;
  accesskey?: string;
  enterkeyhint?: string;
  inputmode?: string;
  popover?: string;
  contenteditable?: boolean | string;
  tabindex?: number;
  hidden?: boolean;
  inert?: boolean;
  draggable?: boolean;
  spellcheck?: boolean;
  autofocus?: boolean;
  [key: `data-${string}`]: unknown;
  [key: `aria-${string}`]: unknown;
  [key: `on${string}`]: unknown;
}

export const KeyboardMap: FunctionComponent<KeyboardMapProps> = ({ layout, highlight, labels, platform, caption, ...rest }) =>
  h('arc-keyboard-map', { layout, highlight, labels, platform, caption, ...rest });
