// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui/text';

export interface TextProps {
  variant?: 'accent' | 'code';
  as?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const Text: FunctionComponent<TextProps> = ({ variant, as, children, ...rest }) => (
  <arc-text variant={variant} as={as} {...rest}>
    {children}
  </arc-text>
);
