// Auto-generated by @arclux/prism — do not edit manually

import { type FunctionComponent } from 'preact';
import '@arclux/arc-ui';

export interface TimeAgoProps {
  datetime?: string;
  live?: boolean;
  locale?: string;
  children?: preact.ComponentChildren;
  [key: string]: unknown;
}

export const TimeAgo: FunctionComponent<TimeAgoProps> = ({ datetime, live, locale, children, ...rest }) => (
  <arc-time-ago datetime={datetime} live={live} locale={locale} {...rest}>
    {children}
  </arc-time-ago>
);
